<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    Get-Module AWSCustomizations -All | Remove-Module -Force -ErrorAction SilentlyContinue
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$PSScriptRoot/../../../src/CharlandCustomizations/Public/AWS/AWSCustomizations.psm1" -Force
}

Describe 'Find-CHARCFNStackError' -Tag 'Unit' {

    BeforeAll {
        $moduleName = 'AWSCustomizations'

        # Mock Get-STSCallerIdentity to prevent live AWS calls
        Mock Get-STSCallerIdentity {
            [PSCustomObject]@{ Account = '123456789012' }
        } -ModuleName $moduleName

        # Mock Get-CFNStack returning mix of stacks with and without StackStatusReason
        Mock Get-CFNStack {
            @(
                [PSCustomObject]@{
                    StackName         = 'FailingStack1'
                    StackStatus       = 'UPDATE_ROLLBACK_COMPLETE'
                    StackStatusReason = 'Update successful. One or more resources could not be deleted.'
                    StackId           = 'arn:aws:cloudformation:us-east-1:123456789012:stack/FailingStack1/guid1'
                    RootId            = $null
                },
                [PSCustomObject]@{
                    StackName         = 'HealthyStack1'
                    StackStatus       = 'CREATE_COMPLETE'
                    StackStatusReason = $null
                    StackId           = 'arn:aws:cloudformation:us-east-1:123456789012:stack/HealthyStack1/guid2'
                    RootId            = $null
                },
                [PSCustomObject]@{
                    StackName         = 'FailingStack2'
                    StackStatus       = 'CREATE_FAILED'
                    StackStatusReason = 'Resource creation cancelled'
                    StackId           = 'arn:aws:cloudformation:us-east-1:123456789012:stack/FailingStack2/guid3'
                    RootId            = $null
                },
                [PSCustomObject]@{
                    StackName         = 'HealthyStack2'
                    StackStatus       = 'UPDATE_COMPLETE'
                    StackStatusReason = $null
                    StackId           = 'arn:aws:cloudformation:us-east-1:123456789012:stack/HealthyStack2/guid4'
                    RootId            = $null
                }
            )
        } -ModuleName $moduleName

        # Mock Get-CFNStackResourceSummary to return resources with errors
        Mock Get-CFNStackResourceSummary {
            @(
                [PSCustomObject]@{
                    ResourceStatus       = 'UPDATE_FAILED'
                    LogicalResourceId    = 'MyLambdaFunction'
                    ResourceStatusReason = 'Resource update cancelled'
                }
            )
        } -ModuleName $moduleName

        # Mock Format-Table to pass through pipeline objects (accepts -AutoSize to match SUT usage)
        Mock Format-Table {
            param(
                [Parameter(ValueFromPipeline)]$InputObject,
                [switch]$AutoSize
            )
            process { $InputObject }
        } -ModuleName $moduleName
    }

    Context 'Stacks with non-null StackStatusReason are included, null excluded (Req 3.2)' {

        It 'Includes stacks with non-null StackStatusReason in output' {
            # Act — capture all output including formatted objects
            $output = Find-CHARCFNStackError *>&1 | Out-String

            # Assert — stacks with errors appear in output
            $output | Should -Match 'FailingStack1'
            $output | Should -Match 'FailingStack2'
        }

        It 'Excludes stacks with null StackStatusReason from error output' {
            # Act
            $output = Find-CHARCFNStackError *>&1 | Out-String

            # Assert — healthy stacks do not appear anywhere in the output
            $output | Should -Not -Match 'HealthyStack1'
            $output | Should -Not -Match 'HealthyStack2'
        }

        It 'Calls Get-CFNStackResourceSummary only for stacks with errors' {
            # Act
            Find-CHARCFNStackError *>&1 | Out-Null

            # Assert — Get-CFNStackResourceSummary called for each error stack
            Should -Invoke Get-CFNStackResourceSummary -ModuleName $moduleName -Times 2 -Exactly
        }
    }

    Context 'Property: Stack error filtering' {
        # Feature: pester-test-coverage, Property 4: Stack error filtering
        # **Validates: Requirements 3.2**

        It 'Returns only stacks with non-null StackStatusReason across 100 random collections' {
            foreach ($i in 1..100) {
                # Generate a random collection of stacks (2-10 stacks per iteration)
                $stackCount = Get-Random -Minimum 2 -Maximum 11
                $stacks = @()
                $expectedErrorStacks = @()

                for ($s = 0; $s -lt $stackCount; $s++) {
                    $stackName = "Stack-$i-$s"
                    # Randomly decide if this stack has a non-null StackStatusReason
                    $hasReason = (Get-Random -Minimum 0 -Maximum 2) -eq 1
                    $reason = if ($hasReason) {
                        # Generate a random reason string
                        -join ((65..90) + (97..122) | Get-Random -Count (Get-Random -Minimum 5 -Maximum 30) | ForEach-Object { [char]$_ })
                    } else { $null }

                    $stack = [PSCustomObject]@{
                        StackName         = $stackName
                        StackStatus       = @('CREATE_COMPLETE', 'UPDATE_COMPLETE', 'UPDATE_ROLLBACK_COMPLETE', 'CREATE_FAILED') | Get-Random
                        StackStatusReason = $reason
                        StackId           = "arn:aws:cloudformation:us-east-1:123456789012:stack/$stackName/guid-$s"
                        RootId            = $null
                    }
                    $stacks += $stack

                    if ($hasReason) {
                        $expectedErrorStacks += $stackName
                    }
                }

                # Mock Get-CFNStack to return this iteration's random stacks
                Mock Get-CFNStack { $stacks } -ModuleName $moduleName

                # Mock Get-CFNStackResourceSummary to return empty (we only care about stack filtering)
                Mock Get-CFNStackResourceSummary { @() } -ModuleName $moduleName

                # Act — capture all output
                $output = Find-CHARCFNStackError *>&1 | Out-String

                # Assert — each stack with non-null reason appears in output
                foreach ($name in $expectedErrorStacks) {
                    $output | Should -Match $name
                }

                # Assert — stacks with null reason do NOT appear in output (except the header line)
                $nullReasonStacks = $stacks | Where-Object { $null -eq $_.StackStatusReason } | Select-Object -ExpandProperty StackName
                foreach ($name in $nullReasonStacks) {
                    $output | Should -Not -Match $name
                }
            }
        }
    }
}
