<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Get-Module AWSCustomizations, CharlandCustomizations | Remove-Module -Force -ErrorAction SilentlyContinue
    Import-Module "$PSScriptRoot/../../../src/CharlandCustomizations/Public/AWS/AWSCustomizations.psm1" -Force
}

<<<<<<<< HEAD:tests/Unit/AWS/Remove-CCExpiredAWSProfiles.Tests.ps1
<<<<<<<< HEAD:tests/Unit/AWS/Remove-CCExpiredAWSProfile.Tests.ps1
Describe 'Remove-CCExpiredAWSProfile' -Tag 'Unit' {
========
Describe 'Remove-CCExpiredAWSProfiles' -Tag 'Unit' {
>>>>>>>> e6f2a92 (refactored/removed DefaultCommandPrefix from manifest):tests/Unit/AWS/Remove-CCExpiredAWSProfiles.Tests.ps1
========
Describe 'Remove-CCExpiredAWSProfile' -Tag 'Unit' {
>>>>>>>> 58fc8f6 (refactor: rename functions to use singular nouns):tests/Unit/AWS/Remove-CCExpiredAWSProfile.Tests.ps1

    Context 'Expired profile (ExpiredToken error)' {

        It 'Calls Remove-AWSCredentialProfile for profile with ExpiredToken error' {
            # Arrange
            Mock Get-AWSCredential {
                @(
                    [PSCustomObject]@{ ProfileName = 'expired-profile'; ProfileLocation = '~/.aws/credentials' }
                )
            } -ModuleName AWSCustomizations

            Mock Set-AWSCredential {} -ModuleName AWSCustomizations

            Mock Get-STSCallerIdentity {
                throw 'The security token included in the request is invalid'
            } -ModuleName AWSCustomizations

            Mock Remove-AWSCredentialProfile {} -ModuleName AWSCustomizations

            # Act
<<<<<<<< HEAD:tests/Unit/AWS/Remove-CCExpiredAWSProfiles.Tests.ps1
<<<<<<<< HEAD:tests/Unit/AWS/Remove-CCExpiredAWSProfile.Tests.ps1
            Remove-CCExpiredAWSProfile
========
            Remove-CCExpiredAWSProfiles
>>>>>>>> e6f2a92 (refactored/removed DefaultCommandPrefix from manifest):tests/Unit/AWS/Remove-CCExpiredAWSProfiles.Tests.ps1
========
            Remove-CCExpiredAWSProfile
>>>>>>>> 58fc8f6 (refactor: rename functions to use singular nouns):tests/Unit/AWS/Remove-CCExpiredAWSProfile.Tests.ps1

            # Assert (Req 3.5)
            Should -Invoke Remove-AWSCredentialProfile -ModuleName AWSCustomizations -Times 1 -Exactly
        }
    }

    Context 'Valid profile (Get-STSCallerIdentity succeeds)' {

        It 'Does not call Remove-AWSCredentialProfile for valid profiles' {
            # Arrange
            Mock Get-AWSCredential {
                @(
                    [PSCustomObject]@{ ProfileName = 'valid-profile'; ProfileLocation = '~/.aws/credentials' }
                )
            } -ModuleName AWSCustomizations

            Mock Set-AWSCredential {} -ModuleName AWSCustomizations

            Mock Get-STSCallerIdentity {
                [PSCustomObject]@{ Account = '123456789012'; Arn = 'arn:aws:iam::123456789012:user/test' }
            } -ModuleName AWSCustomizations

            Mock Remove-AWSCredentialProfile {} -ModuleName AWSCustomizations

            # Act
<<<<<<<< HEAD:tests/Unit/AWS/Remove-CCExpiredAWSProfiles.Tests.ps1
<<<<<<<< HEAD:tests/Unit/AWS/Remove-CCExpiredAWSProfile.Tests.ps1
            Remove-CCExpiredAWSProfile
========
            Remove-CCExpiredAWSProfiles
>>>>>>>> e6f2a92 (refactored/removed DefaultCommandPrefix from manifest):tests/Unit/AWS/Remove-CCExpiredAWSProfiles.Tests.ps1
========
            Remove-CCExpiredAWSProfile
>>>>>>>> 58fc8f6 (refactor: rename functions to use singular nouns):tests/Unit/AWS/Remove-CCExpiredAWSProfile.Tests.ps1

            # Assert (Req 3.13)
            Should -Invoke Remove-AWSCredentialProfile -ModuleName AWSCustomizations -Times 0 -Exactly
        }
    }

    Context 'WhatIf behavior' {

        It 'Does not call Remove-AWSCredentialProfile when WhatIf is used' {
            # Arrange
            Mock Get-AWSCredential {
                @(
                    [PSCustomObject]@{ ProfileName = 'expired-profile'; ProfileLocation = '~/.aws/credentials' }
                )
            } -ModuleName AWSCustomizations

            Mock Get-STSCallerIdentity {
                throw 'The security token included in the request is invalid'
            } -ModuleName AWSCustomizations

            Mock Remove-AWSCredentialProfile {} -ModuleName AWSCustomizations

            # Act
            Remove-CCExpiredAWSProfile -WhatIf

            # Assert
            Should -Invoke Remove-AWSCredentialProfile -ModuleName AWSCustomizations -Times 0 -Exactly
        }
    }

    Context 'Force behavior' {

        It 'Passes Force to Remove-AWSCredentialProfile when Force is specified' {
            # Arrange
            Mock Get-AWSCredential {
                @(
                    [PSCustomObject]@{ ProfileName = 'expired-profile'; ProfileLocation = '~/.aws/credentials' }
                )
            } -ModuleName AWSCustomizations

            Mock Get-STSCallerIdentity {
                throw 'The security token included in the request is invalid'
            } -ModuleName AWSCustomizations

            Mock Remove-AWSCredentialProfile {} -ModuleName AWSCustomizations

            # Act
            Remove-CCExpiredAWSProfile -Force -Confirm:$false

            # Assert
            Should -Invoke Remove-AWSCredentialProfile -ModuleName AWSCustomizations -Times 1 -Exactly -ParameterFilter { $Force }
        }
    }
}
