<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    # Remove any previously loaded version to avoid conflicts
    Get-Module -Name AWSCustomizations -All | Remove-Module -Force -ErrorAction SilentlyContinue
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    # Import the module from source
    $modulePath = "$PSScriptRoot/../../../src/CharlandCustomizations/Public/AWS/AWSCustomizations.psm1"
    Import-Module $modulePath -Force
}

Describe 'Set-AWSProfileWithMFA' -Tag 'Unit' {

    BeforeAll {
        $moduleName = 'AWSCustomizations'

        # Mock Get-DefaultAWSRegion to provide a fallback region
        Mock Get-DefaultAWSRegion { [PSCustomObject]@{ Region = 'us-east-1' } } -ModuleName $moduleName

        # Mock Set-AWSCredential (called as AWS bug workaround)
        Mock Set-AWSCredential {} -ModuleName $moduleName

        # Mock Get-IAMMFADevice to return a fake MFA device
        Mock Get-IAMMFADevice {
            [PSCustomObject]@{ SerialNumber = 'arn:aws:iam::123456789012:mfa/user' }
        } -ModuleName $moduleName

        # Mock Get-STSSessionToken to return fake credentials
        Mock Get-STSSessionToken {
            [PSCustomObject]@{
                AccessKeyId     = 'AKIAIOSFODNN7EXAMPLE'
                SecretAccessKey = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
                SessionToken    = 'FwoGZXIvYXdzEBYaDH...'
                Expiration      = (Get-Date).AddHours(12)
            }
        } -ModuleName $moduleName
    }

    Context 'Happy path' {

        It 'Calls Get-STSSessionToken with correct SerialNumber and TokenCode' {
            # Arrange
            $expectedSerial = 'arn:aws:iam::123456789012:mfa/user'
            $expectedToken = '123456'

            # Act
            $result = Set-AWSProfileWithMFA -ProfileName 'myprofile' -TokenCode $expectedToken

            # Assert — verify Get-STSSessionToken was called with the correct parameters
            Should -Invoke Get-STSSessionToken -ModuleName $moduleName -Times 1 -Exactly -ParameterFilter {
                $SerialNumber -eq $expectedSerial -and $TokenCode -eq $expectedToken
            }

            # Assert — verify the function returns the STS session token result
            $result.AccessKeyId | Should -Be 'AKIAIOSFODNN7EXAMPLE'
        }

        It 'Calls Set-AWSCredential with ProfileName as AWS bug workaround' {
            # Act
            Set-AWSProfileWithMFA -ProfileName 'testprofile' -TokenCode '654321'

            # Assert — verify Set-AWSCredential is called with the profile name
            Should -Invoke Set-AWSCredential -ModuleName $moduleName -Times 1 -Exactly -ParameterFilter {
                $ProfileName -eq 'testprofile'
            }
        }

        It 'Uses Get-DefaultAWSRegion when Region is not specified' {
            # Act
            Set-AWSProfileWithMFA -ProfileName 'myprofile' -TokenCode '111111'

            # Assert — verify Get-DefaultAWSRegion was called for fallback
            Should -Invoke Get-DefaultAWSRegion -ModuleName $moduleName -Times 1
        }
    }
}
