<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    Get-Module AWSCustomizations -All | Remove-Module -Force -ErrorAction SilentlyContinue
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$PSScriptRoot/../../../src/CharlandCustomizations/Public/AWS/AWSCustomizations.psm1" -Force
}

Describe 'Set-CCAWSEnv' -Tag 'Unit' {

    BeforeAll {
        $moduleName = 'AWSCustomizations'

        # Mock Get-AWSCredential to return object with GetCredentials() method
        Mock Get-AWSCredential {
            $creds = [PSCustomObject]@{
                AccessKey = 'AKIAIOSFODNN7EXAMPLE'
                SecretKey = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
                UseToken  = $true
                Token     = 'FwoGZXIvYXdzEBYaDHtoken123'
            }
            # Return an object with a GetCredentials() method that returns the creds
            $wrapper = [PSCustomObject]@{}
            $wrapper | Add-Member -MemberType ScriptMethod -Name 'GetCredentials' -Value { $creds }.GetNewClosure()
            $wrapper
        } -ModuleName $moduleName

        # Mock Get-STSCallerIdentity
        Mock Get-STSCallerIdentity {
            [PSCustomObject]@{
                Account = '123456789012'
                Arn     = 'arn:aws:iam::123456789012:user/testuser'
            }
        } -ModuleName $moduleName

        # Mock Get-DefaultAWSRegion
        Mock Get-DefaultAWSRegion {
            [PSCustomObject]@{ Region = 'us-east-1' }
        } -ModuleName $moduleName

        # Mock Write-Host to suppress output during tests
        Mock Write-Host {} -ModuleName $moduleName
    }

    Context 'WhatIf does not modify environment variables (Req 3.4)' {

        It 'Does not change AWS environment variables when -WhatIf is specified' {
            # Arrange — save current env var values
            $originalAccessKey = $env:AWS_ACCESS_KEY_ID
            $originalRegion = $env:AWS_DEFAULT_REGION
            $originalSecretKey = $env:AWS_SECRET_ACCESS_KEY
            $originalSessionToken = $env:AWS_SESSION_TOKEN

            # Act — call with -WhatIf
            Set-CCAWSEnv -WhatIf

            # Assert — env vars should remain unchanged
            $env:AWS_ACCESS_KEY_ID | Should -Be $originalAccessKey
            $env:AWS_DEFAULT_REGION | Should -Be $originalRegion
            $env:AWS_SECRET_ACCESS_KEY | Should -Be $originalSecretKey
            $env:AWS_SESSION_TOKEN | Should -Be $originalSessionToken
        }
    }
}
