<#
.NOTES
    Generated by Copilot, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$PSScriptRoot/../../../../../src/CharlandCustomizations/Public/AWS/ACM/ACM-Customizations.psm1" -Force

    $script:testRoot = Join-Path ([System.IO.Path]::GetTempPath()) "Export-CHARPfxCertificatePem_$([guid]::NewGuid().ToString('N'))"
    New-Item -ItemType Directory -Path $script:testRoot -Force | Out-Null

    $script:testPfxPath = Join-Path $script:testRoot 'unit-test-certificate.pfx'
    $script:testPasswordPlain = 'P@ssw0rd!'
    $script:testPasswordSecure = ConvertTo-SecureString -String $script:testPasswordPlain -AsPlainText -Force

    $rsa = [System.Security.Cryptography.RSA]::Create(2048)
    try {
        $request = [System.Security.Cryptography.X509Certificates.CertificateRequest]::new(
            'CN=unit-test.example',
            $rsa,
            [System.Security.Cryptography.HashAlgorithmName]::SHA256,
            [System.Security.Cryptography.RSASignaturePadding]::Pkcs1
        )
        $certificate = $request.CreateSelfSigned(
            [DateTimeOffset]::UtcNow.AddDays(-1),
            [DateTimeOffset]::UtcNow.AddDays(30)
        )
        try {
            $pfxBytes = $certificate.Export(
                [System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx,
                $script:testPasswordPlain
            )
            [System.IO.File]::WriteAllBytes($script:testPfxPath, $pfxBytes)
        }
        finally {
            $certificate.Dispose()
        }
    }
    finally {
        $rsa.Dispose()
    }
}

AfterAll {
    if (Test-Path $script:testRoot) {
        Remove-Item -Path $script:testRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}

Describe 'Export-CHARPfxCertificatePem' -Tag 'Unit' {

    It 'Saves certificate, private key, and chain PEM files to the specified directory' {
        $pemOutputDir = Join-Path $script:testRoot 'pem-output'

        $result = Export-CHARPfxCertificatePem -PfxPath $script:testPfxPath -Password $script:testPasswordSecure -OutputPath $pemOutputDir

        $result | Should -Not -BeNullOrEmpty
        $result.CertificateArn | Should -BeNullOrEmpty
        $result.PemOutputPath | Should -Be (Resolve-Path $pemOutputDir).ProviderPath
        @($result.SavedPemFiles).Count | Should -Be 3

        $baseName = [System.IO.Path]::GetFileNameWithoutExtension($script:testPfxPath)
        $certificatePath = Join-Path $pemOutputDir "$baseName-certificate.pem"
        $privateKeyPath = Join-Path $pemOutputDir "$baseName-private-key.pem"
        $chainPath = Join-Path $pemOutputDir "$baseName-chain.pem"

        Test-Path $certificatePath | Should -BeTrue
        Test-Path $privateKeyPath | Should -BeTrue
        Test-Path $chainPath | Should -BeTrue

        (Get-Content -Path $certificatePath -Raw) | Should -Match '-----BEGIN CERTIFICATE-----'
        (Get-Content -Path $privateKeyPath -Raw) | Should -Match '-----BEGIN PRIVATE KEY-----'
    }

    It 'Supports WhatIf and does not write PEM files to disk' {
        $whatIfOutputDir = Join-Path $script:testRoot 'whatif-pem-output'

        $result = Export-CHARPfxCertificatePem -PfxPath $script:testPfxPath -Password $script:testPasswordSecure -OutputPath $whatIfOutputDir -WhatIf

        $result.CertificateArn | Should -BeNullOrEmpty
        @($result.SavedPemFiles).Count | Should -Be 0
        Test-Path $whatIfOutputDir | Should -BeFalse
    }

    It 'Throws when the PFX path does not exist' {
        {
            Export-CHARPfxCertificatePem -PfxPath (Join-Path $script:testRoot 'missing-file.pfx')
        } | Should -Throw '*PFX file not found*'
    }
}
