<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    # Stub AWS cmdlets that may not be installed locally
    $script:awsStubs = @('Get-AWSCredential', 'Get-STSCallerIdentity', 'Get-IAMAccountAlias')
    foreach ($cmd in $script:awsStubs) {
        if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
            Set-Item -Path "function:global:$cmd" -Value { } -Force
        }
    }

    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/AWSCustomizations.psm1" -Force
}

AfterAll {
    foreach ($cmd in $script:awsStubs) {
        if (Test-Path "function:global:$cmd") {
            Remove-Item "function:global:$cmd" -ErrorAction SilentlyContinue
        }
    }
}

Describe 'Get-CHARAccountListFromProfile' -Tag 'Unit' {

    BeforeEach {
        Mock Get-AWSCredential -ModuleName AWSCustomizations {
            @(
                [PSCustomObject]@{ ProfileName = 'dev' }
                [PSCustomObject]@{ ProfileName = 'prod' }
            )
        } -ParameterFilter { $ListProfileDetail -eq $true }

        Mock Get-STSCallerIdentity -ModuleName AWSCustomizations {
            if ($ProfileName -eq 'dev') {
                [PSCustomObject]@{ Account = '111111111111' }
            } else {
                [PSCustomObject]@{ Account = '222222222222' }
            }
        }

        Mock Get-IAMAccountAlias -ModuleName AWSCustomizations {
            if ($ProfileName -eq 'dev') { 'dev-account' }
            else { 'prod-account' }
        }
    }

    It 'Returns one object per profile' {
        $results = @(Get-CHARAccountListFromProfile)
        $results.Count | Should -Be 2
    }

    It 'Includes ProfileName in output' {
        $results = @(Get-CHARAccountListFromProfile)
        $results[0].Profilename | Should -Be 'dev'
        $results[1].Profilename | Should -Be 'prod'
    }

    It 'Includes Account from Get-STSCallerIdentity' {
        $results = @(Get-CHARAccountListFromProfile)
        $results[0].Account | Should -Be '111111111111'
        $results[1].Account | Should -Be '222222222222'
    }

    It 'Includes AccountAlias from Get-IAMAccountAlias' {
        $results = @(Get-CHARAccountListFromProfile)
        $results[0].AccountAlias | Should -Be 'dev-account'
        $results[1].AccountAlias | Should -Be 'prod-account'
    }
}
