<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/AWSCustomizations.psm1" -Force
}

Describe 'Get-CHARAccountListFromProfile' -Tag 'Unit' {

    It 'Is an available command' {
        Get-Command Get-CHARAccountListFromProfile | Should -Not -BeNullOrEmpty
    }
}
