<#
.NOTES
    Generated by Copilot, reviewed by ccharland
#>
BeforeAll {
    # Stub AWS cmdlet if AWS Tools are not installed locally.
    if (-not (Get-Command Import-ACMCertificate -ErrorAction SilentlyContinue)) {
        Set-Item -Path function:global:Import-ACMCertificate -Value {
            [CmdletBinding()]
            param(
                [byte[]]$Certificate,
                [byte[]]$PrivateKey,
                [byte[]]$CertificateChain,
                [string]$CertificateArn,
                [string]$Region
            )
        } -Force
        $script:createdImportStub = $true
    }
    if (-not (Get-Command Get-ACMCertificateDetail -ErrorAction SilentlyContinue)) {
        Set-Item -Path function:global:Get-ACMCertificateDetail -Value { } -Force
        $script:createdDetailStub = $true
    }

    . "$PSScriptRoot/../../../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$PSScriptRoot/../../../../../src/CharlandCustomizations/Public/AWS/ACM/ACM-Customizations.psm1" -Force

    $script:testRoot = Join-Path ([System.IO.Path]::GetTempPath()) "Import-CHARPfxCertificateToACM_$([guid]::NewGuid().ToString('N'))"
    New-Item -ItemType Directory -Path $script:testRoot -Force | Out-Null

    $script:testPfxPath = Join-Path $script:testRoot 'unit-test-certificate.pfx'
    $script:testPasswordPlain = 'P@ssw0rd!'
    $script:testPasswordSecure = ConvertTo-SecureString -String $script:testPasswordPlain -AsPlainText -Force

    if ($IsMacOS) {
        $testKeyPath = Join-Path $script:testRoot 'unit-test.key'
        $testCertPath = Join-Path $script:testRoot 'unit-test.crt'
        & openssl req -x509 -newkey rsa:2048 -keyout $testKeyPath -out $testCertPath -days 30 -nodes -subj '/CN=unit-test.example' -addext 'subjectAltName=DNS:unit-test.example,DNS:www.unit-test.example' 2>$null
        & openssl pkcs12 -export -legacy -out $script:testPfxPath -inkey $testKeyPath -in $testCertPath -passout "pass:$($script:testPasswordPlain)" 2>$null
        if ($LASTEXITCODE -ne 0) {
            throw 'OpenSSL failed to create the macOS PFX test fixture.'
        }
    }
    else {
        $rsa = [System.Security.Cryptography.RSA]::Create(2048)
        try {
            $request = [System.Security.Cryptography.X509Certificates.CertificateRequest]::new(
                'CN=unit-test.example',
                $rsa,
                [System.Security.Cryptography.HashAlgorithmName]::SHA256,
                [System.Security.Cryptography.RSASignaturePadding]::Pkcs1
            )
            $sanBuilder = [System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder]::new()
            $sanBuilder.AddDnsName('unit-test.example')
            $sanBuilder.AddDnsName('www.unit-test.example')
            $request.CertificateExtensions.Add($sanBuilder.Build())
            $certificate = $request.CreateSelfSigned(
                [DateTimeOffset]::UtcNow.AddDays(-1),
                [DateTimeOffset]::UtcNow.AddDays(30)
            )
            try {
                $pfxBytes = $certificate.Export(
                    [System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx,
                    $script:testPasswordPlain
                )
                [System.IO.File]::WriteAllBytes($script:testPfxPath, $pfxBytes)
            }
            finally {
                $certificate.Dispose()
            }
        }
        finally {
            $rsa.Dispose()
        }
    }
}

AfterAll {
    if (Test-Path $script:testRoot) {
        Remove-Item -Path $script:testRoot -Recurse -Force -ErrorAction SilentlyContinue
    }

    if ($script:createdImportStub -and (Test-Path function:global:Import-ACMCertificate)) {
        Remove-Item function:global:Import-ACMCertificate -Force -ErrorAction SilentlyContinue
    }
    if ($script:createdDetailStub -and (Test-Path function:global:Get-ACMCertificateDetail)) {
        Remove-Item function:global:Get-ACMCertificateDetail -Force -ErrorAction SilentlyContinue
    }
}

Describe 'Import-CHARPfxCertificateToACM' -Tag 'Unit' {

    BeforeEach {
        Mock Test-CHARAWSCmdlet { $true } -ModuleName ACM-Customizations
        Mock Import-ACMCertificate -ModuleName ACM-Customizations {
            [PSCustomObject]@{
                CertificateArn = 'arn:aws:acm:us-east-1:123456789012:certificate/test-cert'
            }
        }
        Mock Get-ACMCertificateDetail -ModuleName ACM-Customizations {
            [PSCustomObject]@{
                CertificateArn = $CertificateArn
                DomainName = 'unit-test.example'
                SubjectAlternativeNames = @('unit-test.example', 'www.unit-test.example')
            }
        }
    }

    It 'Imports a PFX file into ACM and returns metadata' {
        $result = Import-CHARPfxCertificateToACM -PfxPath $script:testPfxPath -Password $script:testPasswordSecure -Region 'us-east-1'

        $result | Should -Not -BeNullOrEmpty
        $result.CertificateArn | Should -Be 'arn:aws:acm:us-east-1:123456789012:certificate/test-cert'
        $result.SourcePath | Should -Be (Resolve-Path $script:testPfxPath).ProviderPath
        $result.SubjectAlternativeNames | Should -Contain 'unit-test.example'
        $result.SubjectAlternativeNames | Should -Contain 'www.unit-test.example'
        $result.SubjectAlternativeNameCount | Should -Be 2

        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 1
        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 1 -ParameterFilter {
            $Certificate -is [byte[]] -and $Certificate.Length -gt 0
        }
        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 1 -ParameterFilter {
            $PrivateKey -is [byte[]] -and $PrivateKey.Length -gt 0
        }
        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 1 -ParameterFilter {
            $Region -eq 'us-east-1'
        }
        Should -Invoke Test-CHARAWSCmdlet -ModuleName ACM-Customizations -Times 1 -Exactly -ParameterFilter {
            $Name -eq 'Import-ACMCertificate'
        }
    }

    It 'Supports WhatIf and does not call Import-ACMCertificate' {
        $null = Import-CHARPfxCertificateToACM -PfxPath $script:testPfxPath -Password $script:testPasswordSecure -WhatIf

        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 0
    }

    It 'accepts the certificate ARN string returned by AWS Tools by default' {
        Mock Import-ACMCertificate -ModuleName ACM-Customizations {
            'arn:aws:acm:us-east-1:123456789012:certificate/string-result'
        }

        $result = Import-CHARPfxCertificateToACM -PfxPath $script:testPfxPath -Password $script:testPasswordSecure

        $result.CertificateArn | Should -Be 'arn:aws:acm:us-east-1:123456789012:certificate/string-result'
    }

    It 'replaces an existing certificate when all DNS names match' {
        $certificateArn = 'arn:aws:acm:us-east-1:123456789012:certificate/replace'

        $result = Import-CHARPfxCertificateToACM -PfxPath $script:testPfxPath -Password $script:testPasswordSecure -CertificateArn $certificateArn -Confirm:$false

        $result.CertificateArn | Should -Be 'arn:aws:acm:us-east-1:123456789012:certificate/test-cert'
        Should -Invoke Get-ACMCertificateDetail -ModuleName ACM-Customizations -Times 1 -ParameterFilter {
            $CertificateArn -eq 'arn:aws:acm:us-east-1:123456789012:certificate/replace'
        }
        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 1 -ParameterFilter {
            $CertificateArn -eq 'arn:aws:acm:us-east-1:123456789012:certificate/replace'
        }
    }

    It 'rejects replacement certificates with different DNS names unless forced' {
        Mock Get-ACMCertificateDetail -ModuleName ACM-Customizations {
            [PSCustomObject]@{
                CertificateArn = $CertificateArn
                DomainName = 'unit-test.example'
                SubjectAlternativeNames = @('unit-test.example', 'other.example')
            }
        }
        $certificateArn = 'arn:aws:acm:us-east-1:123456789012:certificate/replace'

        {
            Import-CHARPfxCertificateToACM -PfxPath $script:testPfxPath -Password $script:testPasswordSecure -CertificateArn $certificateArn -Confirm:$false
        } | Should -Throw '*DNS names do not match*'

        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 0
    }

    It 'allows replacement with different DNS names when forced' {
        Mock Get-ACMCertificateDetail -ModuleName ACM-Customizations {
            [PSCustomObject]@{
                CertificateArn = $CertificateArn
                DomainName = 'unit-test.example'
                SubjectAlternativeNames = @('unit-test.example', 'other.example')
            }
        }

        $null = Import-CHARPfxCertificateToACM -PfxPath $script:testPfxPath -Password $script:testPasswordSecure -CertificateArn 'arn:aws:acm:us-east-1:123456789012:certificate/replace' -Force -Confirm:$false

        Should -Invoke Get-ACMCertificateDetail -ModuleName ACM-Customizations -Times 0
        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 1
    }

    It 'Throws when the PFX path does not exist' {
        {
            Import-CHARPfxCertificateToACM -PfxPath (Join-Path $script:testRoot 'missing-file.pfx')
        } | Should -Throw '*PFX file not found*'

        Should -Invoke Test-CHARAWSCmdlet -ModuleName ACM-Customizations -Times 1 -Exactly -ParameterFilter {
            $Name -eq 'Import-ACMCertificate'
        }
        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 0 -Exactly
    }

    It 'Stops before reading the PFX when the ACM module is unavailable' {
        Mock Test-CHARAWSCmdlet { throw 'ACM dependency unavailable' } -ModuleName ACM-Customizations

        {
            Import-CHARPfxCertificateToACM -PfxPath (Join-Path $script:testRoot 'missing-file.pfx')
        } | Should -Throw '*ACM dependency unavailable*'

        Should -Invoke Import-ACMCertificate -ModuleName ACM-Customizations -Times 0 -Exactly
    }
}
