<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Private/Test-CHARIsWindows.ps1"
}

Describe 'Test-CHARIsWindows' -Tag 'Unit' {

    It 'Returns a boolean value' {
        $result = Test-CHARIsWindows
        $result | Should -BeOfType [bool]
    }

    It 'Returns $true on Windows' -Skip:(-not $IsWindows) {
        Test-CHARIsWindows | Should -BeTrue
    }

    It 'Returns $false on non-Windows' -Skip:($IsWindows) {
        Test-CHARIsWindows | Should -BeFalse
    }
}
