<#
.SYNOPSIS
    AWS Certificate Manager custom functions.
#>
Write-Verbose "Loading ACM-Customizations.psm1"

. "$PSScriptRoot/../../../Private/New-AWSParamSplat.ps1"
. "$PSScriptRoot/../../Test-CHARAWSCmdlet.ps1"

$script:GetPfxCertificateMaterial = {
  param(
    [Parameter(Mandatory)]
    [string]$PfxPath,

    [Parameter()]
    [SecureString]$Password
  )

  try {
    $resolvedPfxPath = (Resolve-Path -Path $PfxPath -ErrorAction Stop).ProviderPath
  }
  catch {
    throw "PFX file not found: $PfxPath"
  }

  $convertBytesToPem = {
    param(
      [Parameter(Mandatory)]
      [byte[]]$Bytes,

      [Parameter(Mandatory)]
      [string]$Label
    )

    $base64 = [System.Convert]::ToBase64String($Bytes)
    $lines = for ($offset = 0; $offset -lt $base64.Length; $offset += 64) {
      $length = [Math]::Min(64, $base64.Length - $offset)
      $base64.Substring($offset, $length)
    }

    @(
      "-----BEGIN $Label-----"
      $lines
      "-----END $Label-----"
    ) -join "`n"
  }

  $passwordText = $null
  if ($PSBoundParameters.ContainsKey('Password') -and $null -ne $Password) {
    $passwordPtr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Password)
    try {
      $passwordText = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($passwordPtr)
    }
    finally {
      [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($passwordPtr)
    }
  }

  $pfxBytes = [System.IO.File]::ReadAllBytes($resolvedPfxPath)
  $certCollection = [System.Security.Cryptography.X509Certificates.X509Certificate2Collection]::new()
  $keyStorageFlags = [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable
  $certCollection.Import($pfxBytes, $passwordText, $keyStorageFlags)

  $leafCertificate = $certCollection | Where-Object HasPrivateKey | Select-Object -First 1
  if (-not $leafCertificate) {
    throw 'No certificate with a private key was found in the PFX file.'
  }

  $certificatePem = & $convertBytesToPem -Bytes $leafCertificate.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert) -Label 'CERTIFICATE'

  $privateKeyBytes = $null
  $rsaPrivateKey = [System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($leafCertificate)
  if ($rsaPrivateKey) {
    try {
      $privateKeyBytes = $rsaPrivateKey.ExportPkcs8PrivateKey()
    }
    finally {
      $rsaPrivateKey.Dispose()
    }
  }
  else {
    $ecdsaPrivateKey = [System.Security.Cryptography.X509Certificates.ECDsaCertificateExtensions]::GetECDsaPrivateKey($leafCertificate)
    if ($ecdsaPrivateKey) {
      try {
        $privateKeyBytes = $ecdsaPrivateKey.ExportPkcs8PrivateKey()
      }
      finally {
        $ecdsaPrivateKey.Dispose()
      }
    }
  }

  if (-not $privateKeyBytes) {
    throw 'Unsupported private key algorithm. Only RSA and ECDSA private keys are supported.'
  }

  $privateKeyPem = & $convertBytesToPem -Bytes $privateKeyBytes -Label 'PRIVATE KEY'

  $chainPemEntries = @()
  foreach ($cert in $certCollection) {
    if ($cert.Thumbprint -eq $leafCertificate.Thumbprint) {
      continue
    }

    $chainPemEntries += & $convertBytesToPem -Bytes $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert) -Label 'CERTIFICATE'
  }

  [PSCustomObject]@{
    SourcePath          = $resolvedPfxPath
    CertificatePem      = $certificatePem
    PrivateKeyPem       = $privateKeyPem
    CertificateChainPem = if ($chainPemEntries.Count -gt 0) { $chainPemEntries -join "`n" } else { $null }
    IncludedChain       = $chainPemEntries.Count -gt 0
    CertificateSubject  = $leafCertificate.Subject
    CertificateNotAfter = $leafCertificate.NotAfter
  }
}

function Export-CHARPfxCertificatePem {
  <#
.SYNOPSIS
  Converts an exported PFX certificate into PEM files.

.DESCRIPTION
  Reads a local .pfx/.p12 file, extracts the leaf certificate, private key, and
  optional certificate chain, then writes PEM files to disk.

.PARAMETER PfxPath
  Path to the exported PFX/P12 file.

.PARAMETER Password
  Optional secure password used to open the PFX file.

.PARAMETER OutputPath
  Output directory for PEM files. Defaults to the current directory.

.EXAMPLE
  Export-CHARPfxCertificatePem -PfxPath .\site.pfx -Password (Read-Host -AsSecureString)

  Writes certificate, private key, and chain PEM files for a password-protected PFX.

.EXAMPLE
  Export-CHARPfxCertificatePem -PfxPath .\site.pfx -OutputPath .\acm-export

  Saves PEM files locally to the specified directory.

.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
    Last updated: July 2026
#>
  [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'Medium')]
  param(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]$PfxPath,

    [Parameter()]
    [SecureString]$Password,

    [Parameter()]
    [string]$OutputPath = '.'
  )

  process {
    try {
      $material = & $script:GetPfxCertificateMaterial -PfxPath $PfxPath -Password $Password

      Write-Warning 'The exported private key PEM file is not encrypted. Protect the output directory appropriately.'

      try {
        $resolvedOutputPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath)
      }
      catch {
        throw "Invalid OutputPath: $OutputPath"
      }

      if (-not (Test-Path -LiteralPath $resolvedOutputPath)) {
        if ($PSCmdlet.ShouldProcess($resolvedOutputPath, 'Create output directory for PEM files')) {
          New-Item -Path $resolvedOutputPath -ItemType Directory -Force -ErrorAction Stop | Out-Null
        }
      }

      $savedFilePaths = @()
      $baseName = [System.IO.Path]::GetFileNameWithoutExtension($material.SourcePath)
      $certificatePemPath = Join-Path $resolvedOutputPath "$baseName-certificate.pem"
      $privateKeyPemPath = Join-Path $resolvedOutputPath "$baseName-private-key.pem"
      $chainPemPath = Join-Path $resolvedOutputPath "$baseName-chain.pem"

      if ($PSCmdlet.ShouldProcess($certificatePemPath, 'Write certificate PEM file')) {
        Set-Content -Path $certificatePemPath -Value $material.CertificatePem -Encoding ascii -NoNewline
        $savedFilePaths += $certificatePemPath
      }
      if ($PSCmdlet.ShouldProcess($privateKeyPemPath, 'Write private key PEM file')) {
        Set-Content -Path $privateKeyPemPath -Value $material.PrivateKeyPem -Encoding ascii -NoNewline
        $savedFilePaths += $privateKeyPemPath
      }

      $chainPemContent = if ($material.CertificateChainPem) {
        $material.CertificateChainPem
      }
      else {
        '# No additional chain certificates were present in the PFX.'
      }

      if ($PSCmdlet.ShouldProcess($chainPemPath, 'Write certificate chain PEM file')) {
        Set-Content -Path $chainPemPath -Value $chainPemContent -Encoding ascii -NoNewline
        $savedFilePaths += $chainPemPath
      }

      [PSCustomObject]@{
        CertificateArn      = $null
        SourcePath          = $material.SourcePath
        PemOutputPath       = $resolvedOutputPath
        SavedPemFiles       = @($savedFilePaths)
        IncludedChain       = $material.IncludedChain
        CertificateSubject  = $material.CertificateSubject
        CertificateNotAfter = $material.CertificateNotAfter
      }
    }
    catch {
      $PSCmdlet.ThrowTerminatingError($_)
    }
  }
}

function Import-CHARPfxCertificateToACM {
  <#
.SYNOPSIS
  Imports an exported PFX certificate into AWS ACM.

.DESCRIPTION
  Reads a local .pfx/.p12 file, extracts the leaf certificate, private key, and
  optional certificate chain, converts each to PEM, and imports them into
  AWS Certificate Manager using Import-ACMCertificate.

.PARAMETER PfxPath
  Path to the exported PFX/P12 file.

.PARAMETER Password
  Optional secure password used to open the PFX file.

.PARAMETER CertificateArn
  Optional ACM certificate ARN. When provided, ACM updates the existing
  certificate. When omitted, ACM creates a new certificate.

.PARAMETER Region
    AWS region. If not specified, uses the session default.

.PARAMETER ProfileName
    AWS profile name. Optional.

.PARAMETER AccessKey
    AWS access key. Optional.

.PARAMETER SecretKey
    AWS secret key. Optional.

.PARAMETER SessionToken
    AWS session token for temporary credentials. Optional.

.PARAMETER Credential
    Pre-built AWS credential object. Optional.

.PARAMETER ProfileLocation
    Custom credential file path. Optional.

.PARAMETER EndpointUrl
    Custom AWS service endpoint URL. Optional.

.EXAMPLE
  Import-CHARPfxCertificateToACM -PfxPath .\site.pfx -Password (Read-Host -AsSecureString)

  Imports a new certificate into ACM from a password-protected PFX file.

.EXAMPLE
  Import-CHARPfxCertificateToACM -PfxPath .\site.pfx -CertificateArn arn:aws:acm:us-east-1:123456789012:certificate/abc-def

  Re-imports (updates) an existing ACM certificate from a PFX file.

.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
    Last updated: July 2026
#>
  [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'Medium')]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'Credential',
    Justification = 'Credential parameter accepts AWSCredentials object, not a password')]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'NetworkCredential',
    Justification = 'NetworkCredential typed as [object] for pipeline compatibility')]
  param(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [string]$PfxPath,

    [Parameter()]
    [SecureString]$Password,

    [Parameter()]
    [string]$CertificateArn,

    # AWS common parameters
    [Parameter()]
    [string]$Region,

    [Parameter()]
    [string]$ProfileName,

    [Parameter()]
    [string]$AccessKey,

    [Parameter()]
    [string]$SecretKey,

    [Parameter()]
    [string]$SessionToken,

    [Parameter()]
    [object]$Credential,

    [Parameter()]
    [object]$NetworkCredential,

    [Parameter()]
    [string]$ProfileLocation,

    [Parameter()]
    [string]$EndpointUrl
  )

  begin {
    $null = Test-CHARAWSCmdlet -Name 'Import-ACMCertificate'

    $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters

  }

  process {
    try {
      $material = & $script:GetPfxCertificateMaterial -PfxPath $PfxPath -Password $Password

      $importParams = @{
        Certificate = [System.Text.Encoding]::ASCII.GetBytes($material.CertificatePem)
        PrivateKey  = [System.Text.Encoding]::ASCII.GetBytes($material.PrivateKeyPem)
        ErrorAction = 'Stop'
      }

      if ($material.CertificateChainPem) {
        $importParams['CertificateChain'] = [System.Text.Encoding]::ASCII.GetBytes($material.CertificateChainPem)
      }
      if ($CertificateArn) {
        $importParams['CertificateArn'] = $CertificateArn
      }

      foreach ($key in $awsParams.Keys) {
        $importParams[$key] = $awsParams[$key]
      }

      $target = if ($CertificateArn) { "ACM certificate '$CertificateArn'" } else { 'a new ACM certificate' }
      if ($PSCmdlet.ShouldProcess($target, "Import certificate from '$($material.SourcePath)'")) {
        $result = Import-ACMCertificate @importParams
        return [PSCustomObject]@{
          CertificateArn      = if ($result -is [string]) { $result } elseif ($result.CertificateArn) { $result.CertificateArn } else { $CertificateArn }
          SourcePath          = $material.SourcePath
          PemOutputPath       = $null
          SavedPemFiles       = @()
          IncludedChain       = $material.IncludedChain
          CertificateSubject  = $material.CertificateSubject
          CertificateNotAfter = $material.CertificateNotAfter
        }
      }
    }
    catch {
      $PSCmdlet.ThrowTerminatingError($_)
    }
  }
}

function Test-CHARPfxCertificate {
  <#
.SYNOPSIS
  Inspects a local PFX/P12 certificate file.

.DESCRIPTION
  Reads a PFX/P12 file and returns certificate identity, validity, private-key,
  and chain-validation information without exporting certificate material.

.PARAMETER PfxPath
  Path to the PFX/P12 file to inspect.

.PARAMETER Password
  Optional secure password used to open the PFX file.

.EXAMPLE
  Test-CHARPfxCertificate -PfxPath .\site.pfx -Password (Read-Host -AsSecureString)

.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
    Last updated: July 2026
#>
  [CmdletBinding()]
  param(
    [Parameter(Mandatory, ValueFromPipeline, ValueFromPipelineByPropertyName)]
    [ValidateNotNullOrEmpty()]
    [Alias('FullName')]
    [string]$PfxPath,

    [Parameter()]
    [SecureString]$Password
  )

  process {
    try {
      try {
        $resolvedPfxPath = (Resolve-Path -Path $PfxPath -ErrorAction Stop).ProviderPath
      }
      catch {
        throw "PFX file not found: $PfxPath"
      }

      $passwordText = $null
      if ($PSBoundParameters.ContainsKey('Password')) {
        $passwordPtr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Password)
        try {
          $passwordText = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($passwordPtr)
        }
        finally {
          [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($passwordPtr)
        }
      }

      $certCollection = [System.Security.Cryptography.X509Certificates.X509Certificate2Collection]::new()
      $certCollection.Import(
        [System.IO.File]::ReadAllBytes($resolvedPfxPath),
        $passwordText,
        [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::DefaultKeySet
      )

      $leafCertificate = $certCollection | Where-Object HasPrivateKey | Select-Object -First 1
      if (-not $leafCertificate) {
        $leafCertificate = $certCollection | Select-Object -First 1
      }
      if (-not $leafCertificate) {
        throw 'No certificates were found in the PFX file.'
      }

      $chain = [System.Security.Cryptography.X509Certificates.X509Chain]::new()
      try {
        $chainIsValid = $chain.Build($leafCertificate)
        $chainStatus = @($chain.ChainStatus | ForEach-Object {
          [PSCustomObject]@{
            Status            = $_.Status.ToString()
            StatusInformation = $_.StatusInformation.Trim()
          }
        })
      }
      finally {
        $chain.Dispose()
      }

      $now = [DateTime]::Now
      $daysRemaining = [Math]::Floor(($leafCertificate.NotAfter - $now).TotalDays)

      [PSCustomObject]@{
        Path              = $resolvedPfxPath
        Subject           = $leafCertificate.Subject
        Issuer            = $leafCertificate.Issuer
        DnsName           = $leafCertificate.GetNameInfo([System.Security.Cryptography.X509Certificates.X509NameType]::DnsName, $false)
        Thumbprint        = $leafCertificate.Thumbprint
        SerialNumber      = $leafCertificate.SerialNumber
        NotBefore         = $leafCertificate.NotBefore
        NotAfter          = $leafCertificate.NotAfter
        DaysRemaining     = [int]$daysRemaining
        HasPrivateKey     = $leafCertificate.HasPrivateKey
        IsExpired         = $leafCertificate.NotAfter -lt $now
        IsCurrentlyValid  = $leafCertificate.NotBefore -le $now -and $leafCertificate.NotAfter -ge $now
        ChainIsValid      = $chainIsValid
        ChainStatus       = $chainStatus
        CertificateCount  = $certCollection.Count
      }
    }
    catch {
      $PSCmdlet.ThrowTerminatingError($_)
    }
  }
}

function Test-CHARACMCertificate {
  <#
.SYNOPSIS
  Validates the status and remaining lifetime of an ACM certificate.

.DESCRIPTION
  Retrieves detailed ACM certificate metadata and reports whether the certificate
  is issued, unexpired, and valid for at least the requested number of days.

.PARAMETER CertificateArn
  ARN of the ACM certificate to validate.

.PARAMETER MinimumDaysRemaining
  Minimum acceptable remaining lifetime. Defaults to 30 days.

.EXAMPLE
  Test-CHARACMCertificate -CertificateArn $certificateArn -Region us-east-1

.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
    Last updated: July 2026
#>
  [CmdletBinding()]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'Credential',
    Justification = 'Credential parameter accepts AWSCredentials object, not a password')]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'NetworkCredential',
    Justification = 'NetworkCredential typed as [object] for pipeline compatibility')]
  param(
    [Parameter(Mandatory, ValueFromPipeline, ValueFromPipelineByPropertyName)]
    [ValidateNotNullOrEmpty()]
    [string]$CertificateArn,

    [Parameter()]
    [ValidateRange(0, 36500)]
    [int]$MinimumDaysRemaining = 30,

    [Parameter()]
    [string]$Region,
    [Parameter()]
    [string]$ProfileName,
    [Parameter()]
    [string]$AccessKey,
    [Parameter()]
    [string]$SecretKey,
    [Parameter()]
    [string]$SessionToken,
    [Parameter()]
    [object]$Credential,
    [Parameter()]
    [object]$NetworkCredential,
    [Parameter()]
    [string]$ProfileLocation,
    [Parameter()]
    [string]$EndpointUrl
  )

  begin {
    $null = Test-CHARAWSCmdlet -Name 'Get-ACMCertificateDetail'

    $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters
  }

  process {
    try {
      $detail = Get-ACMCertificateDetail -CertificateArn $CertificateArn @awsParams -ErrorAction Stop
      $now = [DateTime]::UtcNow
      $hasExpiration = $null -ne $detail.NotAfter -and ([DateTime]$detail.NotAfter) -gt [DateTime]::MinValue
      $daysRemaining = if ($hasExpiration) {
        [int][Math]::Floor((([DateTime]$detail.NotAfter).ToUniversalTime() - $now).TotalDays)
      }
      else {
        $null
      }
      $isIssued = [string]$detail.Status -eq 'ISSUED'
      $isExpired = $hasExpiration -and ([DateTime]$detail.NotAfter).ToUniversalTime() -lt $now
      $hasMinimumValidity = $hasExpiration -and $daysRemaining -ge $MinimumDaysRemaining
      $messages = @()
      if (-not $isIssued) {
        $messages += "Certificate status is '$($detail.Status)', not 'ISSUED'."
      }
      if (-not $hasExpiration) {
        $messages += 'Certificate expiration information is unavailable.'
      }
      elseif ($isExpired) {
        $messages += 'Certificate is expired.'
      }
      elseif (-not $hasMinimumValidity) {
        $messages += "Certificate has fewer than $MinimumDaysRemaining days remaining."
      }

      $certificateRegion = $Region
      if (-not $certificateRegion -and $CertificateArn -match '^arn:[^:]+:acm:([^:]+):') {
        $certificateRegion = $Matches[1]
      }

      [PSCustomObject]@{
        Region                = $certificateRegion
        CertificateArn        = $detail.CertificateArn
        DomainName            = $detail.DomainName
        Status                = [string]$detail.Status
        NotAfter              = if ($hasExpiration) { [DateTime]$detail.NotAfter } else { $null }
        DaysRemaining         = $daysRemaining
        InUseBy               = @($detail.InUseBy)
        IsIssued              = $isIssued
        IsExpired             = $isExpired
        HasMinimumValidity    = $hasMinimumValidity
        IsValid               = $isIssued -and -not $isExpired -and $hasMinimumValidity
        ValidationMessages    = @($messages)
      }
    }
    catch {
      $PSCmdlet.ThrowTerminatingError($_)
    }
  }
}

function Update-CHARPfxCertificateInACM {
  <#
.SYNOPSIS
  Replaces an imported ACM certificate with certificate material from a PFX file.

.DESCRIPTION
  Reimports certificate material into an existing ACM certificate ARN, preserving
  the ARN and its existing AWS service associations.

.EXAMPLE
  Update-CHARPfxCertificateInACM -CertificateArn $certificateArn -PfxPath .\renewed.pfx -Password (Read-Host -AsSecureString)

.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
    Last updated: July 2026
#>
  [CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'Credential',
    Justification = 'Credential parameter accepts AWSCredentials object, not a password')]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'NetworkCredential',
    Justification = 'NetworkCredential typed as [object] for pipeline compatibility')]
  param(
    [Parameter(Mandatory, ValueFromPipelineByPropertyName)]
    [ValidateNotNullOrEmpty()]
    [string]$CertificateArn,

    [Parameter(Mandatory, ValueFromPipelineByPropertyName)]
    [ValidateNotNullOrEmpty()]
    [string]$PfxPath,

    [Parameter()]
    [SecureString]$Password,

    [Parameter()]
    [string]$Region,
    [Parameter()]
    [string]$ProfileName,
    [Parameter()]
    [string]$AccessKey,
    [Parameter()]
    [string]$SecretKey,
    [Parameter()]
    [string]$SessionToken,
    [Parameter()]
    [object]$Credential,
    [Parameter()]
    [object]$NetworkCredential,
    [Parameter()]
    [string]$ProfileLocation,
    [Parameter()]
    [string]$EndpointUrl
  )

  process {
    try {
      if ($PSCmdlet.ShouldProcess($CertificateArn, "Replace ACM certificate from '$PfxPath'")) {
        $replaceParams = @{
          CertificateArn = $CertificateArn
          PfxPath        = $PfxPath
          Confirm        = $false
        }
        if ($PSBoundParameters.ContainsKey('Password')) {
          $replaceParams['Password'] = $Password
        }

        $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters
        foreach ($key in $awsParams.Keys) {
          $replaceParams[$key] = $awsParams[$key]
        }

        Import-CHARPfxCertificateToACM @replaceParams
      }
    }
    catch {
      $PSCmdlet.ThrowTerminatingError($_)
    }
  }
}

function Get-CHARACMCertificateInventory {
  <#
.SYNOPSIS
  Returns an inventory of ACM certificates in an AWS region.

.DESCRIPTION
  Lists ACM certificates and retrieves each certificate's detailed status,
  expiration date, remaining lifetime, and service associations.

.EXAMPLE
  Get-CHARACMCertificateInventory -Region us-east-1 -ProfileName production

.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
    Last updated: July 2026
#>
  [CmdletBinding()]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'Credential',
    Justification = 'Credential parameter accepts AWSCredentials object, not a password')]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingPlainTextForPassword', 'NetworkCredential',
    Justification = 'NetworkCredential typed as [object] for pipeline compatibility')]
  param(
    [Parameter()]
    [string]$Region,
    [Parameter()]
    [string]$ProfileName,
    [Parameter()]
    [string]$AccessKey,
    [Parameter()]
    [string]$SecretKey,
    [Parameter()]
    [string]$SessionToken,
    [Parameter()]
    [object]$Credential,
    [Parameter()]
    [object]$NetworkCredential,
    [Parameter()]
    [string]$ProfileLocation,
    [Parameter()]
    [string]$EndpointUrl
  )

  begin {
    $null = Test-CHARAWSCmdlet -Name 'Get-ACMCertificateList'

    $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters
  }

  process {
    try {
      $certificateSummaries = @(Get-ACMCertificateList @awsParams -ErrorAction Stop)
      foreach ($summary in $certificateSummaries) {
        $detail = Get-ACMCertificateDetail -CertificateArn $summary.CertificateArn @awsParams -ErrorAction Stop
        $hasExpiration = $null -ne $detail.NotAfter -and ([DateTime]$detail.NotAfter) -gt [DateTime]::MinValue
        $daysRemaining = if ($hasExpiration) {
          [int][Math]::Floor((([DateTime]$detail.NotAfter).ToUniversalTime() - [DateTime]::UtcNow).TotalDays)
        }
        else {
          $null
        }

        $certificateRegion = $Region
        if (-not $certificateRegion -and $detail.CertificateArn -match '^arn:[^:]+:acm:([^:]+):') {
          $certificateRegion = $Matches[1]
        }

        [PSCustomObject]@{
          Region          = $certificateRegion
          CertificateArn  = $detail.CertificateArn
          DomainName      = $detail.DomainName
          Status          = [string]$detail.Status
          NotAfter        = if ($hasExpiration) { [DateTime]$detail.NotAfter } else { $null }
          DaysRemaining   = $daysRemaining
          InUseBy         = @($detail.InUseBy)
        }
      }
    }
    catch {
      $PSCmdlet.ThrowTerminatingError($_)
    }
  }
}

try {
  Write-Verbose "Attempting to export ACM module members"
  Export-ModuleMember -Function @(
    'Export-CHARPfxCertificatePem'
    'Get-CHARACMCertificateInventory'
    'Import-CHARPfxCertificateToACM'
    'Test-CHARACMCertificate'
    'Test-CHARPfxCertificate'
    'Update-CHARPfxCertificateInACM'
  )
}
catch {
  Write-Verbose 'OK: someone is dot sourcing this script'
}
finally {
  Write-Verbose 'Finished loading ACM-Customizations.psm1'
}

# SIG # Begin signature block
# MIIgywYJKoZIhvcNAQcCoIIgvDCCILgCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCh9OZXfpIsv5qv
# 3tTKtI9aIQZz4vsJhIT0DLKYDZyBCKCCG1gwggN5MIIC/qADAgECAhAcz51nzeIZ
# /xLZmv82guWnMAoGCCqGSM49BAMDMHwxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVU
# ZXhhczEQMA4GA1UEBwwHSG91c3RvbjEYMBYGA1UECgwPU1NMIENvcnBvcmF0aW9u
# MTEwLwYDVQQDDChTU0wuY29tIFJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkg
# RUNDMB4XDTE5MDMwNzE5MzU0N1oXDTM0MDMwMzE5MzU0N1oweDELMAkGA1UEBhMC
# VVMxDjAMBgNVBAgMBVRleGFzMRAwDgYDVQQHDAdIb3VzdG9uMREwDwYDVQQKDAhT
# U0wgQ29ycDE0MDIGA1UEAwwrU1NMLmNvbSBDb2RlIFNpZ25pbmcgSW50ZXJtZWRp
# YXRlIENBIEVDQyBSMjB2MBAGByqGSM49AgEGBSuBBAAiA2IABOpt7gyJbfdl1TyX
# rJy6JZGueJwq39d2z/FOJTbnNRuYrlS823MWKvLp+ziKPRCumlXWYiCS5X0xZxWv
# 2FIxsD9Tf7tCm8JcqSsa6W8uRyjXT+yEBglVRcOJGZiIjeFxJKOCAUcwggFDMBIG
# A1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUgtGFczDnNQTTjgKS++Wk0cQh
# 6M0weAYIKwYBBQUHAQEEbDBqMEYGCCsGAQUFBzAChjpodHRwOi8vd3d3LnNzbC5j
# b20vcmVwb3NpdG9yeS9TU0xjb20tUm9vdENBLUVDQy0zODQtUjEuY3J0MCAGCCsG
# AQUFBzABhhRodHRwOi8vb2NzcHMuc3NsLmNvbTARBgNVHSAECjAIMAYGBFUdIAAw
# EwYDVR0lBAwwCgYIKwYBBQUHAwMwOwYDVR0fBDQwMjAwoC6gLIYqaHR0cDovL2Ny
# bHMuc3NsLmNvbS9zc2wuY29tLWVjYy1Sb290Q0EuY3JsMB0GA1UdDgQWBBQyeLEO
# kNtGzxrPtmMRbf4w52dUMDAOBgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwMDaQAw
# ZgIxAIZwNaUUH2Oi1OfK9PES0J4Ay3EIm1mAOjpxEHItL3pSmV+5tJ/iQQqK2Dwg
# evkxFQIxAIHLuf6CWo8Wvxn2XZR/+3do0Q/XjqQSbfhJlqwRUVPlxUz5aK1vpJwv
# LRHaPzhzXTCCA8AwggNHoAMCAQICEFEd7vPtDKtYV7OYcsTNL88wCgYIKoZIzj0E
# AwMweDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVRleGFzMRAwDgYDVQQHDAdIb3Vz
# dG9uMREwDwYDVQQKDAhTU0wgQ29ycDE0MDIGA1UEAwwrU1NMLmNvbSBDb2RlIFNp
# Z25pbmcgSW50ZXJtZWRpYXRlIENBIEVDQyBSMjAeFw0yNjA4MDcxOTA3NTdaFw0y
# NzExMDgxOTA3NTdaMHkxCzAJBgNVBAYTAlVTMRYwFAYDVQQIDA1OZXcgSGFtcHNo
# aXJlMRQwEgYDVQQHDAtOZXcgSXBzd2ljaDEdMBsGA1UECgwUQ2hyaXN0b3BoZXIg
# Q2hhcmxhbmQxHTAbBgNVBAMMFENocmlzdG9waGVyIENoYXJsYW5kMHYwEAYHKoZI
# zj0CAQYFK4EEACIDYgAEnBTifag8qbU07/B2aFtw7h3deXWsME/+F18vvlqQOnQg
# 5YNQyYRisw1XkwtXq2m1AMiqAddMEVOkmxIi71eYqVi87p/RQct3k/HuXi/clk4C
# YqaYFCEpq7tFMUDd8cUCo4IBkzCCAY8wDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAW
# gBQyeLEOkNtGzxrPtmMRbf4w52dUMDB5BggrBgEFBQcBAQRtMGswRwYIKwYBBQUH
# MAKGO2h0dHA6Ly9jZXJ0LnNzbC5jb20vU1NMY29tLVN1YkNBLWNvZGVTaWduaW5n
# LUVDQy0zODQtUjIuY2VyMCAGCCsGAQUFBzABhhRodHRwOi8vb2NzcHMuc3NsLmNv
# bTBRBgNVHSAESjBIMAgGBmeBDAEEATA8BgwrBgEEAYKpMAEDAwEwLDAqBggrBgEF
# BQcCARYeaHR0cHM6Ly93d3cuc3NsLmNvbS9yZXBvc2l0b3J5MBMGA1UdJQQMMAoG
# CCsGAQUFBwMDMEwGA1UdHwRFMEMwQaA/oD2GO2h0dHA6Ly9jcmxzLnNzbC5jb20v
# U1NMY29tLVN1YkNBLWNvZGVTaWduaW5nLUVDQy0zODQtUjIuY3JsMB0GA1UdDgQW
# BBRaKfdK1zqVgfdqPHp69Ump7V7QDjAOBgNVHQ8BAf8EBAMCB4AwCgYIKoZIzj0E
# AwMDZwAwZAIwfyXRtBRHbkmoEP6vHjnUe6Xb6WUcfzZ+r2mFqz3pxpokqXkdYfbn
# ySinlBy2oScEAjAmFdwaA7/yG/M+bPD8UviQ9p13KC3R2X1eXbRlCoRwLwdKSF89
# FQPG4jtmL9FPIawwggaCMIIEaqADAgECAhA2wrC9fBs656Oz3TbLyXVoMA0GCSqG
# SIb3DQEBDAUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKTmV3IEplcnNleTEU
# MBIGA1UEBxMLSmVyc2V5IENpdHkxHjAcBgNVBAoTFVRoZSBVU0VSVFJVU1QgTmV0
# d29yazEuMCwGA1UEAxMlVVNFUlRydXN0IFJTQSBDZXJ0aWZpY2F0aW9uIEF1dGhv
# cml0eTAeFw0yMTAzMjIwMDAwMDBaFw0zODAxMTgyMzU5NTlaMFcxCzAJBgNVBAYT
# AkdCMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxLjAsBgNVBAMTJVNlY3RpZ28g
# UHVibGljIFRpbWUgU3RhbXBpbmcgUm9vdCBSNDYwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQCIndi5RWedHd3ouSaBmlRUwHxJBZvMWhUP2ZQQRLRBQIF3
# FJmp1OR2LMgIU14g0JIlL6VXWKmdbmKGRDILRxEtZdQnOh2qmcxGzjqemIk8et8s
# E6J+N+Gl1cnZocew8eCAawKLu4TRrCoqCAT8uRjDeypoGJrruH/drCio28aqIVEn
# 45NZiZQI7YYBex48eL78lQ0BrHeSmqy1uXe9xN04aG0pKG9ki+PC6VEfzutu6Q3I
# cZZfm00r9YAEp/4aeiLhyaKxLuhKKaAdQjRaf/h6U13jQEV1JnUTCm511n5avv4N
# +jSVwd+Wb8UMOs4netapq5Q/yGyiQOgjsP/JRUj0MAT9YrcmXcLgsrAimfWY3MzK
# m1HCxcquinTqbs1Q0d2VMMQyi9cAgMYC9jKc+3mW62/yVl4jnDcw6ULJsBkOkrcP
# LUwqj7poS0T2+2JMzPP+jZ1h90/QpZnBkhdtixMiWDVgh60KmLmzXiqJc6lGwqoU
# qpq/1HVHm+Pc2B6+wCy/GwCcjw5rmzajLbmqGygEgaj/OLoanEWP6Y52Hflef3XL
# vYnhEY4kSirMQhtberRvaI+5YsD3XVxHGBjlIli5u+NrLedIxsE88WzKXqZjj9Zi
# 5ybJL2WjeXuOTbswB7XjkZbErg7ebeAQUQiS/uRGZ58NHs57ZPUfECcgJC+v2wID
# AQABo4IBFjCCARIwHwYDVR0jBBgwFoAUU3m/WqorSs9UgOHYm8Cd8rIDZsswHQYD
# VR0OBBYEFPZ3at0//QET/xahbIICL9AKPRQlMA4GA1UdDwEB/wQEAwIBhjAPBgNV
# HRMBAf8EBTADAQH/MBMGA1UdJQQMMAoGCCsGAQUFBwMIMBEGA1UdIAQKMAgwBgYE
# VR0gADBQBgNVHR8ESTBHMEWgQ6BBhj9odHRwOi8vY3JsLnVzZXJ0cnVzdC5jb20v
# VVNFUlRydXN0UlNBQ2VydGlmaWNhdGlvbkF1dGhvcml0eS5jcmwwNQYIKwYBBQUH
# AQEEKTAnMCUGCCsGAQUFBzABhhlodHRwOi8vb2NzcC51c2VydHJ1c3QuY29tMA0G
# CSqGSIb3DQEBDAUAA4ICAQAOvmVB7WhEuOWhxdQRh+S3OyWM637ayBeR7djxQ8Si
# hTnLf2sABFoB0DFR6JfWS0snf6WDG2gtCGflwVvcYXZJJlFfym1Doi+4PfDP8s0c
# qlDmdfyGOwMtGGzJ4iImyaz3IBae91g50QyrVbrUoT0mUGQHbRcF57olpfHhQESt
# z5i6hJvVLFV/ueQ21SM99zG4W2tB1ExGL98idX8ChsTwbD/zIExAopoe3l6JrzJt
# Pxj8V9rocAnLP2C8Q5wXVVZcbw4x4ztXLsGzqZIiRh5i111TW7HV1AtsQa6vXy63
# 3vCAbAOIaKcLAo/IU7sClyZUk62XD0VUnHD+YvVNvIGezjM6CRpcWed/ODiptK+e
# vDKPU2K6synimYBaNH49v9Ih24+eYXNtI38byt5kIvh+8aW88WThRpv8lUJKaPn3
# 7+YHYafob9Rg7LyTrSYpyZoBmwRWSE4W6iPjB7wJjJpH29308ZkpKKdpkiS9WNsf
# /eeUtvRrtIEiSJHN899L1P4l6zKVsdrUu1FX1T/ubSrsxrYJD+3f3aKg6yxdbugo
# t06YwGXXiy5UUGZvOu3lXlxA+fC13dQ5OlL2gIb5lmF6Ii8+CQOYDwXM+yd9dbmo
# cQsHjcRPsccUd5E9FiswEqORvz8g3s+jR3SFCgXhN4wz7NgAnOgpCdUo4uDyllU9
# PzCCBqcwggSPoAMCAQICEQCQrAhyIP3Fp8RrXMcN9z0GMA0GCSqGSIb3DQEBDAUA
# MFcxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxLjAsBgNV
# BAMTJVNlY3RpZ28gUHVibGljIFRpbWUgU3RhbXBpbmcgUm9vdCBSNDYwHhcNMjYw
# MzI1MDAwMDAwWhcNNDEwMzI0MjM1OTU5WjBVMQswCQYDVQQGEwJHQjEYMBYGA1UE
# ChMPU2VjdGlnbyBMaW1pdGVkMSwwKgYDVQQDEyNTZWN0aWdvIFB1YmxpYyBUaW1l
# IFN0YW1waW5nIENBIFI0MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AK7kSqIBrYIcYvlmLVuaA8zw1RfBhkn4G1CoemzjcYtML6yNUvKmwGH7y6/5MuSC
# 1UYP/+9KYDSqvMQt/1hEKHYxMAD9oZpBkoaDQFEKbOJHelsKe+BaO0ZcENTKfePc
# raVkA7wrGAW2XHA5gQCQv4IKori/3PNOXxnDMOk8yIMgVrlMeTxqfWJ4XkjT1xc2
# s9DD7URHWWJOFobTPoWs6mrDFlaY9FlAHDYTfbzvxQHVsvRmn3W+5ZmCwyk02I8K
# gGPT/UX4sTz41GiR+ppwUjQXa1+2tEHZbsdAKUtH3OPEVtZvlt7atx4h83IdRR8o
# Yi8wjY3OjFKXFecWpQbzzsPxbUKPwMWiTrzwkrFa8dH/1pDKRJt371W62PfqKPay
# Cr/XbnBOlRn8CALSmHnRtGzuAWtTJpcT3BKw6oy8IIL6wSbu938F6ZIbRNIc1dKb
# IJtr4ULN6R5ZfTdNEhwXctqp3RHDbg4fuOl6LjNoaFwjud92EEDhzxFJzE1jqN4c
# sceZIwxOT1aqfsfh0uFQE/lgTBuBs3i6/WL2W1OceWLy3XEdXRK1f0EWCuea6dNf
# X2RRdjUfk5EltFnJkN2+bWhnK14OPRKcyjOv5hKZ0iV4NRNd1+hjtva1rPyzb5Bs
# 7EvFxqEQhgZbOq7qH3nm0rBwA0dxniBOYCFPdu246JCxAgMBAAGjggFuMIIBajAf
# BgNVHSMEGDAWgBT2d2rdP/0BE/8WoWyCAi/QCj0UJTAdBgNVHQ4EFgQUOnSlDGfG
# QlDC/bX8x7spNIL0erkwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8C
# AQAwEwYDVR0lBAwwCgYIKwYBBQUHAwgwIwYDVR0gBBwwGjAIBgZngQwBBAIwDgYM
# KwYBBAGyMQECAQMIMEwGA1UdHwRFMEMwQaA/oD2GO2h0dHA6Ly9jcmwuc2VjdGln
# by5jb20vU2VjdGlnb1B1YmxpY1RpbWVTdGFtcGluZ1Jvb3RSNDYuY3JsMHwGCCsG
# AQUFBwEBBHAwbjBHBggrBgEFBQcwAoY7aHR0cDovL2NydC5zZWN0aWdvLmNvbS9T
# ZWN0aWdvUHVibGljVGltZVN0YW1waW5nUm9vdFI0Ni5wN2MwIwYIKwYBBQUHMAGG
# F2h0dHA6Ly9vY3NwLnNlY3RpZ28uY29tMA0GCSqGSIb3DQEBDAUAA4ICAQAy3lJH
# ZvGeA2b43yhzoarvobHVzbfl+RfuPDwej0wCQkYAN6scTt2GwFe22qbOCv/tllqF
# lLKQZE+E9jVyuPTbyQHwrM7R0oLapAEDC1+CowsqSRf/ptira5Pfd4PoHICnb9co
# PQtyZmHSQp5y9IGvqWf1qNfq7V2fHZ8DvEQrLUzeoGF9BJRYu2OzacW3QQtUum3N
# OVf0gPRwv6I4991uhncJ6VP4lcpUpHZKB7R3hiIUC09mR9KjzPVnXHvL9n2bAwiU
# ECfK5Zezhiw27F2tgi39DETfU8M4n0N6xLgFzsf05M5GURX8C9+IX9V6kpmmKtrU
# zMti4LD66gtmf+mSm934K81NL6YQeMEk1rpYrWPypcW76Mir6wb1AgseLIHqn/Gk
# euQm7zOTDf3f5WoX14qVNjZWNHF3JxkutV6ZnhinfCLfdv5bnwKWUfceqOajCVnt
# I6uCbHxjBg6SCsexc5AfIGno7gVFvwifT4XONPsSUaJ71XsJ+EvciVUVnjOO4qxm
# 0fWJTd8a7jP8mc4ZPqwJvQFtOp7+6G+kUJAF0fnE8YgD8uttBReNTa1YmAeFMiqc
# 38e8fI4eLm0zjM/eeGCHasnoqqrbGwcF41iz9HXzFDwN4iD5z3QShp6HRiU3UpTw
# DJiiXcr0z6pjl7PyzJ3/tmWtGehV7CAfc/WlyzCCBuIwggTKoAMCAQICEQDnTvJV
# sFBP+tum3/f8i6MVMA0GCSqGSIb3DQEBDAUAMFUxCzAJBgNVBAYTAkdCMRgwFgYD
# VQQKEw9TZWN0aWdvIExpbWl0ZWQxLDAqBgNVBAMTI1NlY3RpZ28gUHVibGljIFRp
# bWUgU3RhbXBpbmcgQ0EgUjQxMB4XDTI2MDMyNTAwMDAwMFoXDTM3MDYyNDIzNTk1
# OVowcjELMAkGA1UEBhMCR0IxFzAVBgNVBAgTDkdyZWF0ZXIgTG9uZG9uMRgwFgYD
# VQQKEw9TZWN0aWdvIExpbWl0ZWQxMDAuBgNVBAMTJ1NlY3RpZ28gUHVibGljIFRp
# bWUgU3RhbXBpbmcgU2lnbmVyIFIzNzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCC
# AgoCggIBALL/w21L3FDZRS0FEXfZuPtUrefibnRSqOT/NNyJLOJhXjQfUspqHT+g
# SSVgbjYThUI/cO+wFQHoOakKQNnSMKdkE8gR69ofXlkk5DAVY/ZlevliOUmlvrw2
# Vuz4SU28rHfb/Vgd17eqpRIvJuO6XE8vPpPzn4c4iorszUF6nwuynKEQ/+rqfDmQ
# bFNKsa+5+Z4f4kXwKdUFxUwUDjQWUhiHRwMlUWGF9N91aAvL+9a4sxCgqR/ez8W8
# HJ/XqvSu1vIeb+J6bDFKKgkv3PJkMMpQ0BsdeXR2FejZXFRXY1w9dZe6gqyMv7px
# +TpWbYMefECUV0WxoEMgXUk6RKcLo94uUHOdmfZu4Xe8ghglyro3/N4VEKTj8dcP
# PvOBGxFEx1QH6uHKTkWhloGPDScurcZnd8KUtTHl6zmlQDHM04MwGfsmQViKnYEA
# YE8RHl5XRE6GTq0ZMb59SIyJX6+CODVic/kW+dhbIS1Z5AP8HaGne/PRG+12QzSn
# eKDJp3Ot+k4GrmmlWT9iy6FNCQ/32K+d4cAZ+Ll7uWbEn6Z6gE+tEu7MyZvzWvPN
# sRKMkcyyflFW1zpRyzutwypALXc9Qg7sFsYERNXa58KZXqU9Onc/tck6+adQJFM9
# tW8xOnE//P5I4eDj84IGGKqzgUD37ihC+WST3DfY0YBKWL0ZaubnAgMBAAGjggGO
# MIIBijAfBgNVHSMEGDAWgBQ6dKUMZ8ZCUML9tfzHuyk0gvR6uTAdBgNVHQ4EFgQU
# YRDpehKvUcSF1PLPpHQPUM0gr/gwDgYDVR0PAQH/BAQDAgbAMAwGA1UdEwEB/wQC
# MAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwSgYDVR0gBEMwQTAIBgZngQwBBAIw
# NQYMKwYBBAGyMQECAQMIMCUwIwYIKwYBBQUHAgEWF2h0dHBzOi8vc2VjdGlnby5j
# b20vQ1BTMEoGA1UdHwRDMEEwP6A9oDuGOWh0dHA6Ly9jcmwuc2VjdGlnby5jb20v
# U2VjdGlnb1B1YmxpY1RpbWVTdGFtcGluZ0NBUjQxLmNybDB6BggrBgEFBQcBAQRu
# MGwwRQYIKwYBBQUHMAKGOWh0dHA6Ly9jcnQuc2VjdGlnby5jb20vU2VjdGlnb1B1
# YmxpY1RpbWVTdGFtcGluZ0NBUjQxLmNydDAjBggrBgEFBQcwAYYXaHR0cDovL29j
# c3Auc2VjdGlnby5jb20wDQYJKoZIhvcNAQEMBQADggIBAAPqPY3RrM36GXqTpsoH
# n9TpW5I6z3dkFvc9zPL1W0Egq7j3jtnkbAvRoWeAjGX4ZK4sWsmA+u4EJG8okQmy
# buS/4tDUI5UIQb21n4hG2vihxShrneWB0VoQ2VLQ3jCCRmRtAQ+/7H7WVKNiH5Pg
# l4v2ZTOdPsStzpKnl1YuRrmww/+bcZmLqgk909ywIpZqAfubYfbEMYjIckLk90f2
# mG+L8qaGSS2JJVM02pV5XltZ1fbOFETpRN/PQhwygIv33qUUjJ1fE4ITgw0McMzR
# qziWdOJP8ocxxw7qXxz1OdRWCalyL1qvUgAFnZTVdSRiMYZKf0wLcQcM/1Xf1W4F
# W9nff8ERX8RZJGt/TtPuMWmUpf6BCv9Q6o8YyUTtknvZRpSQ0nLttWXdtwsrN2mM
# gfMuR//gxVrVXvDzCoK/lbiA6dEZOW53lQwBFtEzwE/FH8JdhegyYg4PymZOTZrG
# BEvgsbxe25yEhJ0IdGa1pwCYsarldJhJVMdNcAOU7jyIMqHcczav3wtIXp/SwbXZ
# 3xX0mfsLfANSJ47G4qPgx1atb6GIlTaQXzu/p4fTQeAIUVzZXT4K984IyfuO7NLj
# WMtog1wGUpZD98pv+4Mt9Y5bvfPUjaUVjtePy1DVdi0rl5ESNYi0zyOmXVxtA5zz
# xu1H7RdLZOZugT/XjX69rY9bMYIEyTCCBMUCAQEwgYwweDELMAkGA1UEBhMCVVMx
# DjAMBgNVBAgMBVRleGFzMRAwDgYDVQQHDAdIb3VzdG9uMREwDwYDVQQKDAhTU0wg
# Q29ycDE0MDIGA1UEAwwrU1NMLmNvbSBDb2RlIFNpZ25pbmcgSW50ZXJtZWRpYXRl
# IENBIEVDQyBSMgIQUR3u8+0Mq1hXs5hyxM0vzzANBglghkgBZQMEAgEFAKCBhDAY
# BgorBgEEAYI3AgEMMQowCKACgAChAoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3
# AgEEMBwGCisGAQQBgjcCAQsxDjAMBgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEi
# BCC00ANAfZc7PtLk8EJDsAZY2cwz6SVhZXEkwdcS36irjDALBgcqhkjOPQIBBQAE
# ZzBlAjEAi9D+Sj3bZLXJr1wOUJNNYMGDTJ2TbO1Slo0WVKrNhsVVj8f34ClY/3Eb
# 5zxwG/o9AjAmYTbDLswSqPNse23FyymYI0w0Xm8cJVvf9UFtNmrldWn3bxyfy+bz
# uZB7rD8qgaShggMjMIIDHwYJKoZIhvcNAQkGMYIDEDCCAwwCAQEwajBVMQswCQYD
# VQQGEwJHQjEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMSwwKgYDVQQDEyNTZWN0
# aWdvIFB1YmxpYyBUaW1lIFN0YW1waW5nIENBIFI0MQIRAOdO8lWwUE/626bf9/yL
# oxUwDQYJYIZIAWUDBAICBQCgeTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwG
# CSqGSIb3DQEJBTEPFw0yNjA4MjMyMTEzMDhaMD8GCSqGSIb3DQEJBDEyBDD+D6hV
# IR4THldchwQYt1yshke+TCaBk4s34b8vVQxK7/HMof8XiEx6lJDCXW9dVXwwDQYJ
# KoZIhvcNAQEBBQAEggIAAJjSZQlMrOOA9EFSyq6SqPLG5nscO0aqogzUpWLoHoyj
# UwaakIn3rrxbgzV4jKvFlCa7HE989r5Sd28fqKpD7YY5xAPy1ss3JATaYHYhXiKC
# 6k04qBBQp5vP1rHCnYeoiu7osNbdm8gOucZeFCFhz3DOlTVELwnz4yuSoTKWksYP
# hhfTyR5t2aAPt72iCaE/E0PBX8nM4WONMUlOrQJ6NWcxl4KMGliXclaML3N78eGW
# VR0KjgL3WuWcGs1QXoT0fxYJfLE74KZvkiXRcjOAs2mEyDbC1YI6YvKL6r5Oc8fQ
# diPHyhyNDHsW94Z/ZQGTfuCf4UIFgJRrqRrYgrULbKh2sItsmr6CWLY6iKejElvi
# /gTeyUKYlmKFhzGv2OqAtAgfpCiW1XLnC12539Zs15Q1ZbUb2g2o2aRFCd69qGWO
# pxE5Q8jnHiWF6toEOVRpyr3nhIxvBPR2jGEfrcX8epMCfEwj1YAO3phNku+X+HAT
# dvowQqruRIVfx0/dY5DkCX72gQ5vqVVjU4NvT5/IokJ8Y4jpWi/VlrPn8kBTPwDD
# RJ7OQibmUZ8cbHfl2Tfs5KVUaTgT9EUQRhNEmzfSFqqtKFRVJSZE+7zDtlK2MuwR
# WMXEg9b2oruMt3K3uhHpbxQC6JfMsusdi0GbyqPTQEn4VKMuvz2LqiNMwh1VRjc=
# SIG # End signature block
