<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    Get-Module AWSCustomizations -All | Remove-Module -Force -ErrorAction SilentlyContinue
    . "$PSScriptRoot/../../../../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$PSScriptRoot/../../../../../../src/CharlandCustomizations/Public/AWS/AWSCustomizations.psm1" -Force

    # Define simple wrapper functions inside the module to avoid AWS cmdlet parameter binding
    # issues (NetworkCredential prompt) when pipeline-binding strings to Get-S3BucketLocation
    InModuleScope AWSCustomizations {
        function script:Get-S3BucketLocation {
            param(
                [Parameter(ValueFromPipeline)]
                [string]$BucketName,
                [string]$Region,
                [string]$ProfileName,
                [string]$AccessKey,
                [string]$SecretKey,
                [string]$SessionToken,
                $Credential,
                [string]$ProfileLocation,
                [string]$EndpointUrl
            )
            process { }
        }
    }
}

Describe 'Get-CHARAWSObjectCount' -Tag 'Unit' {

    Context 'Output contains required properties' {

        BeforeAll {
            Mock Get-EC2Region { @([PSCustomObject]@{ RegionName = 'us-east-1' }) } -ModuleName AWSCustomizations
            Mock Get-CFNStack { @(1, 2, 3) } -ModuleName AWSCustomizations
            Mock Get-EC2Vpc { @(1) } -ModuleName AWSCustomizations
            Mock Get-EC2Instance { @(1, 2) } -ModuleName AWSCustomizations
            Mock Get-S3Bucket { @([PSCustomObject]@{ BucketName = 'bucket1' }) } -ModuleName AWSCustomizations
            Mock Get-S3BucketLocation { [PSCustomObject]@{ Value = 'us-east-1' } } -ModuleName AWSCustomizations
            Mock Get-LMFunctionList { @(1, 2, 3, 4) } -ModuleName AWSCustomizations

            $script:result = Get-CHARAWSObjectCount -Region 'us-east-1'
        }

        It 'Output has Region property (Req 3.9)' {
            $script:result | Should -Not -BeNullOrEmpty
            $script:result.Region | Should -Be 'us-east-1'
        }

        It 'Output has StackCount property (Req 3.9)' {
            $script:result.StackCount | Should -Be 3
        }

        It 'Output has VPCCount property (Req 3.9)' {
            $script:result.VPCCount | Should -Be 1
        }

        It 'Output has EC2Count property (Req 3.9)' {
            $script:result.EC2Count | Should -Be 2
        }

        It 'Output has BucketCount property (Req 3.9)' {
            $script:result.BucketCount | Should -Be 1
        }

        It 'Output has LambdaCount property (Req 3.9)' {
            $script:result.LambdaCount | Should -Be 4
        }

        It 'Output has ScanOk property set to True (Req 3.9)' {
            $script:result.ScanOk | Should -BeTrue
        }
    }

    Context 'AWS API error sets ScanOk to false and counts to empty strings' {

        BeforeAll {
            Mock Get-EC2Region { @([PSCustomObject]@{ RegionName = 'us-east-1' }) } -ModuleName AWSCustomizations
            Mock Get-CFNStack { throw 'AWS API error: Access Denied' } -ModuleName AWSCustomizations
            Mock Get-EC2Vpc { @(1) } -ModuleName AWSCustomizations
            Mock Get-EC2Instance { @(1, 2) } -ModuleName AWSCustomizations
            Mock Get-S3Bucket { @([PSCustomObject]@{ BucketName = 'bucket1' }) } -ModuleName AWSCustomizations
            Mock Get-S3BucketLocation { [PSCustomObject]@{ Value = 'us-east-1' } } -ModuleName AWSCustomizations
            Mock Get-LMFunctionList { @(1, 2, 3, 4) } -ModuleName AWSCustomizations

            $script:errorResult = Get-CHARAWSObjectCount -Region 'us-east-1'
        }

        It 'Sets ScanOk to $false on API error (Req 8.6)' {
            $script:errorResult.ScanOk | Should -BeFalse
        }

        It 'Sets StackCount to empty string on API error (Req 8.6)' {
            $script:errorResult.StackCount | Should -BeExactly ''
        }

        It 'Sets EC2Count to empty string on API error (Req 8.6)' {
            $script:errorResult.EC2Count | Should -BeExactly ''
        }

        It 'Sets BucketCount to empty string on API error (Req 8.6)' {
            $script:errorResult.BucketCount | Should -BeExactly ''
        }

        It 'Sets LambdaCount to empty string on API error (Req 8.6)' {
            $script:errorResult.LambdaCount | Should -BeExactly ''
        }
    }
}
