<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force
}

Describe 'Find-CHAREC2DBSG' -Tag 'Unit' {

    It 'Is an available command' {
        Get-Command Find-CHAREC2DBSG | Should -Not -BeNullOrEmpty
    }

    It 'Has a Region parameter' {
        (Get-Command Find-CHAREC2DBSG).Parameters.Keys | Should -Contain 'Region'
    }

    It 'Has a ProfileName parameter' {
        (Get-Command Find-CHAREC2DBSG).Parameters.Keys | Should -Contain 'ProfileName'
    }
}
