<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force
}

Describe 'Get-CHAREC2SGInUse' -Tag 'Unit' {

    BeforeEach {
        Mock Get-EC2SecurityGroup -ModuleName Audit-AWSAccount {
            @(
                [PSCustomObject]@{ GroupId = 'sg-used'; GroupName = 'in-use-sg'; VpcId = 'vpc-123' }
                [PSCustomObject]@{ GroupId = 'sg-unused'; GroupName = 'orphan-sg'; VpcId = 'vpc-123' }
            )
        }
        Mock Get-EC2Instance -ModuleName Audit-AWSAccount {
            @(
                [PSCustomObject]@{
                    InstanceId = 'i-111'
                    SecurityGroups = @([PSCustomObject]@{ GroupId = 'sg-used' })
                }
            )
        }
        Mock Get-EC2NetworkInterface -ModuleName Audit-AWSAccount {
            @(
                [PSCustomObject]@{
                    NetworkInterfaceId = 'eni-111'
                    Groups = @([PSCustomObject]@{ GroupId = 'sg-used' })
                }
            )
        }
    }

    It 'Returns security group usage data' {
        $results = @(Get-CHAREC2SGInUse)
        $results | Should -Not -BeNullOrEmpty
    }

    It 'Identifies security groups attached to instances or ENIs' {
        $results = @(Get-CHAREC2SGInUse)
        $results.GroupId | Should -Contain 'sg-used'
    }

    It 'Identifies unused security groups' {
        $results = @(Get-CHAREC2SGInUse)
        # Unused SG should be flagged or listed separately
        $results | Where-Object { $_.GroupId -eq 'sg-unused' } | Should -Not -BeNullOrEmpty
    }

    It 'Handles empty instance list gracefully' {
        Mock Get-EC2Instance -ModuleName Audit-AWSAccount { @() }
        Mock Get-EC2NetworkInterface -ModuleName Audit-AWSAccount { @() }

        $results = @(Get-CHAREC2SGInUse)
        # All SGs should be reported as unused
        $results.Count | Should -BeGreaterOrEqual 2
    }
}
