<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Get-Module Audit-AWSAccount -All | Remove-Module -Force -ErrorAction SilentlyContinue
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force

    # Define stub functions for AWS cmdlets not available in test environment
    if (-not (Get-Command Get-ASAutoScalingGroup -ErrorAction SilentlyContinue)) {
        function global:Get-ASAutoScalingGroup { param() @() }
    }
    if (-not (Get-Command Get-ELB2LoadBalancer -ErrorAction SilentlyContinue)) {
        function global:Get-ELB2LoadBalancer { param() @() }
    }
    if (-not (Get-Command Get-ELBLoadBalancer -ErrorAction SilentlyContinue)) {
        function global:Get-ELBLoadBalancer { param() @() }
    }
}

Describe 'Get-CHAREC2Count' -Tag 'Unit' {

    BeforeEach {
        Mock Write-Progress -ModuleName Audit-AWSAccount {}
        Mock Get-EC2Instance -ModuleName Audit-AWSAccount {
            @(
                [PSCustomObject]@{ InstanceId = 'i-111' }
                [PSCustomObject]@{ InstanceId = 'i-222' }
            )
        }
        Mock Get-EC2Volume -ModuleName Audit-AWSAccount {
            @([PSCustomObject]@{ VolumeId = 'vol-111'; Size = 100 })
        }
        Mock Get-EC2Snapshot -ModuleName Audit-AWSAccount {
            @([PSCustomObject]@{ SnapshotId = 'snap-111' })
        }
        Mock Get-ASAutoScalingGroup -ModuleName Audit-AWSAccount {
            @([PSCustomObject]@{ AutoScalingGroupName = 'asg-1' })
        }
        Mock Get-ELB2LoadBalancer -ModuleName Audit-AWSAccount {
            @([PSCustomObject]@{ LoadBalancerName = 'alb-1' })
        }
        Mock Get-ELBLoadBalancer -ModuleName Audit-AWSAccount {
            @([PSCustomObject]@{ LoadBalancerName = 'clb-1' })
        }
    }

    It 'Returns results for each specified region' {
        $results = @(Get-CHAREC2Count -Region 'us-east-1', 'us-west-2')
        $results.Count | Should -Be 2
    }

    It 'Includes Region property in output' {
        $results = @(Get-CHAREC2Count -Region 'us-east-1')
        $results[0].Region | Should -Be 'us-east-1'
    }

    It 'Reports instance count per region' {
        $results = @(Get-CHAREC2Count -Region 'us-east-1')
        $results[0].InstanceCount | Should -Be 2
    }

    It 'Sets ScanOk to true when API calls succeed' {
        $results = @(Get-CHAREC2Count -Region 'us-east-1')
        $results[0].ScanOk | Should -BeTrue
    }

    It 'Handles API errors gracefully and marks ScanOk false' {
        Mock Get-EC2Instance -ModuleName Audit-AWSAccount { throw 'Access denied' }

        $results = @(Get-CHAREC2Count -Region 'us-east-1')
        $results[0].ScanOk | Should -BeFalse
    }
}
