<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force
}

Describe 'Get-CHAREC2VolumeReport' -Tag 'Unit' {

    BeforeEach {
        Mock Get-EC2Volume -ModuleName Audit-AWSAccount {
            @(
                [PSCustomObject]@{
                    VolumeId = 'vol-111'
                    Size = 100
                    VolumeType = 'gp3'
                    State = 'in-use'
                    AvailabilityZone = 'us-east-1a'
                    Encrypted = $true
                    Attachments = @([PSCustomObject]@{ InstanceId = 'i-111'; Device = '/dev/sda1' })
                }
                [PSCustomObject]@{
                    VolumeId = 'vol-222'
                    Size = 50
                    VolumeType = 'gp2'
                    State = 'available'
                    AvailabilityZone = 'us-east-1b'
                    Encrypted = $false
                    Attachments = @()
                }
            )
        }
    }

    It 'Returns volume data with VolumeId' {
        $results = @(Get-CHAREC2VolumeReport)
        $results[0].VolumeId | Should -Be 'vol-111'
    }

    It 'Returns all volumes from the API response' {
        $results = @(Get-CHAREC2VolumeReport)
        $results.Count | Should -Be 2
    }

    It 'Includes volume state in output' {
        $results = @(Get-CHAREC2VolumeReport)
        $results[0].State | Should -Be 'in-use'
        $results[1].State | Should -Be 'available'
    }

    It 'Identifies unattached volumes' {
        $results = @(Get-CHAREC2VolumeReport)
        $unattached = $results | Where-Object { $_.State -eq 'available' }
        $unattached.VolumeId | Should -Contain 'vol-222'
    }

    It 'Handles empty volume list gracefully' {
        Mock Get-EC2Volume -ModuleName Audit-AWSAccount { @() }

        $results = @(Get-CHAREC2VolumeReport)
        $results.Count | Should -Be 0
    }
}
