<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Get-Module Audit-AWSAccount -All | Remove-Module -Force -ErrorAction SilentlyContinue
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force
}

Describe 'Get-CHAREC2VolumeReport' -Tag 'Unit' {

    BeforeEach {
        Mock Get-EC2Volume -ModuleName Audit-AWSAccount {
            @(
                [PSCustomObject]@{
                    VolumeId = 'vol-111'
                    Size = 100
                    Iops = 3000
                    VolumeType = 'gp3'
                    State = 'in-use'
                    Attachments = @([PSCustomObject]@{ VolumeId = 'vol-111'; InstanceId = 'i-111' })
                },
                [PSCustomObject]@{
                    VolumeId = 'vol-222'
                    Size = 50
                    Iops = 100
                    VolumeType = 'gp2'
                    State = 'available'
                    Attachments = @()
                }
            )
        }
    }

    It 'Returns results with VolumeId property' {
        $results = @(Get-CHAREC2VolumeReport -Region 'us-east-1')
        $results.Count | Should -Be 2
        $results[0].VolumeId | Should -Be 'vol-111'
    }

    It 'Reports InstanceId as NoInstance for unattached volumes' {
        $results = @(Get-CHAREC2VolumeReport -Region 'us-east-1')
        $unattached = $results | Where-Object { $_.VolumeId -eq 'vol-222' }
        $unattached.InstanceId | Should -Be 'NoInstance'
    }

    It 'Includes Size and VolumeType for attached volumes' {
        $results = @(Get-CHAREC2VolumeReport -Region 'us-east-1')
        $attached = $results | Where-Object { $_.VolumeId -eq 'vol-111' }
        $attached.Size | Should -Be 100
        $attached.VolumeType | Should -Be 'gp3'
    }

    It 'Handles empty volume list gracefully' {
        Mock Get-EC2Volume -ModuleName Audit-AWSAccount { @() }

        $results = @(Get-CHAREC2VolumeReport -Region 'us-east-1')
        $results.Count | Should -Be 0
    }
}
