<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Get-Module Audit-AWSAccount -All | Remove-Module -Force -ErrorAction SilentlyContinue
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force
}

Describe 'Get-CHAREC2SnapshotReport' -Tag 'Unit' {

    BeforeEach {
        $global:AWShistory = [PSCustomObject]@{
            LastServiceResponse = [PSCustomObject]@{ NextToken = $null }
        }

        Mock Get-EC2Snapshot -ModuleName Audit-AWSAccount {
            @(
                [PSCustomObject]@{
                    SnapshotId = 'snap-111'
                    VolumeId = 'vol-aaa'
                    StartTime = [DateTime]'2024-01-15T10:00:00Z'
                    VolumeSize = 100
                    State = 'completed'
                    Description = 'Daily backup'
                    OwnerId = '123456789012'
                }
                [PSCustomObject]@{
                    SnapshotId = 'snap-222'
                    VolumeId = 'vol-bbb'
                    StartTime = [DateTime]'2024-02-20T14:30:00Z'
                    VolumeSize = 50
                    State = 'completed'
                    Description = 'Manual snapshot'
                    OwnerId = '123456789012'
                }
            )
        }
    }

    It 'Returns snapshot data with SnapshotId' {
        $results = @(Get-CHAREC2SnapshotReport)
        $results[0].SnapshotId | Should -Be 'snap-111'
        $results[1].SnapshotId | Should -Be 'snap-222'
    }

    It 'Includes VolumeId in output' {
        $results = @(Get-CHAREC2SnapshotReport)
        $results[0].VolumeId | Should -Be 'vol-aaa'
    }

    It 'Includes StartTime in output' {
        $results = @(Get-CHAREC2SnapshotReport)
        $results[0].StartTime | Should -Be ([DateTime]'2024-01-15T10:00:00Z')
    }

    It 'Returns all snapshots from the API response' {
        $results = @(Get-CHAREC2SnapshotReport)
        $results.Count | Should -Be 2
    }

    It 'Handles no snapshots returned' {
        Mock Get-EC2Snapshot -ModuleName Audit-AWSAccount { @() }

        $results = @(Get-CHAREC2SnapshotReport)
        $results.Count | Should -Be 0
    }
}
