<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force
}

Describe 'Out-CHARAWSSupportingInfo' -Tag 'Unit' {

    BeforeEach {
        Mock Get-STSCallerIdentity {
            [PSCustomObject]@{ Account = '123456789012'; Arn = 'arn:aws:iam::123456789012:user/admin' }
        }
        Mock Get-DefaultAWSRegion {
            [PSCustomObject]@{ Region = 'us-east-1' }
        }
        Mock Get-SSMParameterList {
            @(
                [PSCustomObject]@{ Name = '/app/config/db-host'; Type = 'String'; LastModifiedDate = (Get-Date) }
                [PSCustomObject]@{ Name = '/app/config/api-key'; Type = 'SecureString'; LastModifiedDate = (Get-Date) }
            )
        }
        Mock Get-SECSecretList {
            @(
                [PSCustomObject]@{ Name = 'prod/database'; ARN = 'arn:aws:secretsmanager:us-east-1:123:secret:prod/database' }
            )
        }
        Mock Get-CFNExport {
            @(
                [PSCustomObject]@{ Name = 'VpcId'; Value = 'vpc-111'; ExportingStackId = 'arn:aws:cfn:us-east-1:123:stack/net/abc' }
            )
        }
    }

    It 'Creates output files in the specified RootPath' {
        Out-CHARAWSSupportingInfo -RootPath $TestDrive
        $files = Get-ChildItem -Path $TestDrive -Recurse -File
        $files.Count | Should -BeGreaterThan 0
    }

    It 'Includes SSM parameter data in output' {
        Out-CHARAWSSupportingInfo -RootPath $TestDrive
        $content = Get-ChildItem -Path $TestDrive -Recurse -File | Get-Content -Raw
        $content | Should -BeLike '*/app/config*'
    }

    It 'Includes CloudFormation exports in output' {
        Out-CHARAWSSupportingInfo -RootPath $TestDrive
        $content = Get-ChildItem -Path $TestDrive -Recurse -File | Get-Content -Raw
        $content | Should -BeLike '*VpcId*'
    }

    It 'Handles empty service responses gracefully' {
        Mock Get-SSMParameterList { @() }
        Mock Get-SECSecretList { @() }
        Mock Get-CFNExport { @() }

        { Out-CHARAWSSupportingInfo -RootPath $TestDrive } | Should -Not -Throw
    }

    It 'Calls Get-STSCallerIdentity for account identification' {
        Out-CHARAWSSupportingInfo -RootPath $TestDrive
        Should -Invoke Get-STSCallerIdentity -Times 1
    }
}
