<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Import-Module "$script:RepoRoot/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1" -Force
}

Describe 'Start-CHAREC2RetryLoop' -Tag 'Unit' {

    It 'Is an available command' {
        Get-Command Start-CHAREC2RetryLoop | Should -Not -BeNullOrEmpty
    }

    It 'Has a ScriptBlock parameter' {
        (Get-Command Start-CHAREC2RetryLoop).Parameters.Keys | Should -Contain 'ScriptBlock'
    }

    It 'Has a MaxRetries parameter' {
        (Get-Command Start-CHAREC2RetryLoop).Parameters.Keys | Should -Contain 'MaxRetries'
    }
}
