<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    $script:ModulePath = Join-Path $script:RepoRoot 'src/CharlandCustomizations/Public/AWS/Lambda/Lambda-Customizations.psm1'
}

Describe 'Lambda-Customizations module' -Tag 'Unit' {

    It 'Is a valid PowerShell module file' {
        $errors = $null
        [System.Management.Automation.Language.Parser]::ParseFile($script:ModulePath, [ref]$null, [ref]$errors)
        $errors | Should -BeNullOrEmpty
    }

    It 'Exports expected functions when imported' {
        Import-Module $script:ModulePath -Force
        $commands = Get-Command -Module Lambda-Customizations
        $commands.Count | Should -BeGreaterThan 0
    }
}
