<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../../../../..')
    . "$script:RepoRoot/src/CharlandCustomizations/Public/Git/Install-CHARGitHook.ps1"
}

Describe 'Install-CHARGitHook' -Tag 'Unit' {

    It 'Is a recognized command after dot-sourcing' {
        Get-Command Install-CHARGitHook | Should -Not -BeNullOrEmpty
    }

    It 'Has a Force switch parameter' {
        $cmd = Get-Command Install-CHARGitHook
        $cmd.Parameters.Keys | Should -Contain 'Force'
    }
}
