<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    # Build-Module.ps1 is a script with CmdletBinding, so we dot-source it inside mocks
    $script:BuildModulePath = "$PSScriptRoot/../../../Scripts/Build-Module.ps1"
}

Describe 'Build-Module' -Tag 'Unit' {

    Context 'Build steps execute copy and directory creation' {

        BeforeAll {
            # Mock filesystem operations to prevent real file system changes
            Mock Copy-Item {}
            Mock New-Item { [PSCustomObject]@{ FullName = $Path } }
            Mock Remove-Item {}
            Mock Test-Path { return $true }
            Mock Test-ModuleManifest {
                [PSCustomObject]@{
                    Version = [version]'0.3.0'
                    Guid    = [guid]::NewGuid()
                }
            }
            Mock Import-PowerShellDataFile {
                @{
                    ModuleVersion = '0.3.0'
                    PrivateData   = @{ PSData = @{ Prerelease = 'beta1' } }
                    RootModule    = 'CharlandCustomizations.psm1'
                    NestedModules = @()
                    FileList      = @()
                }
            }
            Mock Import-Module {}
            Mock Remove-Module {}
            Mock Get-Command { @() }
            Mock Get-Module { $null } -ParameterFilter { $ListAvailable -eq $true }
            Mock Get-ChildItem { @() }
            Mock Write-Host {}
            Mock Write-Output {}
            Mock Write-Warning {}
        }

        It 'Creates build directory with New-Item' {
            # Act — invoke the build script with -SkipSigning to simplify the test path
            & $script:BuildModulePath -SkipSigning -SkipAnalysis

            # Assert — New-Item called to create the versioned build directory
            Should -Invoke New-Item -Times 1 -Exactly -ParameterFilter {
                $ItemType -eq 'Directory' -and $Path -like '*build*'
            }
        }

        It 'Copies module files to build directory with Copy-Item' {
            # Act
            & $script:BuildModulePath -SkipSigning -SkipAnalysis

            # Assert — Copy-Item called to copy source files to build output
            Should -Invoke Copy-Item -Times 1 -Exactly -ParameterFilter {
                $Recurse -eq $true -and $Force -eq $true
            }
        }
    }

    Context 'Manifest version update' {

        BeforeAll {
            Mock Copy-Item {}
            Mock New-Item { [PSCustomObject]@{ FullName = $Path } }
            Mock Remove-Item {}
            Mock Test-Path { return $true }
            Mock Update-ModuleManifest {}
            Mock Test-ModuleManifest {
                [PSCustomObject]@{
                    Version = [version]'0.3.1'
                    Guid    = [guid]::NewGuid()
                }
            }
            Mock Import-PowerShellDataFile {
                @{
                    ModuleVersion = '0.3.0'
                    RootModule    = 'CharlandCustomizations.psm1'
                    NestedModules = @()
                    FileList      = @()
                }
            }
            Mock Import-Module {}
            Mock Remove-Module {}
            Mock Get-Command { @() }
            Mock Get-Module { $null } -ParameterFilter { $ListAvailable -eq $true }
            Mock Get-ChildItem { @() }
            Mock Write-Host {}
            Mock Write-Output {}
            Mock Write-Warning {}
        }

        It 'Calls Update-ModuleManifest when -BumpVersion Patch is specified' {
            # Act
            & $script:BuildModulePath -BumpVersion Patch -SkipSigning -SkipAnalysis

            # Assert — Update-ModuleManifest called with incremented version
            Should -Invoke Update-ModuleManifest -Times 1 -Exactly -ParameterFilter {
                $ModuleVersion -eq [version]'0.3.1'
            }
        }

        It 'Calls Update-ModuleManifest when -Version is explicitly specified' {
            # Act
            & $script:BuildModulePath -Version '1.0.0' -SkipSigning -SkipAnalysis

            # Assert — Update-ModuleManifest called with the explicit version
            Should -Invoke Update-ModuleManifest -Times 1 -Exactly -ParameterFilter {
                $ModuleVersion -eq [version]'1.0.0'
            }
        }

        It 'Calls Update-ModuleManifest with -Prerelease when explicitly specified' {
            # Act
            & $script:BuildModulePath -Prerelease 'rc1' -SkipSigning -SkipAnalysis

            # Assert
            Should -Invoke Update-ModuleManifest -Times 1 -Exactly -ParameterFilter {
                $ModuleVersion -eq [version]'0.3.0' -and
                $Prerelease -eq 'rc1'
            }
        }

        It 'Calls Update-ModuleManifest without prerelease when -ClearPrerelease is specified' {
            # Act
            & $script:BuildModulePath -ClearPrerelease -SkipSigning -SkipAnalysis

            # Assert
            Should -Invoke Update-ModuleManifest -Times 1 -Exactly -ParameterFilter {
                $ModuleVersion -eq [version]'0.3.0' -and
                -not $PSBoundParameters.ContainsKey('Prerelease')
            }
        }
    }

    Context 'Clean build directory' {

        BeforeAll {
            Mock Copy-Item {}
            Mock New-Item { [PSCustomObject]@{ FullName = $Path } }
            Mock Remove-Item {}
            Mock Test-Path { return $true }
            Mock Test-ModuleManifest {
                [PSCustomObject]@{
                    Version = [version]'0.3.0'
                    Guid    = [guid]::NewGuid()
                }
            }
            Mock Import-PowerShellDataFile {
                @{
                    ModuleVersion = '0.3.0'
                    RootModule    = 'CharlandCustomizations.psm1'
                    NestedModules = @()
                    FileList      = @()
                }
            }
            Mock Import-Module {}
            Mock Remove-Module {}
            Mock Get-Command { @() }
            Mock Get-Module { $null } -ParameterFilter { $ListAvailable -eq $true }
            Mock Get-ChildItem { @() }
            Mock Write-Host {}
            Mock Write-Output {}
            Mock Write-Warning {}
        }

        It 'Removes build directory when -Clean is specified' {
            # Act
            & $script:BuildModulePath -Clean -SkipSigning -SkipAnalysis

            # Assert — Remove-Item called for the build directory
            Should -Invoke Remove-Item -ParameterFilter {
                $Recurse -eq $true -and $Force -eq $true -and $Path -like '*build*'
            }
        }
    }

    Context 'Non-PowerShell file removal' {

        BeforeAll {
            Mock Copy-Item {}
            Mock New-Item { [PSCustomObject]@{ FullName = $Path } }
            Mock Remove-Item {}
            Mock Test-Path { return $true }
            Mock Test-ModuleManifest {
                [PSCustomObject]@{
                    Version = [version]'0.3.0'
                    Guid    = [guid]::NewGuid()
                }
            }
            Mock Import-PowerShellDataFile {
                @{
                    ModuleVersion = '0.3.0'
                    RootModule    = 'CharlandCustomizations.psm1'
                    NestedModules = @()
                    FileList      = @()
                }
            }
            Mock Import-Module {}
            Mock Remove-Module {}
            Mock Get-Command { @() }
            Mock Get-Module { $null } -ParameterFilter { $ListAvailable -eq $true }
            # Default: return empty for .gitkeep filter scan and other calls
            Mock Get-ChildItem { @() }
            # For the build-path scan (no -Filter, no -Include): return a non-PowerShell file
            Mock Get-ChildItem {
                @([PSCustomObject]@{
                    Extension = '.gitkeep'
                    FullName  = 'C:\fake\build\CharlandCustomizations\0.3.0\.gitkeep'
                    Name      = '.gitkeep'
                })
            } -ParameterFilter { -not $Filter -and -not $Include }
            Mock Write-Host {}
            Mock Write-Output {}
            Mock Write-Warning {}
        }

        It 'Removes non-PowerShell files from build output' {
            # Act
            & $script:BuildModulePath -SkipSigning -SkipAnalysis

            # Assert — Remove-Item called for the non-PowerShell file
            Should -Invoke Remove-Item -ParameterFilter {
                $Path -like '*.gitkeep' -and $Force -eq $true
            }
        }
    }
}
