<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    $script:ScriptPath = "$PSScriptRoot/../../../Scripts/Publish-CharlandCustomizations.ps1"
}

Describe 'Publish-CharlandCustomizations' -Tag 'Unit' {

    BeforeEach {
        # Mock Resolve-Path to return a string path that Join-Path can consume
        Mock Resolve-Path { '/fake/module/path' }
        Mock Test-Path { return $true }
        Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }
        Mock Get-Command { return @{ Name = 'Publish-Module' } } -ParameterFilter { $Name -eq 'Publish-Module' }
        Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-Secret' }
        Mock Publish-Module {}
        Mock Publish-PSResource {}
        Mock Read-Host { return 'fake-api-key' }
    }

    Context 'Legacy PowerShellGet publishing' {

        It 'Calls Publish-Module with correct Path, Repository, and NuGetApiKey' {
            # Arrange - force legacy path and provide API key
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return @{ Name = 'Publish-Module' } } -ParameterFilter { $Name -eq 'Publish-Module' }

            # Act - invoke the script with explicit parameters
            & $script:ScriptPath -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert (Req 10.1 - Unit tag, Req 1.2 - naming, Req 1.3 - attribution, Req 1.4 - dot-source)
            Should -Invoke Publish-Module -Times 1 -Exactly -ParameterFilter {
                $Path -eq '/fake/module/path' -and
                $Repository -eq 'PSGallery' -and
                $NuGetApiKey -eq 'test-api-key'
            }
        }

        It 'Does not call Publish-PSResource when -UseLegacyPowerShellGet is specified' {
            # Arrange - even if Publish-PSResource is available, legacy flag forces Publish-Module
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }

            # Act
            & $script:ScriptPath -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-PSResource -Times 0 -Exactly
        }
    }

    Context 'PSResourceGet publishing' {

        It 'Calls Publish-PSResource when available and -UseLegacyPowerShellGet is not specified' {
            # Arrange - make Publish-PSResource available
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-PSResourceRepository' }

            # Act
            & $script:ScriptPath -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key'

            # Assert
            Should -Invoke Publish-PSResource -Times 1 -Exactly -ParameterFilter {
                $Repository -eq 'PSGallery' -and
                $ApiKey -eq 'test-api-key'
            }
        }
    }

    Context 'API key resolution' {

        It 'Uses environment variable when -ApiKey is not provided' {
            # Arrange
            $env:PSGALLERY_API_KEY = 'env-api-key'
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }

            # Act
            & $script:ScriptPath -Path '/fake/module/path' -Repository 'PSGallery' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-Module -Times 1 -Exactly -ParameterFilter {
                $NuGetApiKey -eq 'env-api-key'
            }

            # Cleanup
            Remove-Item Env:\PSGALLERY_API_KEY -ErrorAction SilentlyContinue
        }
    }

    Context 'Error handling' {

        It 'Throws when module manifest is not found' {
            # Arrange
            Mock Test-Path { return $false }

            # Act & Assert
            { & $script:ScriptPath -Path '/fake/module/path' -ApiKey 'key' } | Should -Throw '*Module manifest not found*'
        }

        It 'Throws when no API key is provided and Read-Host returns empty' {
            # Arrange
            $env:PSGALLERY_API_KEY = $null
            Remove-Item Env:\PSGALLERY_API_KEY -ErrorAction SilentlyContinue
            Mock Read-Host { return '' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-Secret' }

            # Act & Assert
            { & $script:ScriptPath -Path '/fake/module/path' } | Should -Throw '*No API key was provided*'
        }
    }
}
