<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    $script:ScriptPath = "$PSScriptRoot/../../../Scripts/Publish-CharlandCustomizations.ps1"

    if (-not (Get-Command Test-CCAuthenticodeSignatures -ErrorAction SilentlyContinue)) {
        function global:Test-CCAuthenticodeSignatures { param($Path, $IncludeExtension) }
    }
    if (-not (Get-Command Test-CCAuthenticodeSignature -ErrorAction SilentlyContinue)) {
        function global:Test-CCAuthenticodeSignature { param($Path, $IncludeExtension) }
    }
    # Stub Publish-Module if not available
    if (-not (Get-Command Publish-Module -ErrorAction SilentlyContinue)) {
        function global:Publish-Module { param($Path, $Repository, $NuGetApiKey) }
    }
    # Stub Publish-PSResource if not available
    if (-not (Get-Command Publish-PSResource -ErrorAction SilentlyContinue)) {
        function global:Publish-PSResource { param($Path, $Repository, $ApiKey) }
    }
    # Stub Get-PSResourceRepository if not available
    if (-not (Get-Command Get-PSResourceRepository -ErrorAction SilentlyContinue)) {
        function global:Get-PSResourceRepository { param($Name) }
    }
    # Stub Set-PSResourceRepository if not available
    if (-not (Get-Command Set-PSResourceRepository -ErrorAction SilentlyContinue)) {
        function global:Set-PSResourceRepository { param($Name, [switch]$Trusted) }
    }
    # Stub Get-Secret if not available
    if (-not (Get-Command Get-Secret -ErrorAction SilentlyContinue)) {
        function global:Get-Secret { param($Name, [switch]$AsPlainText) }
    }

    # Wrapper function that executes the script in the current scope so mocks are visible
    function Invoke-PublishScript {
        param(
            [string]$Path,
            [string]$Repository,
            [string]$ApiKey,
            [string]$SecretName,
            [switch]$SkipRepositoryTrust,
            [switch]$UseLegacyPowerShellGet,
            [switch]$WhatIfMode
        )
        $scriptContent = Get-Content $script:ScriptPath -Raw
        $scriptDir = Split-Path $script:ScriptPath -Parent
        $scriptContent = $scriptContent -replace '\$PSScriptRoot', "'$scriptDir'"
        $scriptContent = $scriptContent -replace '\bexit\s+(\d+)', 'return'
        $scriptContent = $scriptContent -replace '\bexit\b', 'return'
        $scriptContent = $scriptContent -replace '(?s)