<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    $script:ScriptPath = "$PSScriptRoot/../../../Scripts/Publish-CharlandCustomizations.ps1"

    if (-not (Get-Command Test-CHARAuthenticodeSignatures -ErrorAction SilentlyContinue)) {
        function global:Test-CHARAuthenticodeSignatures { param($Path, $IncludeExtension) }
    }
    if (-not (Get-Command Test-CHARAuthenticodeSignature -ErrorAction SilentlyContinue)) {
        function global:Test-CHARAuthenticodeSignature { param($Path, $IncludeExtension) }
    }
    # Stub Publish-Module if not available
    if (-not (Get-Command Publish-Module -ErrorAction SilentlyContinue)) {
        function global:Publish-Module { param($Path, $Repository, $NuGetApiKey) }
    }
    # Stub Publish-PSResource if not available
    if (-not (Get-Command Publish-PSResource -ErrorAction SilentlyContinue)) {
        function global:Publish-PSResource { param($Path, $Repository, $ApiKey) }
    }
    # Stub Get-PSResourceRepository if not available
    if (-not (Get-Command Get-PSResourceRepository -ErrorAction SilentlyContinue)) {
        function global:Get-PSResourceRepository { param($Name) }
    }
    # Stub Set-PSResourceRepository if not available
    if (-not (Get-Command Set-PSResourceRepository -ErrorAction SilentlyContinue)) {
        function global:Set-PSResourceRepository { param($Name, [switch]$Trusted) }
    }
    # Stub Get-Secret if not available
    if (-not (Get-Command Get-Secret -ErrorAction SilentlyContinue)) {
        function global:Get-Secret { param($Name, [switch]$AsPlainText) }
    }

    # Wrapper function that executes the script in the current scope so mocks are visible
    function Invoke-PublishScript {
        param(
            [string]$Path,
            [string]$Repository,
            [string]$ApiKey,
            [string]$SecretName,
            [switch]$SkipRepositoryTrust,
            [switch]$UseLegacyPowerShellGet,
            [switch]$WhatIfMode
        )
        $scriptContent = Get-Content $script:ScriptPath -Raw
        $scriptDir = Split-Path $script:ScriptPath -Parent
        $scriptContent = $scriptContent -replace '\$PSScriptRoot', "'$scriptDir'"
        $scriptContent = $scriptContent -replace '\bexit\s+(\d+)', 'return'
        $scriptContent = $scriptContent -replace '\bexit\b', 'return'
        $scriptContent = $scriptContent -replace '(?s)# SIG # Begin signature block.*# SIG # End signature block', ''

        $sb = [scriptblock]::Create($scriptContent)
        $invokeParams = @{}
        if ($Path) { $invokeParams['Path'] = $Path }
        if ($Repository) { $invokeParams['Repository'] = $Repository }
        if ($ApiKey) { $invokeParams['ApiKey'] = $ApiKey }
        if ($SecretName) { $invokeParams['SecretName'] = $SecretName }
        if ($SkipRepositoryTrust) { $invokeParams['SkipRepositoryTrust'] = $true }
        if ($UseLegacyPowerShellGet) { $invokeParams['UseLegacyPowerShellGet'] = $true }
        if ($WhatIfMode) { $invokeParams['WhatIf'] = $true }
        . $sb @invokeParams
    }
}

Describe 'Publish-CharlandCustomizations' -Tag 'Unit' {

    BeforeEach {
        $script:IsWindows = $true

        # Mock Resolve-Path to return a string path that Join-Path can consume
        Mock Resolve-Path { '/fake/module/path' }
        Mock Test-Path { return $true }
        Mock Test-ModuleManifest {
            [PSCustomObject]@{
                Version = [version]'0.2.0'
                PrivateData = @{
                    PSData = @{
                        Prerelease = 'beta1'
                    }
                }
            }
        }
        Mock git {
            param([Parameter(ValueFromRemainingArguments = $true)][object[]]$RemainingArgs)

            $gitCommand = $RemainingArgs -join ' '
            if ($gitCommand -match 'rev-parse --show-toplevel') {
                return 'C:/fake/repo'
            }
            if ($gitCommand -match 'branch --show-current') {
                return 'main'
            }
            if ($gitCommand -match 'tag --points-at HEAD') {
                return '0.2.0-beta1'
            }

            return $null
        }
        Mock Get-ChildItem {
            @(
                [PSCustomObject]@{ FullName = '/fake/module/path/CharlandCustomizations.psd1'; Extension = '.psd1' },
                [PSCustomObject]@{ FullName = '/fake/module/path/CharlandCustomizations.psm1'; Extension = '.psm1' },
                [PSCustomObject]@{ FullName = '/fake/module/path/Public/Example.ps1'; Extension = '.ps1' }
            )
        }
        Mock Get-Command { return @{ Name = 'git' } } -ParameterFilter { $Name -eq 'git' }
        Mock Get-Command { return @{ Name = 'Test-CHARAuthenticodeSignatures' } } -ParameterFilter { $Name -eq 'Test-CHARAuthenticodeSignatures' }
        Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Test-CHARAuthenticodeSignature' }
        Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }
        Mock Get-Command { return @{ Name = 'Publish-Module' } } -ParameterFilter { $Name -eq 'Publish-Module' }
        Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-Secret' }
        Mock Test-CHARAuthenticodeSignatures { @() }
        Mock Test-CHARAuthenticodeSignature { @() }
        Mock Publish-Module {}
        Mock Publish-PSResource {}
        Mock Read-Host { return 'fake-api-key' }
    }

    Context 'PSGallery release gating' {

        It 'Throws when publishing to PSGallery from a non-main branch' {
            # Arrange
            Mock git {
                param([Parameter(ValueFromRemainingArguments = $true)][object[]]$RemainingArgs)

                $gitCommand = $RemainingArgs -join ' '
                if ($gitCommand -match 'rev-parse --show-toplevel') {
                    return 'C:/fake/repo'
                }
                if ($gitCommand -match 'branch --show-current') {
                    return 'feature/test'
                }
                if ($gitCommand -match 'tag --points-at HEAD') {
                    return '0.2.0-beta1'
                }

                return $null
            }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet } |
                Should -Throw "*only allowed from branch 'main'*"
        }

        It 'Throws when required release tag is not on HEAD' {
            # Arrange - tag on HEAD is completely different from expected
            Mock git {
                param([Parameter(ValueFromRemainingArguments = $true)][object[]]$RemainingArgs)

                $gitCommand = $RemainingArgs -join ' '
                if ($gitCommand -match 'rev-parse --show-toplevel') {
                    return 'C:/fake/repo'
                }
                if ($gitCommand -match 'branch --show-current') {
                    return 'main'
                }
                if ($gitCommand -match 'tag --points-at HEAD') {
                    return 'v0.1.0'
                }

                return $null
            }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet } |
                Should -Throw "*requires immutable release tag*"
        }

        It 'Accepts v-prefixed release tag on HEAD' {
            # Arrange - tag on HEAD uses v prefix matching workflow convention
            Mock git {
                param([Parameter(ValueFromRemainingArguments = $true)][object[]]$RemainingArgs)

                $gitCommand = $RemainingArgs -join ' '
                if ($gitCommand -match 'rev-parse --show-toplevel') {
                    return 'C:/fake/repo'
                }
                if ($gitCommand -match 'branch --show-current') {
                    return 'main'
                }
                if ($gitCommand -match 'tag --points-at HEAD') {
                    return 'v0.2.0-beta1'
                }

                return $null
            }

            # Act - should not throw
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-Module -Times 1 -Exactly
        }

        It 'Accepts bare release tag on HEAD (no v prefix)' {
            # Arrange - tag without v prefix also works
            Mock git {
                param([Parameter(ValueFromRemainingArguments = $true)][object[]]$RemainingArgs)

                $gitCommand = $RemainingArgs -join ' '
                if ($gitCommand -match 'rev-parse --show-toplevel') {
                    return 'C:/fake/repo'
                }
                if ($gitCommand -match 'branch --show-current') {
                    return 'main'
                }
                if ($gitCommand -match 'tag --points-at HEAD') {
                    return '0.2.0-beta1'
                }

                return $null
            }

            # Act - should not throw
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-Module -Times 1 -Exactly
        }

        It 'Does not enforce git branch/tag gate for non-PSGallery repositories' {
            # Arrange
            Mock git {
                param([Parameter(ValueFromRemainingArguments = $true)][object[]]$RemainingArgs)
                return $null
            }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'InternalRepo' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-Module -Times 1 -Exactly
        }
    }

    Context 'Signature validation' {

        It 'Validates signatures before publishing by default' {
            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Test-CHARAuthenticodeSignatures -Times 1 -Exactly -ParameterFilter {
                $Path -eq '/fake/module/path'
            }
        }

        It 'Throws when not running on Windows' {
            # Arrange
            $script:IsWindows = $false

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet } |
                Should -Throw '*only supported on Windows systems*'
        }

        It 'Throws when a module file signature is invalid' {
            # Arrange
            Mock Test-CHARAuthenticodeSignatures {
                [PSCustomObject]@{
                    Path = '/fake/module/path/Public/Example.ps1'
                    Status = 'HashMismatch'
                }
            }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet } |
                Should -Throw '*valid Authenticode signatures*'
        }

        It 'Throws when a non-PowerShell file exists in the module directory' {
            # Arrange
            Mock Get-ChildItem {
                @(
                    [PSCustomObject]@{ FullName = '/fake/module/path/CharlandCustomizations.psd1'; Extension = '.psd1' },
                    [PSCustomObject]@{ FullName = '/fake/module/path/CharlandCustomizations.psm1'; Extension = '.psm1' },
                    [PSCustomObject]@{ FullName = '/fake/module/path/.gitignore'; Extension = '.gitignore' }
                )
            }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet } |
                Should -Throw '*disallowed file*'
        }

        It 'Uses singular signature command as fallback when plural command is unavailable' {
            # Arrange
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Test-CHARAuthenticodeSignatures' }
            Mock Get-Command { return @{ Name = 'Test-CHARAuthenticodeSignature' } } -ParameterFilter { $Name -eq 'Test-CHARAuthenticodeSignature' }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Test-CHARAuthenticodeSignatures -Times 0 -Exactly
            Should -Invoke Test-CHARAuthenticodeSignature -Times 1 -Exactly -ParameterFilter {
                $Path -eq '/fake/module/path'
            }
        }
    }

    Context 'Legacy PowerShellGet publishing' {

        It 'Calls Publish-Module with correct Path, Repository, and NuGetApiKey' {
            # Arrange - force legacy path and provide API key
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return @{ Name = 'Publish-Module' } } -ParameterFilter { $Name -eq 'Publish-Module' }

            # Act - invoke the script with explicit parameters
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert (Req 10.1 - Unit tag, Req 1.2 - naming, Req 1.3 - attribution, Req 1.4 - dot-source)
            Should -Invoke Publish-Module -Times 1 -Exactly -ParameterFilter {
                $Path -eq '/fake/module/path' -and
                $Repository -eq 'PSGallery' -and
                $NuGetApiKey -eq 'test-api-key'
            }
        }

        It 'Does not call Publish-PSResource when -UseLegacyPowerShellGet is specified' {
            # Arrange - even if Publish-PSResource is available, legacy flag forces Publish-Module
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-PSResource -Times 0 -Exactly
        }
    }

    Context 'PSResourceGet publishing' {

        It 'Calls Publish-PSResource when available and -UseLegacyPowerShellGet is not specified' {
            # Arrange - make Publish-PSResource available
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-PSResourceRepository' }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key'

            # Assert
            Should -Invoke Publish-PSResource -Times 1 -Exactly -ParameterFilter {
                $Repository -eq 'PSGallery' -and
                $ApiKey -eq 'test-api-key'
            }
        }

        It 'Skips publishing when -WhatIf is specified' {
            # Arrange - make Publish-PSResource available so ShouldProcess can short-circuit it
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-PSResourceRepository' }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -WhatIfMode

            # Assert
            Should -Invoke Test-CHARAuthenticodeSignatures -Times 1 -Exactly
            Should -Invoke Publish-PSResource -Times 0 -Exactly
            Should -Invoke Publish-Module -Times 0 -Exactly
        }
    }

    Context 'API key resolution' {

        It 'Uses environment variable when -ApiKey is not provided' {
            # Arrange
            $env:PSGALLERY_API_KEY = 'env-api-key'
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-Module -Times 1 -Exactly -ParameterFilter {
                $NuGetApiKey -eq 'env-api-key'
            }

            # Cleanup
            Remove-Item Env:\PSGALLERY_API_KEY -ErrorAction SilentlyContinue
        }
    }

    Context 'Error handling' {

        It 'Throws when module manifest is not found' {
            # Arrange
            Mock Test-Path { return $false }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -ApiKey 'key' } | Should -Throw '*Module manifest not found*'
        }

        It 'Throws when no API key is provided and Read-Host returns empty' {
            # Arrange
            $env:PSGALLERY_API_KEY = $null
            Remove-Item Env:\PSGALLERY_API_KEY -ErrorAction SilentlyContinue
            Mock Read-Host { return '' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-Secret' }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' } | Should -Throw '*No API key was provided*'
        }

        It 'Throws when neither Publish-PSResource nor Publish-Module is available' {
            # Arrange
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-Module' }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-key' } |
                Should -Throw '*Neither Publish-PSResource nor Publish-Module*'
        }

        It 'Throws when git is not available and publishing to PSGallery' {
            # Arrange
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'git' }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-key' } |
                Should -Throw '*requires git*'
        }

        It 'Throws when not inside a git repository' {
            # Arrange
            Mock git {
                param([Parameter(ValueFromRemainingArguments = $true)][object[]]$RemainingArgs)
                $gitCommand = $RemainingArgs -join ' '
                if ($gitCommand -match 'rev-parse --show-toplevel') {
                    return $null
                }
                return $null
            }

            # Act & Assert
            { Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-key' } |
                Should -Throw '*inside a git repository*'
        }
    }

    Context 'Success output' {

        It 'Outputs success message when publishing via Publish-Module' {
            # Arrange
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return @{ Name = 'Publish-Module' } } -ParameterFilter { $Name -eq 'Publish-Module' }

            # Act
            $output = Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            $output | Should -BeLike '*Successfully published*PowerShellGet*'
        }

        It 'Outputs success message when publishing via Publish-PSResource' {
            # Arrange
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Get-PSResourceRepository' }

            # Act
            $output = Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key'

            # Assert
            $output | Should -BeLike '*Successfully published*PSResourceGet*'
        }

        It 'Outputs success message containing the repository name' {
            # Arrange
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return @{ Name = 'Publish-Module' } } -ParameterFilter { $Name -eq 'Publish-Module' }

            # Act
            $output = Invoke-PublishScript -Path '/fake/module/path' -Repository 'InternalRepo' -ApiKey 'test-api-key' -UseLegacyPowerShellGet

            # Assert
            $output | Should -BeLike "*InternalRepo*"
        }
    }

    Context 'Repository trust handling' {

        It 'Sets repository as trusted when not already trusted and Publish-PSResource path is used' {
            # Arrange
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return @{ Name = 'Get-PSResourceRepository' } } -ParameterFilter { $Name -eq 'Get-PSResourceRepository' }
            Mock Get-PSResourceRepository { [PSCustomObject]@{ Name = 'PSGallery'; Trusted = $false } }
            Mock Set-PSResourceRepository {}

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key'

            # Assert
            Should -Invoke Set-PSResourceRepository -Times 1 -Exactly
        }

        It 'Skips repository trust when -SkipRepositoryTrust is specified' {
            # Arrange
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return @{ Name = 'Get-PSResourceRepository' } } -ParameterFilter { $Name -eq 'Get-PSResourceRepository' }
            Mock Get-PSResourceRepository { [PSCustomObject]@{ Name = 'PSGallery'; Trusted = $false } }
            Mock Set-PSResourceRepository {}

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key' -SkipRepositoryTrust

            # Assert
            Should -Invoke Set-PSResourceRepository -Times 0 -Exactly
        }

        It 'Does not set repository trust when already trusted' {
            # Arrange
            Mock Get-Command { return @{ Name = 'Publish-PSResource' } } -ParameterFilter { $Name -eq 'Publish-PSResource' }
            Mock Get-Command { return @{ Name = 'Get-PSResourceRepository' } } -ParameterFilter { $Name -eq 'Get-PSResourceRepository' }
            Mock Get-PSResourceRepository { [PSCustomObject]@{ Name = 'PSGallery'; Trusted = $true } }
            Mock Set-PSResourceRepository {}

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -ApiKey 'test-api-key'

            # Assert
            Should -Invoke Set-PSResourceRepository -Times 0 -Exactly
        }
    }

    Context 'SecretManagement integration' {

        It 'Reads API key from SecretManagement when available and no key provided' {
            # Arrange
            $env:PSGALLERY_API_KEY = $null
            Remove-Item Env:\PSGALLERY_API_KEY -ErrorAction SilentlyContinue
            Mock Get-Command { return @{ Name = 'Get-Secret' } } -ParameterFilter { $Name -eq 'Get-Secret' }
            Mock Get-Secret { return 'secret-api-key' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-Module -Times 1 -Exactly -ParameterFilter {
                $NuGetApiKey -eq 'secret-api-key'
            }
        }

        It 'Falls through to Read-Host when SecretManagement throws' {
            # Arrange
            $env:PSGALLERY_API_KEY = $null
            Remove-Item Env:\PSGALLERY_API_KEY -ErrorAction SilentlyContinue
            Mock Get-Command { return @{ Name = 'Get-Secret' } } -ParameterFilter { $Name -eq 'Get-Secret' }
            Mock Get-Secret { throw 'Secret not found' }
            Mock Read-Host { return 'manual-key' }
            Mock Get-Command { return $null } -ParameterFilter { $Name -eq 'Publish-PSResource' }

            # Act
            Invoke-PublishScript -Path '/fake/module/path' -Repository 'PSGallery' -UseLegacyPowerShellGet

            # Assert
            Should -Invoke Publish-Module -Times 1 -Exactly -ParameterFilter {
                $NuGetApiKey -eq 'manual-key'
            }
        }
    }
}
