<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    $script:SUTPath = "$PSScriptRoot/../../../Scripts/Test-SignatureCompliance.ps1"
}

Describe 'Test-SignatureCompliance' -Tag 'Unit' {

    BeforeEach {
        Mock Test-Path { $true }
        Mock Resolve-Path {
            [PSCustomObject]@{ Path = '/fake/repo/Scripts' }
        }
        Mock Get-ChildItem {
            @(
                [PSCustomObject]@{ FullName = '/fake/repo/Scripts/a.ps1'; Extension = '.ps1' },
                [PSCustomObject]@{ FullName = '/fake/repo/Scripts/b.psm1'; Extension = '.psm1' },
                [PSCustomObject]@{ FullName = '/fake/repo/Scripts/c.psd1'; Extension = '.psd1' }
            )
        }
        Mock Get-AuthenticodeSignature { [PSCustomObject]@{ Status = 'Valid' } }
        Mock Write-Host {}
        Mock Write-Error {}
    }

    Context 'Validation success path' {

        It 'Validates all default extension files recursively' {
            # Act
            & $script:SUTPath

            # Assert
            Should -Invoke Get-ChildItem -Times 2 -Exactly -ParameterFilter {
                $Recurse -eq $true -and $File -eq $true
            }
            Should -Invoke Get-AuthenticodeSignature -Times 6 -Exactly
        }

        It 'Honors IncludeExtension filter when provided' {
            # Arrange
            Mock Get-ChildItem {
                @(
                    [PSCustomObject]@{ FullName = '/fake/repo/Scripts/a.ps1'; Extension = '.ps1' },
                    [PSCustomObject]@{ FullName = '/fake/repo/Scripts/b.psm1'; Extension = '.psm1' }
                )
            }

            # Act
            & $script:SUTPath -IncludeExtension '.ps1'

            # Assert
            Should -Invoke Get-AuthenticodeSignature -Times 2 -Exactly
        }
    }

    Context 'Validation failures' {

        It 'Throws when a configured path does not exist' {
            # Arrange
            Mock Test-Path { $false }

            # Act & Assert
            { & $script:SUTPath } | Should -Throw '*Validation path does not exist*'
        }

        It 'Throws when no matching files are found' {
            # Arrange
            Mock Get-ChildItem { @() }

            # Act & Assert
            { & $script:SUTPath } | Should -Throw '*No files were found to validate*'
        }

        It 'Throws when any file has an invalid signature' {
            # Arrange
            Mock Get-AuthenticodeSignature { [PSCustomObject]@{ Status = 'NotSigned' } }

            # Act & Assert
            { & $script:SUTPath } | Should -Throw '*invalid Authenticode signatures*'
        }
    }
}
