<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    $script:SUTPath = "$PSScriptRoot/../../../src/CharlandCustomizations/Public/Test-CHARAuthenticodeSignature.ps1"

    # Stub Get-AuthenticodeSignature on Linux/macOS where it doesn't exist
    if (-not (Get-Command Get-AuthenticodeSignature -ErrorAction SilentlyContinue)) {
        function global:Get-AuthenticodeSignature {
            param($FilePath)
        }
    }

    . $script:SUTPath
    # The SUT uses $script:CHARIsWindows internally — set it to $true for testing
    $script:CHARIsWindows = $true

    # Wrapper function that executes the script content in the current scope
    # so Pester mocks are visible, and converts 'exit'/'throw' to returns.
    function Invoke-TestCHARAuthenticodeSignature {
        [CmdletBinding()]
        param(
            [string[]]$Path,
            [string[]]$IncludeExtension
        )
        $invokeParams = @{}
        if ($Path) { $invokeParams['Path'] = $Path }
        if ($IncludeExtension) { $invokeParams['IncludeExtension'] = $IncludeExtension }
        Test-CHARAuthenticodeSignature @invokeParams
    }
}

Describe 'Test-CHARAuthenticodeSignature' -Tag 'Unit' {

    BeforeEach {
        Mock Test-Path { $true }
        Mock Resolve-Path {
            [PSCustomObject]@{ Path = '/fake/repo/Scripts' }
        }
        Mock Get-ChildItem {
            @(
                [PSCustomObject]@{ FullName = '/fake/repo/Scripts/a.ps1'; Extension = '.ps1' },
                [PSCustomObject]@{ FullName = '/fake/repo/Scripts/b.psm1'; Extension = '.psm1' },
                [PSCustomObject]@{ FullName = '/fake/repo/Scripts/c.psd1'; Extension = '.psd1' }
            )
        }
        Mock Get-AuthenticodeSignature { [PSCustomObject]@{ Status = 'Valid'; TimeStamperCertificate = [PSCustomObject]@{ Subject = 'CN=Fake' } } }
        Mock Write-Host {}
        Mock Write-Error {}
    }

    Context 'Validation success path' {

        It 'Validates all default extension files recursively' {
            # Act
            Invoke-TestCHARAuthenticodeSignature

            # Assert
            Should -Invoke Get-ChildItem -Times 2 -Exactly -ParameterFilter {
                $Recurse -eq $true -and $File -eq $true
            }
            Should -Invoke Get-AuthenticodeSignature -Times 6 -Exactly
        }

        It 'Honors IncludeExtension filter when provided' {
            # Arrange
            Mock Get-ChildItem {
                @(
                    [PSCustomObject]@{ FullName = '/fake/repo/Scripts/a.ps1'; Extension = '.ps1' },
                    [PSCustomObject]@{ FullName = '/fake/repo/Scripts/b.psm1'; Extension = '.psm1' }
                )
            }

            # Act
            Invoke-TestCHARAuthenticodeSignature -IncludeExtension '.ps1'

            # Assert
            Should -Invoke Get-AuthenticodeSignature -Times 2 -Exactly
        }
    }

    Context 'Validation failures' {
        It 'Throws when not running on Windows' {
            $script:CHARIsWindows = $false
            try {
                { Invoke-TestCHARAuthenticodeSignature } | Should -Throw '*only supported on Windows systems*'
            }
            finally {
                $script:CHARIsWindows = $true
            }
        }

        It 'Throws when a configured path does not exist' {
            # Arrange
            Mock Test-Path { $false }

            # Act & Assert
            { Invoke-TestCHARAuthenticodeSignature } | Should -Throw '*Validation path does not exist*'
        }

        It 'Throws when no matching files are found' {
            # Arrange
            Mock Get-ChildItem { @() }

            # Act & Assert
            { Invoke-TestCHARAuthenticodeSignature } | Should -Throw '*No files were found to validate*'
        }

        It 'Emits invalid signature objects when any file has an invalid signature' {
            # Arrange
            Mock Get-AuthenticodeSignature { [PSCustomObject]@{ Status = 'NotSigned' } }

            # Act
            $result = Invoke-TestCHARAuthenticodeSignature

            # Assert - should output objects with Status and Path
            $result | Should -Not -BeNullOrEmpty
            $result.Status | Should -Contain 'NotSigned'
        }
    }
}
