<#
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
BeforeAll {
    $script:RepoRoot = Resolve-Path (Join-Path $PSScriptRoot '../..')
    $script:ModulePath = Join-Path $script:RepoRoot 'src/CharlandCustomizations/CharlandCustomizations.psm1'
}

Describe 'CharlandCustomizations.psm1 root module' -Tag 'Unit' {

    It 'Is a valid PowerShell script file' {
        $errors = $null
        [System.Management.Automation.Language.Parser]::ParseFile($script:ModulePath, [ref]$null, [ref]$errors)
        $errors | Should -BeNullOrEmpty
    }

    It 'Dot-sources Public and Private function files' {
        $content = Get-Content -Path $script:ModulePath -Raw
        $content | Should -Match 'Public'
        $content | Should -Match 'Private'
    }
}
