<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    # Stub AWS cmdlets not installed locally so Pester can mock them
    if (-not (Get-Command Find-CTEvent -ErrorAction SilentlyContinue)) {
        function global:Find-CTEvent { }
    }
    if (-not (Get-Command Get-CFGResourceConfigHistory -ErrorAction SilentlyContinue)) {
        function global:Get-CFGResourceConfigHistory { }
    }

    Get-Module Config-Operations -All | Remove-Module -Force -ErrorAction SilentlyContinue
    $modulePath = Resolve-Path "$PSScriptRoot/../../../../../../src/CharlandCustomizations/Public/AWS/Config/Config-Operations.psm1"
    Import-Module $modulePath -Force
}

Describe 'Get-CHARConfigResourceDeleteDate' -Tag 'Unit' {

    BeforeAll {
        Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
        Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'

        Mock Get-CFGResourceConfigHistory {
            @(
                [PSCustomObject]@{
                    ConfigurationItemStatus      = 'ResourceDeleted'
                    ConfigurationItemCaptureTime = [datetime]'2024-03-15 10:30:00'
                    ResourceId                   = 'i-0123456789abcdef0'
                    ResourceType                 = 'AWS::EC2::Instance'
                },
                [PSCustomObject]@{
                    ConfigurationItemStatus      = 'OK'
                    ConfigurationItemCaptureTime = [datetime]'2024-03-14 09:00:00'
                    ResourceId                   = 'i-0123456789abcdef0'
                    ResourceType                 = 'AWS::EC2::Instance'
                }
            )
        } -ModuleName 'Config-Operations'

        Mock Find-CTEvent {
            @(
                [PSCustomObject]@{
                    EventName   = 'TerminateInstances'
                    EventSource = 'ec2.amazonaws.com'
                    Username    = 'arn:aws:iam::123456789012:user/admin'
                }
            )
        } -ModuleName 'Config-Operations'
    }

    Context 'Happy path - deletion record and CloudTrail event found' {

        It 'Returns result with DeletionDate when ResourceDeleted item found' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance'

            $result | Should -Not -BeNullOrEmpty
            $result.DeletionDate | Should -Be ([datetime]'2024-03-15 10:30:00')
        }

        It 'Returns correct ResourceId and ResourceType' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance'

            $result.ResourceId | Should -Be 'i-0123456789abcdef0'
            $result.ResourceType | Should -Be 'AWS::EC2::Instance'
        }

        It 'Returns CloudTrail correlation fields' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance'

            $result.PrincipalName | Should -Be 'arn:aws:iam::123456789012:user/admin'
            $result.EventName | Should -Be 'TerminateInstances'
            $result.EventSource | Should -Be 'ec2.amazonaws.com'
        }

        It 'Output has exactly 6 properties in correct order' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance'

            $propertyNames = $result.PSObject.Properties.Name
            $propertyNames.Count | Should -Be 6
            $propertyNames[0] | Should -Be 'ResourceId'
            $propertyNames[1] | Should -Be 'ResourceType'
            $propertyNames[2] | Should -Be 'DeletionDate'
            $propertyNames[3] | Should -Be 'PrincipalName'
            $propertyNames[4] | Should -Be 'EventName'
            $propertyNames[5] | Should -Be 'EventSource'
        }
    }

    Context 'No deletion record in history' {

        BeforeAll {
            Mock Get-CFGResourceConfigHistory {
                @(
                    [PSCustomObject]@{
                        ConfigurationItemStatus      = 'OK'
                        ConfigurationItemCaptureTime = [datetime]'2024-03-14 09:00:00'
                        ResourceId                   = 'i-0123456789abcdef0'
                        ResourceType                 = 'AWS::EC2::Instance'
                    },
                    [PSCustomObject]@{
                        ConfigurationItemStatus      = 'OK'
                        ConfigurationItemCaptureTime = [datetime]'2024-03-13 08:00:00'
                        ResourceId                   = 'i-0123456789abcdef0'
                        ResourceType                 = 'AWS::EC2::Instance'
                    }
                )
            } -ModuleName 'Config-Operations'
        }

        It 'Returns $null when no ResourceDeleted item exists' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance' -WarningVariable warn 3>&1

            # Filter out warnings from the result stream
            $output = $result | Where-Object { $_ -isnot [System.Management.Automation.WarningRecord] }
            $output | Should -BeNullOrEmpty
        }

        It 'Emits a warning containing the resource ID' {
            $null = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance' -WarningVariable warn 3>$null

            $warn | Should -Not -BeNullOrEmpty
            $warn[0].Message | Should -Match 'i-0123456789abcdef0'
        }
    }

    Context 'ResourceNotDiscoveredException' {

        BeforeAll {
            if (-not ('ResourceNotDiscoveredException' -as [type])) {
                Add-Type -TypeDefinition 'public class ResourceNotDiscoveredException : System.Exception { public ResourceNotDiscoveredException(string message) : base(message) { } }'
            }
            Mock Get-CFGResourceConfigHistory {
                throw [ResourceNotDiscoveredException]::new('Resource not found in Config')
            } -ModuleName 'Config-Operations'
        }

        It 'Returns $null for undiscovered resource' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-notfound' -ResourceType 'AWS::EC2::Instance' 3>$null

            $result | Should -BeNullOrEmpty
        }

        It 'Emits a warning containing the resource ID' {
            $null = Get-CHARConfigResourceDeleteDate -ResourceId 'i-notfound' -ResourceType 'AWS::EC2::Instance' -WarningVariable warn 3>$null

            $warn | Should -Not -BeNullOrEmpty
            $warn[0].Message | Should -Match 'i-notfound'
        }
    }

    Context 'CloudTrail lookup failure (non-fatal)' {

        BeforeAll {
            Mock Get-CFGResourceConfigHistory {
                @(
                    [PSCustomObject]@{
                        ConfigurationItemStatus      = 'ResourceDeleted'
                        ConfigurationItemCaptureTime = [datetime]'2024-03-15 10:30:00'
                        ResourceId                   = 'i-0123456789abcdef0'
                        ResourceType                 = 'AWS::EC2::Instance'
                    }
                )
            } -ModuleName 'Config-Operations'

            Mock Find-CTEvent {
                throw [System.Exception]::new('CloudTrail service unavailable')
            } -ModuleName 'Config-Operations'
        }

        It 'Returns result with null CT fields when CloudTrail fails' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance'

            $result | Should -Not -BeNullOrEmpty
            $result.DeletionDate | Should -Be ([datetime]'2024-03-15 10:30:00')
            $result.PrincipalName | Should -BeNullOrEmpty
            $result.EventName | Should -BeNullOrEmpty
            $result.EventSource | Should -BeNullOrEmpty
        }

        It 'Still returns valid ResourceId and ResourceType' {
            $result = Get-CHARConfigResourceDeleteDate -ResourceId 'i-0123456789abcdef0' -ResourceType 'AWS::EC2::Instance'

            $result.ResourceId | Should -Be 'i-0123456789abcdef0'
            $result.ResourceType | Should -Be 'AWS::EC2::Instance'
        }
    }

    Context 'Pipeline input' {

        BeforeAll {
            Mock Get-CFGResourceConfigHistory {
                @(
                    [PSCustomObject]@{
                        ConfigurationItemStatus      = 'ResourceDeleted'
                        ConfigurationItemCaptureTime = [datetime]'2024-06-01 14:00:00'
                        ResourceId                   = 'i-pipeline01'
                        ResourceType                 = 'AWS::EC2::Instance'
                    }
                )
            } -ModuleName 'Config-Operations'

            Mock Find-CTEvent {
                @(
                    [PSCustomObject]@{
                        EventName   = 'TerminateInstances'
                        EventSource = 'ec2.amazonaws.com'
                        Username    = 'arn:aws:iam::123456789012:role/automation'
                    }
                )
            } -ModuleName 'Config-Operations'
        }

        It 'Accepts ResourceId from pipeline' {
            $result = 'i-pipeline01' | Get-CHARConfigResourceDeleteDate -ResourceType 'AWS::EC2::Instance'

            $result | Should -Not -BeNullOrEmpty
            $result.ResourceId | Should -Be 'i-pipeline01'
            $result.DeletionDate | Should -Be ([datetime]'2024-06-01 14:00:00')
        }
    }
}
