<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    # Define stub functions in global scope so Pester can mock them within module scope
    function global:Get-CFGDiscoveredResourceCount { }

    Get-Module Config-Operations -All | Remove-Module -Force -ErrorAction SilentlyContinue
    $modulePath = Resolve-Path "$PSScriptRoot/../../../../../../src/CharlandCustomizations/Public/AWS/Config/Config-Operations.psm1"
    Import-Module $modulePath -Force
}

Describe 'Test-CHARConfigResourceType' -Tag 'Unit' {

    Context 'Correction Pipeline - Format-Only Mode' {

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'
        }

        BeforeEach {
            # Reset cache to null so each test triggers fresh cache population attempt
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Returns valid input unchanged' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance'
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Corrects capitalization by PascalCasing each segment' {
            # PascalCase only uppercases first char, preserves rest
            $result = Test-CHARConfigResourceType -ResourceType 'aws::ec2::instance'
            $result | Should -Be 'AWS::Ec2::Instance'
        }

        It 'Preserves existing uppercase characters after first char' {
            $result = Test-CHARConfigResourceType -ResourceType 'aws::EC2::Instance'
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Prepends AWS:: prefix when missing' {
            $result = Test-CHARConfigResourceType -ResourceType 'EC2::Instance'
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Normalizes single-colon separators to double-colon' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS:EC2:Instance'
            # After separator fix: AWS::EC2::Instance, then PascalCase preserves uppercase
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Normalizes mixed single and double-colon separators' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::EC2:Instance'
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Trims leading and trailing whitespace' {
            $result = Test-CHARConfigResourceType -ResourceType '  AWS::EC2::Instance  '
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Applies whitespace trimming combined with other corrections' {
            $result = Test-CHARConfigResourceType -ResourceType '  aws:ec2:instance  '
            $result | Should -Be 'AWS::Ec2::Instance'
        }

        It 'Applies corrections in order: trim, separators, prefix, PascalCase' {
            # Input: whitespace + missing prefix + single colons + wrong case
            $result = Test-CHARConfigResourceType -ResourceType ' ec2:instance '
            $result | Should -Be 'AWS::Ec2::Instance'
        }

        It 'Combines multiple corrections: whitespace + single colons + missing prefix' {
            $result = Test-CHARConfigResourceType -ResourceType '  s3:bucket  '
            $result | Should -Be 'AWS::S3::Bucket'
        }

        It 'Handles lowercase prefix by forcing first segment to AWS' {
            $result = Test-CHARConfigResourceType -ResourceType 'Aws::Lambda::Function'
            $result | Should -Be 'AWS::Lambda::Function'
        }
    }

    Context 'Invalid Input' {

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Returns $false for $null input' {
            $result = Test-CHARConfigResourceType -ResourceType $null
            $result | Should -Be $false
        }

        It 'Returns $false for empty string' {
            $result = Test-CHARConfigResourceType -ResourceType ''
            $result | Should -Be $false
        }

        It 'Returns $false for whitespace-only string' {
            $result = Test-CHARConfigResourceType -ResourceType '   '
            $result | Should -Be $false
        }

        It 'Returns $false for single segment with no separators' {
            # 'EC2Instance' → prepend → 'AWS::EC2Instance' → only 2 segments → regex fails
            $result = Test-CHARConfigResourceType -ResourceType 'EC2Instance'
            $result | Should -Be $false
        }

        It 'Returns $false for segments containing special characters' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Inst@nce'
            $result | Should -Be $false
        }

        It 'Returns $false for segments beginning with digits' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::2EC::Instance'
            $result | Should -Be $false
        }

        It 'Returns $false for too few segments after prefix' {
            # 'AWS::EC2' → only 2 segments in split → regex requires 3-segment ::
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::EC2'
            $result | Should -Be $false
        }

        It 'Returns $false for empty segment between separators' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::::Instance'
            $result | Should -Be $false
        }

        It 'Never throws a terminating error for invalid input' {
            { Test-CHARConfigResourceType -ResourceType $null } | Should -Not -Throw
            { Test-CHARConfigResourceType -ResourceType '' } | Should -Not -Throw
            { Test-CHARConfigResourceType -ResourceType '!!invalid!!' } | Should -Not -Throw
            { Test-CHARConfigResourceType -ResourceType 'a' * 1000 } | Should -Not -Throw
        }
    }

    Context 'Pipeline Behavior' {

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Processes multiple piped values producing independent results' {
            $results = @('AWS::EC2::Instance', 'aws::s3::bucket', 'InvalidType') |
                Test-CHARConfigResourceType

            $results | Should -HaveCount 3
            $results[0] | Should -Be 'AWS::EC2::Instance'
            $results[1] | Should -Be 'AWS::S3::Bucket'
            $results[2] | Should -Be $false
        }

        It 'Returns a mix of corrected strings and $false independently' {
            $results = @('EC2::Instance', '', 'Lambda::Function') |
                Test-CHARConfigResourceType

            $results | Should -HaveCount 3
            $results[0] | Should -Be 'AWS::EC2::Instance'
            $results[1] | Should -Be $false
            $results[2] | Should -Be 'AWS::Lambda::Function'
        }
    }

    Context 'Cache-Based Validation' {

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount {
                @(
                    [PSCustomObject]@{ ResourceType = 'AWS::EC2::Instance' },
                    [PSCustomObject]@{ ResourceType = 'AWS::S3::Bucket' },
                    [PSCustomObject]@{ ResourceType = 'AWS::Lambda::Function' },
                    [PSCustomObject]@{ ResourceType = 'AWS::RDS::DBInstance' },
                    [PSCustomObject]@{ ResourceType = 'AWS::IAM::Role' }
                )
            } -ModuleName 'Config-Operations'
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Returns exact cache match unchanged' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance'
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Corrects casing via case-insensitive cache lookup' {
            # 'aws::ec2::instance' → PascalCase → 'AWS::Ec2::Instance' → not exact match
            # → case-insensitive finds 'AWS::EC2::Instance' → returns it
            $result = Test-CHARConfigResourceType -ResourceType 'aws::ec2::instance'
            $result | Should -Be 'AWS::EC2::Instance'
        }

        It 'Returns $false for non-existent type when cache is populated' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::EC2::FakeResource'
            $result | Should -Be $false
        }

        It 'Returns $false for valid format but non-existent service in cache' {
            $result = Test-CHARConfigResourceType -ResourceType 'AWS::FakeService::FakeResource'
            $result | Should -Be $false
        }
    }

    Context 'Cache Lifecycle' {

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount {
                @(
                    [PSCustomObject]@{ ResourceType = 'AWS::EC2::Instance' },
                    [PSCustomObject]@{ ResourceType = 'AWS::S3::Bucket' },
                    [PSCustomObject]@{ ResourceType = 'AWS::Lambda::Function' }
                )
            } -ModuleName 'Config-Operations'
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Populates cache on first call' {
            Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance'
            Should -Invoke Get-CFGDiscoveredResourceCount -Times 1 -Exactly -ModuleName 'Config-Operations'
        }

        It 'Reuses cache on subsequent calls without additional API calls' {
            Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance'
            Test-CHARConfigResourceType -ResourceType 'AWS::S3::Bucket'
            Should -Invoke Get-CFGDiscoveredResourceCount -Times 1 -Exactly -ModuleName 'Config-Operations'
        }

        It 'Discards and re-fetches cache when -RefreshCache is specified' {
            Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance'
            Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance' -RefreshCache
            Should -Invoke Get-CFGDiscoveredResourceCount -Times 2 -Exactly -ModuleName 'Config-Operations'
        }

        Context 'API Failure Fallback' {

            BeforeAll {
                Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
                Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
                Mock Get-CFGDiscoveredResourceCount { throw 'Access denied' } -ModuleName 'Config-Operations'
            }

            BeforeEach {
                & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
            }

            It 'Writes a warning and returns format-corrected string when API fails' {
                $result = Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance' -WarningVariable warn 3>$null
                $result | Should -Be 'AWS::EC2::Instance'
                $warn | Should -Not -BeNullOrEmpty
            }

            It 'Does not retry after API failure — cache set to empty array' {
                # First call triggers the failed API call
                Test-CHARConfigResourceType -ResourceType 'AWS::EC2::Instance' 3>$null
                # Second call should use the empty cache without calling API again
                Test-CHARConfigResourceType -ResourceType 'AWS::S3::Bucket' 3>$null
                Should -Invoke Get-CFGDiscoveredResourceCount -Times 1 -Exactly -ModuleName 'Config-Operations'
            }
        }
    }

    Context 'Property Tests - Output Format Invariant' -Tag 'Property' {
        <#
            Property 1: Output Format Invariant
            For any input string passed to the validator (in format-only mode with empty cache),
            if the return value is not $false, then the returned string MUST match the regex
            ^AWS::[A-Z][a-zA-Z0-9]+::[A-Z][a-zA-Z0-9]+$

            Validates: Requirements 1.7, 1.8
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'

            function New-RandomResourceTypeInput {
                <#
                .SYNOPSIS
                    Generates random resource type inputs for property-based testing.
                .DESCRIPTION
                    Produces a mix of valid, miscased, malformed, and invalid inputs
                    to exercise all branches of the correction pipeline.
                .PARAMETER Count
                    Number of random inputs to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter()]
                    [int]$Count = 100
                )

                $services = @('EC2', 'S3', 'Lambda', 'RDS', 'IAM', 'DynamoDB', 'SNS', 'SQS', 'CloudWatch', 'ECS')
                $resources = @('Instance', 'Bucket', 'Function', 'DBInstance', 'Role', 'Table', 'Topic', 'Queue', 'Alarm', 'Cluster')
                $random = [System.Random]::new()
                $results = [System.Collections.ArrayList]::new()

                for ($i = 0; $i -lt $Count; $i++) {
                    $category = $random.Next(0, 7)
                    $svc = $services[$random.Next(0, $services.Count)]
                    $res = $resources[$random.Next(0, $resources.Count)]

                    switch ($category) {
                        0 {
                            # Valid AWS resource type
                            [void]$results.Add("AWS::${svc}::${res}")
                        }
                        1 {
                            # Miscased variant — randomize case of each character
                            $miscased = -join ("AWS::${svc}::${res}".ToCharArray() | ForEach-Object {
                                if ($random.Next(0, 2) -eq 0) { [char]::ToLower($_) } else { [char]::ToUpper($_) }
                            })
                            [void]$results.Add($miscased)
                        }
                        2 {
                            # Missing prefix
                            [void]$results.Add("${svc}::${res}")
                        }
                        3 {
                            # Single-colon separators
                            [void]$results.Add("AWS:${svc}:${res}")
                        }
                        4 {
                            # Whitespace-padded
                            $pad = ' ' * $random.Next(1, 5)
                            [void]$results.Add("${pad}AWS::${svc}::${res}${pad}")
                        }
                        5 {
                            # Invalid — special characters, digits, empty, null
                            $invalidOptions = @(
                                '',
                                '   ',
                                'JustOneSegment',
                                "AWS::EC2::Inst@nce",
                                "AWS::2Bad::Resource",
                                "AWS::EC2",
                                "AWS::::Instance",
                                '!!invalid!!',
                                "AWS::${svc}::`$pecial",
                                "AWS::${svc}::9Start"
                            )
                            [void]$results.Add($invalidOptions[$random.Next(0, $invalidOptions.Count)])
                        }
                        6 {
                            # Mixed separators
                            [void]$results.Add("AWS::${svc}:${res}")
                        }
                    }
                }

                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'All non-$false outputs match Format_Pattern across 150 random inputs' {
            # Property 1: Output Format Invariant
            # Validates: Requirements 1.7, 1.8
            $formatPattern = '^AWS::[A-Z][a-zA-Z0-9]+::[A-Z][a-zA-Z0-9]+$'
            $inputs = New-RandomResourceTypeInput -Count 150
            $violations = @()

            foreach ($input in $inputs) {
                $result = Test-CHARConfigResourceType -ResourceType $input 3>$null
                if ($result -ne $false) {
                    if ($result -notmatch $formatPattern) {
                        $violations += "Input='$input' → Output='$result' does not match Format_Pattern"
                    }
                }
            }

            $violations | Should -BeNullOrEmpty -Because "every non-`$false output must match ^AWS::[A-Z][a-zA-Z0-9]+::[A-Z][a-zA-Z0-9]+`$"
        }
    }

    Context 'Property Tests - Correction Idempotence' -Tag 'Feature: config-resource-type-validator', 'Property 2: Correction Idempotence' {
        <#
            Property 2: Correction Idempotence
            For any input string that produces a non-$false result, passing that result
            through the validator again (in format-only mode) SHALL return the same string
            unchanged. That is: f(f(x)) == f(x) for all inputs where f(x) != $false.

            Validates: Requirements 1.1, 1.2
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            # Force format-only mode by making cache population fail
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'

            function New-RandomCorrectionInput {
                <#
                .SYNOPSIS
                    Generates random inputs likely to produce non-$false results from the validator.
                .DESCRIPTION
                    Produces a mix of valid AWS resource types, miscased variants, missing prefix,
                    single-colon separators, and whitespace-padded inputs to exercise idempotence.
                .PARAMETER Count
                    Number of random inputs to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter()]
                    [int]$Count = 100
                )

                $services = @('EC2', 'S3', 'Lambda', 'RDS', 'IAM', 'DynamoDB', 'CloudWatch',
                    'SNS', 'SQS', 'ECS', 'EKS', 'Redshift', 'ElastiCache', 'KMS',
                    'CloudFront', 'Route53', 'CodeBuild', 'CodePipeline', 'StepFunctions',
                    'AppSync')
                $resources = @('Instance', 'Bucket', 'Function', 'DBInstance', 'Role', 'Table',
                    'Alarm', 'Topic', 'Queue', 'Cluster', 'Service', 'Distribution',
                    'HostedZone', 'Project', 'Pipeline', 'StateMachine', 'GraphqlApi',
                    'Volume', 'SecurityGroup', 'Subnet')

                $random = [System.Random]::new()
                $results = [System.Collections.Generic.List[string]]::new($Count)

                for ($i = 0; $i -lt $Count; $i++) {
                    $service = $services[$random.Next(0, $services.Count)]
                    $resource = $resources[$random.Next(0, $resources.Count)]
                    $variant = $random.Next(0, 5)

                    switch ($variant) {
                        0 {
                            # Already valid
                            $results.Add("AWS::${service}::${resource}")
                        }
                        1 {
                            # Miscased — lowercase everything
                            $results.Add("aws::$($service.ToLower())::$($resource.ToLower())")
                        }
                        2 {
                            # Missing prefix (correctable two-segment input)
                            $results.Add("${service}::${resource}")
                        }
                        3 {
                            # Single-colon separators
                            $results.Add("AWS:${service}:${resource}")
                        }
                        4 {
                            # Whitespace-padded valid input
                            $pad = ' ' * $random.Next(1, 5)
                            $results.Add("${pad}AWS::${service}::${resource}${pad}")
                        }
                    }
                }
                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Applying the validator twice produces the same result as applying it once (f(f(x)) == f(x)) for 150 generated inputs' {
            # Property 2: Correction Idempotence
            # Validates: Requirements 1.1, 1.2
            $inputs = New-RandomCorrectionInput -Count 150
            $violations = [System.Collections.Generic.List[string]]::new()

            foreach ($input in $inputs) {
                # First application
                & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
                $first = Test-CHARConfigResourceType -ResourceType $input 3>$null

                # Only test idempotence for inputs that produce non-$false results
                if ($first -ne $false) {
                    # Reset cache for second application (same format-only conditions)
                    & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
                    $second = Test-CHARConfigResourceType -ResourceType $first 3>$null

                    if ($second -ne $first) {
                        $violations.Add("Input='$input' -> first='$first' -> second='$second'")
                    }
                }
            }

            $violations | Should -HaveCount 0 -Because "correction must be idempotent: f(f(x)) must equal f(x) for all inputs where f(x) is not `$false. Failures: $($violations -join '; ')"
        }
    }

    Context 'Property Tests - No-Throw Guarantee' -Tag 'Property' {
        <#
            Property 5: No-Throw Guarantee
            For any input value (including $null, empty string, random binary-like strings,
            extremely long strings), the validator SHALL never throw a terminating error.
            It SHALL always return either a valid string or $false.

            Validates: Requirements 1.10
            Feature: config-resource-type-validator, Property 5: No-Throw Guarantee
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'

            function New-RandomArbitraryInput {
                <#
                .SYNOPSIS
                    Generates arbitrary and adversarial inputs for no-throw property testing.
                .DESCRIPTION
                    Produces a wide variety of challenging inputs including nulls, empties,
                    control characters, unicode, SQL injection patterns, extremely long strings,
                    and random byte-like data to verify the validator never throws.
                .PARAMETER Count
                    Number of random inputs to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter()]
                    [int]$Count = 100
                )

                $random = [System.Random]::new()
                $results = [System.Collections.ArrayList]::new()

                # Always include these specific adversarial inputs
                [void]$results.Add($null)
                [void]$results.Add('')
                [void]$results.Add('   ')
                [void]$results.Add("`n")
                [void]$results.Add("`t")
                [void]$results.Add("`0")
                [void]$results.Add([string][char]0x00)
                [void]$results.Add('::::::::')
                [void]$results.Add(':::')
                [void]$results.Add("'; DROP TABLE --")
                [void]$results.Add('A::B::C::D::E::F')
                [void]$results.Add('A::B::C::D::E::F::G::H::I::J')
                [void]$results.Add('\backslash\path\here')
                [void]$results.Add('"quoted"')
                [void]$results.Add("'single'")
                [void]$results.Add('[brackets]')
                [void]$results.Add('{braces}')
                [void]$results.Add('(parens)')
                [void]$results.Add('$variable')
                [void]$results.Add('@{hashtable}')
                [void]$results.Add('`backtick`')
                # Unicode characters
                [void]$results.Add([char]0x00E9 + '::' + [char]0x00F1 + '::test')
                [void]$results.Add([char]0x2603 + '::Snowman::Resource')
                [void]$results.Add('AWS::' + [char]0x0041 + [char]0x0301 + '::Thing')
                # Very long string (600 chars of random alphanumeric)
                $longChars = -join (1..600 | ForEach-Object { [char]$random.Next(65, 123) })
                [void]$results.Add($longChars)
                # Another very long string as a pseudo resource type
                $longService = -join (1..300 | ForEach-Object { [char]$random.Next(97, 123) })
                [void]$results.Add("AWS::${longService}::Resource")

                # Fill remaining with random adversarial inputs
                $remaining = $Count - $results.Count
                for ($i = 0; $i -lt $remaining; $i++) {
                    $category = $random.Next(0, 10)

                    switch ($category) {
                        0 {
                            # Random bytes as string
                            $len = $random.Next(1, 50)
                            $chars = -join (1..$len | ForEach-Object { [char]$random.Next(0, 256) })
                            [void]$results.Add($chars)
                        }
                        1 {
                            # Control characters mixed with text
                            $controls = @("`n", "`r", "`t", "`0", [string][char]0x0B, [string][char]0x0C)
                            $text = 'AWS::EC2::Instance'
                            $pos = $random.Next(0, $text.Length)
                            $ctrl = $controls[$random.Next(0, $controls.Count)]
                            [void]$results.Add($text.Insert($pos, $ctrl))
                        }
                        2 {
                            # Only special characters
                            $specials = '!@#$%^&*()_+-=[]{}|;:,.<>?/~`'
                            $len = $random.Next(1, 30)
                            $str = -join (1..$len | ForEach-Object { $specials[$random.Next(0, $specials.Length)] })
                            [void]$results.Add($str)
                        }
                        3 {
                            # Numeric strings
                            $len = $random.Next(1, 20)
                            $str = -join (1..$len | ForEach-Object { [char]$random.Next(48, 58) })
                            [void]$results.Add($str)
                        }
                        4 {
                            # Strings that look like resource types but have invalid chars
                            $invalidChars = @('@', '#', '!', '$', '%', '^', '&', '*', '(', ')', ' ', '+')
                            $ch = $invalidChars[$random.Next(0, $invalidChars.Count)]
                            [void]$results.Add("AWS::EC2${ch}::Instance")
                        }
                        5 {
                            # Very long repeated characters
                            $ch = [char]$random.Next(65, 91)
                            $len = $random.Next(500, 1000)
                            [void]$results.Add([string]::new($ch, $len))
                        }
                        6 {
                            # Empty-ish variants with different whitespace
                            $wsChars = @(' ', "`t", "`n", "`r")
                            $len = $random.Next(1, 20)
                            $str = -join (1..$len | ForEach-Object { $wsChars[$random.Next(0, $wsChars.Count)] })
                            [void]$results.Add($str)
                        }
                        7 {
                            # Paths and URL-like strings
                            $options = @(
                                'C:\Windows\System32\cmd.exe',
                                'https://example.com/api?key=secret',
                                '/etc/passwd',
                                '../../../etc/shadow',
                                'file:///tmp/test'
                            )
                            [void]$results.Add($options[$random.Next(0, $options.Count)])
                        }
                        8 {
                            # Regex-like patterns that might trip up the engine
                            $options = @(
                                '(?<!:):(?!:)',
                                '^AWS::[A-Z]+::[A-Z]+$',
                                '.*',
                                '(((((nested)))))',
                                '[a-z]{1,100}'
                            )
                            [void]$results.Add($options[$random.Next(0, $options.Count)])
                        }
                        9 {
                            # Mixed valid structure with random Unicode
                            $unicodeChar = [char]$random.Next(0x0100, 0x07FF)
                            [void]$results.Add("AWS::${unicodeChar}Service::Resource")
                        }
                    }
                }

                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Never throws a terminating error for any of 150 arbitrary inputs' {
            # Property 5: No-Throw Guarantee
            # Validates: Requirements 1.10
            $inputs = New-RandomArbitraryInput -Count 150
            $throws = @()

            foreach ($input in $inputs) {
                try {
                    $null = Test-CHARConfigResourceType -ResourceType $input 3>$null 2>$null
                }
                catch {
                    $displayInput = if ($null -eq $input) { '<$null>' } else { "'$input'" }
                    $throws += "Input=${displayInput} threw: $($_.Exception.Message)"
                }
            }

            $throws | Should -BeNullOrEmpty -Because 'the validator must never throw a terminating error for any input value'
        }
    }

    Context 'Property Tests - Whitespace Invariance' -Tag 'Feature: config-resource-type-validator', 'Property 3: Whitespace Invariance' {
        <#
            Property 3: Whitespace Invariance
            For any input string s and any amount of leading/trailing whitespace w,
            the validator SHALL produce the same result for w + s + w as it does for s.
            That is: f(trim(x)) == f(x) for all inputs.

            Validates: Requirements 1.6
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            # Force format-only mode by making cache population fail
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'

            function New-RandomWhitespacePaddedInput {
                <#
                .SYNOPSIS
                    Generates pairs of trimmed and whitespace-padded inputs for invariance testing.
                .DESCRIPTION
                    For each generated pair, the Trimmed value is a base resource type input
                    (valid, miscased, missing prefix, etc.) and the Padded value is the same
                    input wrapped with random leading and trailing whitespace (spaces and tabs).
                .PARAMETER Count
                    Number of pairs to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter()]
                    [int]$Count = 100
                )

                # Whitespace characters to draw from
                $whitespaceChars = @(' ', ' ', ' ', "`t")

                # Base inputs covering various correction scenarios
                $baseInputs = @(
                    'AWS::EC2::Instance',
                    'AWS::S3::Bucket',
                    'AWS::Lambda::Function',
                    'AWS::RDS::DBInstance',
                    'AWS::IAM::Role',
                    'aws::ec2::instance',
                    'aws::s3::bucket',
                    'aws::lambda::function',
                    'Aws::Lambda::Function',
                    'EC2::Instance',
                    'S3::Bucket',
                    'Lambda::Function',
                    'IAM::Role',
                    'AWS:EC2:Instance',
                    'AWS:S3:Bucket',
                    'AWS:Lambda:Function',
                    'ec2:instance',
                    's3:bucket',
                    'lambda:function',
                    'AWS::EC2:Instance',
                    'AWS::S3:Bucket',
                    'AWS::CloudFormation::Stack',
                    'aws::cloudformation::stack',
                    'CloudFormation::Stack',
                    'iam::role',
                    'AWS::DynamoDB::Table',
                    'dynamodb::table',
                    'AWS::ECS::Cluster',
                    'AWS::SNS::Topic',
                    'sns:topic'
                )

                $random = [System.Random]::new()
                $results = [System.Collections.Generic.List[PSCustomObject]]::new($Count)

                for ($i = 0; $i -lt $Count; $i++) {
                    # Pick a base input from the pool
                    $base = $baseInputs[$i % $baseInputs.Count]

                    # Generate random leading whitespace (1-10 characters)
                    $leadCount = $random.Next(1, 11)
                    $leading = -join (1..$leadCount | ForEach-Object {
                        $whitespaceChars[$random.Next(0, $whitespaceChars.Count)]
                    })

                    # Generate random trailing whitespace (1-10 characters)
                    $trailCount = $random.Next(1, 11)
                    $trailing = -join (1..$trailCount | ForEach-Object {
                        $whitespaceChars[$random.Next(0, $whitespaceChars.Count)]
                    })

                    $results.Add([PSCustomObject]@{
                        Trimmed = $base
                        Padded  = "${leading}${base}${trailing}"
                    })
                }

                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Whitespace padding does not change the result for 120 generated inputs (Property 3)' {
            # Property 3: Whitespace Invariance
            # Validates: Requirements 1.6
            $pairs = New-RandomWhitespacePaddedInput -Count 120
            $violations = [System.Collections.Generic.List[string]]::new()

            foreach ($pair in $pairs) {
                # Reset cache before trimmed call
                & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
                $trimmedResult = Test-CHARConfigResourceType -ResourceType $pair.Trimmed 3>$null

                # Reset cache before padded call to ensure identical conditions
                & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
                $paddedResult = Test-CHARConfigResourceType -ResourceType $pair.Padded 3>$null

                if ($paddedResult -ne $trimmedResult) {
                    $violations.Add("f('$($pair.Padded)') = '$paddedResult' but f('$($pair.Trimmed)') = '$trimmedResult'")
                }
            }

            $violations | Should -HaveCount 0 -Because (
                "whitespace must not affect output: f(trim(x)) must equal f(x) for all inputs. Failures: $($violations -join '; ')"
            )
        }
    }

    Context 'Property Tests - Invalid Input Rejection' -Tag 'Property', 'Feature: config-resource-type-validator', 'Property 4: Invalid Input Rejection' {
        <#
            Property 4: Invalid Input Rejection
            For any input string that contains non-alphanumeric characters within segments
            (after separators are normalized), has segments beginning with a digit, or has
            fewer than two meaningful segments after the AWS:: prefix, the validator SHALL
            return $false.

            Validates: Requirements 1.8, 1.9
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'

            function New-RandomInvalidInput {
                <#
                .SYNOPSIS
                    Generates inputs guaranteed to be rejected by the validator.
                .DESCRIPTION
                    Produces strings that cannot be corrected to a valid AWS Config resource
                    type: special characters in segments, digit-leading segments, too few
                    segments, and empty/null-like values.
                .PARAMETER Count
                    Number of invalid inputs to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter()]
                    [int]$Count = 100
                )

                $specialChars = @('!', '@', '#', '$', '%', '^', '&', '*', '(', ')', ' ', '+', '=', '?', '<', '>', '/', '\', '|', '{', '}', '[', ']', '~')
                $validSegments = @('EC2', 'S3', 'Lambda', 'RDS', 'IAM', 'DynamoDB', 'SNS', 'SQS', 'ECS', 'EKS')
                $validResources = @('Instance', 'Bucket', 'Function', 'DBInstance', 'Role', 'Table', 'Topic', 'Queue', 'Cluster', 'Service')
                $random = [System.Random]::new()
                $results = [System.Collections.Generic.List[string]]::new($Count)

                # Category 1: Segments with special characters (~33% of output)
                $specialCharCount = [math]::Ceiling($Count * 0.33)
                for ($i = 0; $i -lt $specialCharCount; $i++) {
                    $char = $specialChars[$random.Next(0, $specialChars.Count)]
                    $segment = $validSegments[$random.Next(0, $validSegments.Count)]
                    $resource = $validResources[$random.Next(0, $validResources.Count)]
                    # Insert special char at random position within the resource segment
                    $pos = $random.Next(1, $resource.Length)
                    $badResource = $resource.Insert($pos, $char)
                    $results.Add("AWS::${segment}::${badResource}")
                }

                # Category 2: Segments beginning with digits (~22% of output)
                $digitCount = [math]::Ceiling($Count * 0.22)
                for ($i = 0; $i -lt $digitCount; $i++) {
                    $digit = $random.Next(0, 10)
                    $segment = $validSegments[$random.Next(0, $validSegments.Count)]
                    $resource = $validResources[$random.Next(0, $validResources.Count)]
                    # Randomly put digit-leading in service or resource position
                    if ($random.Next(0, 2) -eq 0) {
                        $results.Add("AWS::${digit}${segment}::${resource}")
                    }
                    else {
                        $results.Add("AWS::${segment}::${digit}${resource}")
                    }
                }

                # Category 3: Too few segments after prefix (~22% of output)
                $fewSegCount = [math]::Ceiling($Count * 0.22)
                for ($i = 0; $i -lt $fewSegCount; $i++) {
                    $segment = $validSegments[$random.Next(0, $validSegments.Count)]
                    $variant = $random.Next(0, 3)
                    switch ($variant) {
                        0 { $results.Add("AWS::${segment}") }            # Only one segment after AWS::
                        1 { $results.Add($segment) }                      # Single word, no separators
                        2 { $results.Add("${segment}Something") }         # Concatenated, no separators
                    }
                }

                # Category 4: Empty/null-like and garbage (~23% of output)
                $garbageCount = $Count - $specialCharCount - $digitCount - $fewSegCount
                $garbagePool = @(
                    '',
                    '   ',
                    '      ',
                    '!@#$%',
                    ':::',
                    '::::',
                    'AWS::!!::##',
                    'AWS::::Instance',
                    '::EC2::Instance',
                    'AWS::EC2::',
                    'AWS::::',
                    '!!invalid!!',
                    '12345',
                    '....',
                    'AWS::  ::  ',
                    'AWS:: EC2:: Instance',
                    'A W S :: E C 2 :: I n s t a n c e'
                )
                for ($i = 0; $i -lt $garbageCount; $i++) {
                    $results.Add($garbagePool[$random.Next(0, $garbagePool.Count)])
                }

                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'All invalid inputs return $false across 120 generated cases' {
            # Property 4: Invalid Input Rejection
            # Validates: Requirements 1.8, 1.9
            $invalidInputs = New-RandomInvalidInput -Count 120
            $violations = [System.Collections.Generic.List[string]]::new()

            foreach ($input in $invalidInputs) {
                $result = Test-CHARConfigResourceType -ResourceType $input 3>$null
                if ($result -ne $false) {
                    $violations.Add("Input='${input}' returned '${result}' instead of `$false")
                }
            }

            $violations | Should -HaveCount 0 -Because "all structurally invalid inputs (special chars in segments, digit-leading segments, too few segments, empty/garbage) must return `$false. Failures: $($violations -join '; ')"
        }
    }

    Context 'Property Tests - Cache-Based Case Correction' -Tag 'Feature: config-resource-type-validator', 'Property 6: Cache-Based Case Correction' {
        <#
            Property 6: Cache-Based Case Correction
            For any valid resource type string in the cached list, and any case variation
            of that string that produces the same value under case-insensitive comparison,
            the validator SHALL return the exact string from the cache (authoritative casing).

            Validates: Requirements 2.9, 2.10
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount {
                @(
                    [PSCustomObject]@{ ResourceType = 'AWS::EC2::Instance' },
                    [PSCustomObject]@{ ResourceType = 'AWS::S3::Bucket' },
                    [PSCustomObject]@{ ResourceType = 'AWS::Lambda::Function' },
                    [PSCustomObject]@{ ResourceType = 'AWS::RDS::DBInstance' },
                    [PSCustomObject]@{ ResourceType = 'AWS::IAM::Role' },
                    [PSCustomObject]@{ ResourceType = 'AWS::DynamoDB::Table' },
                    [PSCustomObject]@{ ResourceType = 'AWS::CloudWatch::Alarm' },
                    [PSCustomObject]@{ ResourceType = 'AWS::SNS::Topic' },
                    [PSCustomObject]@{ ResourceType = 'AWS::SQS::Queue' },
                    [PSCustomObject]@{ ResourceType = 'AWS::ECS::Cluster' }
                )
            } -ModuleName 'Config-Operations'

            function New-RandomCaseVariant {
                <#
                .SYNOPSIS
                    Generates random case variants of a given resource type string.
                .DESCRIPTION
                    For a given input string, produces Count random case variants by
                    randomly toggling the case of each character. Ensures at least one
                    character differs from the original in each variant.
                .PARAMETER InputString
                    The source resource type string to generate variants of.
                .PARAMETER Count
                    Number of case variants to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter(Mandatory)]
                    [string]$InputString,

                    [Parameter()]
                    [int]$Count = 10
                )

                $random = [System.Random]::new()
                $results = [System.Collections.Generic.List[string]]::new($Count)

                for ($i = 0; $i -lt $Count; $i++) {
                    $attempts = 0
                    do {
                        $variant = -join ($InputString.ToCharArray() | ForEach-Object {
                            if ($random.Next(0, 2) -eq 0) {
                                [char]::ToLower($_)
                            }
                            else {
                                [char]::ToUpper($_)
                            }
                        })
                        $attempts++
                        # Ensure at least one char differs from original (avoid identical output)
                    } while ($variant -ceq $InputString -and $attempts -lt 20)

                    # Fallback: if we couldn't differ, just lowercase the whole thing
                    if ($variant -ceq $InputString) {
                        $variant = $InputString.ToLower()
                    }

                    $results.Add($variant)
                }

                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'All case variants of cached types resolve to the authoritative cached entry across 120+ generated variants' {
            # Property 6: Cache-Based Case Correction
            # Validates: Requirements 2.9, 2.10
            $cachedTypes = @(
                'AWS::EC2::Instance',
                'AWS::S3::Bucket',
                'AWS::Lambda::Function',
                'AWS::RDS::DBInstance',
                'AWS::IAM::Role',
                'AWS::DynamoDB::Table',
                'AWS::CloudWatch::Alarm',
                'AWS::SNS::Topic',
                'AWS::SQS::Queue',
                'AWS::ECS::Cluster'
            )

            $violations = [System.Collections.Generic.List[string]]::new()

            foreach ($cachedType in $cachedTypes) {
                $variants = New-RandomCaseVariant -InputString $cachedType -Count 12

                foreach ($variant in $variants) {
                    # Reset cache so each call triggers fresh cache population from mock
                    & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
                    $result = Test-CHARConfigResourceType -ResourceType $variant

                    if ($result -ne $cachedType) {
                        $violations.Add("Variant='$variant' of cached='$cachedType' returned='$result'")
                    }
                }
            }

            $violations | Should -HaveCount 0 -Because (
                "every case variant of a cached resource type must resolve to the exact authoritative cached string. Failures: $($violations -join '; ')"
            )
        }
    }

    Context 'Property Tests - Non-Existent Type Rejection' -Tag 'Feature: config-resource-type-validator', 'Property 7: Non-Existent Type Rejection' {
        <#
            Property 7: Non-Existent Type Rejection with Populated Cache
            For any string that passes format validation but does not match any entry
            in a populated (non-empty) cache under case-insensitive comparison, the
            validator SHALL return $false.

            Validates: Requirements 2.11
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount {
                @(
                    [PSCustomObject]@{ ResourceType = 'AWS::EC2::Instance' },
                    [PSCustomObject]@{ ResourceType = 'AWS::S3::Bucket' },
                    [PSCustomObject]@{ ResourceType = 'AWS::Lambda::Function' },
                    [PSCustomObject]@{ ResourceType = 'AWS::RDS::DBInstance' },
                    [PSCustomObject]@{ ResourceType = 'AWS::IAM::Role' }
                )
            } -ModuleName 'Config-Operations'

            function New-RandomNonExistentType {
                <#
                .SYNOPSIS
                    Generates format-valid resource type strings that are NOT in the known cache.
                .DESCRIPTION
                    Produces strings matching ^AWS::[A-Z][a-zA-Z0-9]+::[A-Z][a-zA-Z0-9]+$
                    using service and resource names that do not match any of the 5 cached
                    types (EC2::Instance, S3::Bucket, Lambda::Function, RDS::DBInstance,
                    IAM::Role). Includes both real-looking AWS types and random PascalCase
                    combinations.
                .PARAMETER Count
                    Number of non-existent types to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter()]
                    [int]$Count = 100
                )

                # Real AWS service/resource names that are NOT in our small cache
                $knownNonCachedTypes = @(
                    'AWS::Neptune::Database',
                    'AWS::Glue::Crawler',
                    'AWS::EKS::Cluster',
                    'AWS::CodeBuild::Project',
                    'AWS::CloudFront::Distribution',
                    'AWS::Route53::HostedZone',
                    'AWS::DynamoDB::Table',
                    'AWS::SNS::Topic',
                    'AWS::SQS::Queue',
                    'AWS::ECS::Service',
                    'AWS::Redshift::Cluster',
                    'AWS::ElastiCache::CacheCluster',
                    'AWS::AppSync::GraphqlApi',
                    'AWS::StepFunctions::StateMachine',
                    'AWS::CodePipeline::Pipeline',
                    'AWS::CloudWatch::Alarm',
                    'AWS::Kinesis::Stream',
                    'AWS::SageMaker::Endpoint',
                    'AWS::Athena::WorkGroup',
                    'AWS::EMR::Cluster'
                )

                # PascalCase segments for random generation (none overlap with cached types)
                $randomServices = @('Xyzabc', 'Foosvc', 'Barsvc', 'Quuxsvc', 'Netsvc',
                    'Datasvc', 'Appsvc', 'Logsvc', 'Evtsvc', 'Msgsvc',
                    'Worksvc', 'Mlsvc', 'Iotsvc', 'Secops', 'Platsvc')
                $randomResources = @('Foobar', 'Widget', 'Gadget', 'Thingy', 'Doohickey',
                    'Gizmo', 'Contraption', 'Apparatus', 'Mechanism', 'Device',
                    'Processor', 'Handler', 'Resolver', 'Builder', 'Manager')

                $random = [System.Random]::new()
                $results = [System.Collections.Generic.List[string]]::new($Count)

                for ($i = 0; $i -lt $Count; $i++) {
                    if ($i -lt $knownNonCachedTypes.Count) {
                        # Use known real-looking non-cached types first
                        $results.Add($knownNonCachedTypes[$i])
                    }
                    else {
                        # Generate random PascalCase type not in cache
                        $svc = $randomServices[$random.Next(0, $randomServices.Count)]
                        $res = $randomResources[$random.Next(0, $randomResources.Count)]
                        $results.Add("AWS::${svc}::${res}")
                    }
                }

                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'All format-valid strings not in the cache return $false across 120 generated inputs' {
            # Property 7: Non-Existent Type Rejection with Populated Cache
            # Validates: Requirements 2.11
            $inputs = New-RandomNonExistentType -Count 120
            $violations = [System.Collections.Generic.List[string]]::new()

            foreach ($input in $inputs) {
                $result = Test-CHARConfigResourceType -ResourceType $input
                if ($result -ne $false) {
                    $violations.Add("Input='${input}' returned '${result}' instead of `$false")
                }
            }

            $violations | Should -HaveCount 0 -Because "all format-valid strings not present in the populated cache (case-insensitive) must return `$false. Failures: $($violations -join '; ')"
        }
    }

    Context 'Property Tests - Pipeline Independence' -Tag 'Feature: config-resource-type-validator', 'Property 8: Pipeline Independence' {
        <#
            Property 8: Pipeline Independence
            For any array of N input strings piped to the validator, the function SHALL
            produce exactly N output values, and the i-th output SHALL be identical to
            calling the validator with only the i-th input.

            Validates: Requirements 3.5, 3.6
        #>

        BeforeAll {
            Mock Test-CHARAWSCmdlet { } -ModuleName 'Config-Operations'
            Mock New-AWSParamSplat { return @{} } -ModuleName 'Config-Operations'
            Mock Get-CFGDiscoveredResourceCount { throw 'Not available' } -ModuleName 'Config-Operations'

            function New-RandomPipelineInput {
                <#
                .SYNOPSIS
                    Generates random inputs for pipeline independence property testing.
                .DESCRIPTION
                    Produces a mix of valid, miscased, missing prefix, single-colon,
                    whitespace-padded, and invalid inputs to verify pipeline processing
                    matches individual invocation results.
                .PARAMETER Count
                    Number of random inputs to generate.
                #>
                [CmdletBinding()]
                param(
                    [Parameter()]
                    [int]$Count = 50
                )

                $services = @('EC2', 'S3', 'Lambda', 'RDS', 'IAM', 'DynamoDB', 'SNS', 'SQS',
                    'CloudWatch', 'ECS', 'EKS', 'Redshift', 'KMS', 'CloudFront', 'Route53')
                $resources = @('Instance', 'Bucket', 'Function', 'DBInstance', 'Role', 'Table',
                    'Topic', 'Queue', 'Alarm', 'Cluster', 'Service', 'Key', 'Distribution',
                    'HostedZone', 'SecurityGroup')

                $random = [System.Random]::new()
                $results = [System.Collections.Generic.List[string]]::new($Count)

                for ($i = 0; $i -lt $Count; $i++) {
                    $svc = $services[$random.Next(0, $services.Count)]
                    $res = $resources[$random.Next(0, $resources.Count)]
                    $category = $random.Next(0, 8)

                    switch ($category) {
                        0 {
                            # Valid AWS resource type
                            $results.Add("AWS::${svc}::${res}")
                        }
                        1 {
                            # Miscased variant
                            $results.Add("aws::$($svc.ToLower())::$($res.ToLower())")
                        }
                        2 {
                            # Missing prefix
                            $results.Add("${svc}::${res}")
                        }
                        3 {
                            # Single-colon separators
                            $results.Add("AWS:${svc}:${res}")
                        }
                        4 {
                            # Whitespace-padded
                            $pad = ' ' * $random.Next(1, 4)
                            $results.Add("${pad}AWS::${svc}::${res}${pad}")
                        }
                        5 {
                            # Invalid — special chars
                            $results.Add("AWS::${svc}::Inst@nce")
                        }
                        6 {
                            # Invalid — too few segments
                            $results.Add($svc)
                        }
                        7 {
                            # Mixed separators
                            $results.Add("AWS::${svc}:${res}")
                        }
                    }
                }

                return $results.ToArray()
            }
        }

        BeforeEach {
            & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
        }

        It 'Pipeline output matches individual invocation for batches of 10, 25, and 50 inputs' {
            # Property 8: Pipeline Independence
            # Validates: Requirements 3.5, 3.6
            $violations = [System.Collections.Generic.List[string]]::new()

            foreach ($batchSize in @(10, 25, 50)) {
                $inputs = New-RandomPipelineInput -Count $batchSize

                # Pipeline invocation — reset cache once before piping the batch
                & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
                $pipelineResults = @($inputs | Test-CHARConfigResourceType 3>$null)

                # Individual invocations — reset cache before each call
                $individualResults = @()
                foreach ($input in $inputs) {
                    & (Get-Module Config-Operations) { $script:ConfigResourceTypeCache = $null }
                    $individualResults += Test-CHARConfigResourceType -ResourceType $input 3>$null
                }

                # Assert count equality
                if ($pipelineResults.Count -ne $individualResults.Count) {
                    $violations.Add("Batch=${batchSize}: pipeline produced $($pipelineResults.Count) results but individual produced $($individualResults.Count)")
                    continue
                }

                # Assert per-element equality
                for ($i = 0; $i -lt $pipelineResults.Count; $i++) {
                    if ($pipelineResults[$i] -ne $individualResults[$i]) {
                        $violations.Add("Batch=${batchSize}, Index=${i}: pipeline='$($pipelineResults[$i])' vs individual='$($individualResults[$i])' for input='$($inputs[$i])'")
                    }
                }
            }

            $violations | Should -HaveCount 0 -Because (
                "piping N inputs must produce identical results to N individual calls. Failures: $($violations -join '; ')"
            )
        }
    }
}
