<#
.SYNOPSIS
    Private helper functions used internally by IAM-Customizations.psm1.

.DESCRIPTION
    Contains the private helpers backing Get-CHARPrincipalPermission: principal ARN
    parsing, glob-pattern intersection, IAM action-overlap matching, and principal
    policy-document aggregation.

    These are NOT exported to end users.

.NOTES
    Used by:
        - Get-CHARPrincipalPermission

    Generated by Kiro using Claude Opus 4.8, reviewed by ccharland
#>

function Resolve-CHARPrincipalArn {
    <#
    .SYNOPSIS
        Derives the IAM principal type and name from a principal ARN.

    .DESCRIPTION
        Private helper that parses an IAM principal ARN of the form
        'arn:aws:iam::<12-digit-account>:(role|user|group)/<path><name>' and returns
        the principal type (Role, User, or Group) along with the trailing name segment.

        The resource keyword in the ARN (role/user/group) determines the principal
        type. Any optional path segments are stripped so only the final name component
        is returned. A terminating error is thrown for malformed or non-IAM ARNs so
        callers fail fast rather than proceeding with an unusable principal.

    .PARAMETER PrincipalArn
        The IAM principal ARN to parse. Must be a role, user, or group ARN.

    .OUTPUTS
        PSCustomObject with properties:
            Type - The principal type: 'Role', 'User', or 'Group'
            Name - The trailing name segment of the principal (path stripped)

    .EXAMPLE
        Resolve-CHARPrincipalArn -PrincipalArn 'arn:aws:iam::123456789012:role/app/read-only'

        Returns [PSCustomObject]@{ Type = 'Role'; Name = 'read-only' }.

    .NOTES
        Generated by Kiro using Claude Opus 4.8, reviewed by ccharland
        Created: August 2026

        This is a PRIVATE helper and is intentionally not exported.

    .LINK
        https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html
    #>
    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory)]
        [string]$PrincipalArn
    )

    # IAM ARN shape: arn:aws:iam::<account>:<resourceType>/<path><name>
    # Capture the resource keyword to derive the principal type, and the remainder
    # (path + name) so we can strip any path down to the trailing name segment.
    $pattern = '^arn:aws:iam::\d{12}:(role|user|group)/(.+)$'
    $match = [regex]::Match($PrincipalArn, $pattern)

    if (-not $match.Success) {
        # Terminating error naming the supplied value and the expected formats (Req 1.4).
        throw "Invalid IAM principal ARN: '$PrincipalArn'. Expected one of: " +
        "arn:aws:iam::<account-id>:role/<name>, " +
        "arn:aws:iam::<account-id>:user/<name>, " +
        "arn:aws:iam::<account-id>:group/<name>."
    }

    $resourceType = $match.Groups[1].Value            # role|user|group (lowercase)
    $resourcePath = $match.Groups[2].Value            # path + name, e.g. app/read-only
    $name = ($resourcePath -split '/')[-1]            # trailing name segment

    [PSCustomObject]@{
        # TitleCase the resource keyword so callers get 'Role'|'User'|'Group' (Req 1.1-1.3).
        Type = (Get-Culture).TextInfo.ToTitleCase($resourceType)
        Name = $name
    }
}

function Test-CHARGlobIntersect {
    <#
    .SYNOPSIS
        Decides whether two glob patterns share at least one concrete string.

    .DESCRIPTION
        Private helper that determines whether two glob patterns using '*'
        (zero-or-more characters) and '?' (exactly one character) as wildcards
        overlap -- that is, whether there exists at least one concrete string
        matched by BOTH patterns.

        The decision uses the classic memoized "do two wildcard patterns
        intersect" dynamic program. Define Intersect(i, j) as true when the
        suffix of PatternA starting at index i can share a concrete tail with
        the suffix of PatternB starting at index j:

            - Both suffixes empty                       => true
            - A[i] is '*'  => Intersect(i+1, j) OR
                              (j < len(B) AND Intersect(i, j+1))
            - B[j] is '*'  => Intersect(i, j+1) OR
                              (i < len(A) AND Intersect(i+1, j))   (symmetric)
            - Both non-'*' => compatible (equal, or either is '?') then
                              Intersect(i+1, j+1); otherwise false
            - One suffix empty, the other's remaining chars all '*' => true;
              otherwise false

        The recurrence operates purely on the pattern strings -- there is no
        enumeration of the concrete action space and no regex construction. It
        is evaluated by a bottom-up dynamic-programming fill of an
        (len(A)+1) x (len(B)+1) table (equivalent to the memoized recurrence),
        so each Intersect(i, j) sub-problem is resolved exactly once for an
        O(len(A) * len(B)) bound. The relation is symmetric by construction, so
        swapping the two arguments yields the same result.

        Callers are responsible for any case normalization (for IAM action
        overlap the caller lowercases both patterns); this helper compares the
        patterns exactly as supplied.

    .PARAMETER PatternA
        The first glob pattern. May contain '*' and '?' wildcards.

    .PARAMETER PatternB
        The second glob pattern. May contain '*' and '?' wildcards.

    .OUTPUTS
        System.Boolean. True when the two patterns share at least one concrete
        string; otherwise false.

    .EXAMPLE
        Test-CHARGlobIntersect -PatternA 'ec2:getinstance' -PatternB 'ec2:get*'

        Returns $true -- 'ec2:getinstance' is a concrete string matched by both.

    .EXAMPLE
        Test-CHARGlobIntersect -PatternA 'ec2:getinstance' -PatternB 's3:get*'

        Returns $false -- the fixed 'ec2:' / 's3:' prefixes cannot overlap.

    .NOTES
        Generated by Kiro using Claude Opus 4.8, reviewed by ccharland
        Created: August 2026

        This is a PRIVATE helper and is intentionally not exported.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$PatternA,

        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$PatternB
    )

    $a = $PatternA
    $b = $PatternB
    $lenA = $a.Length
    $lenB = $b.Length

    # Dynamic-programming table for the Intersect(i, j) recurrence, sized
    # (lenA + 1) x (lenB + 1). Cell [i, j] holds whether the suffix of A from
    # index i can share a concrete tail with the suffix of B from index j.
    #
    # Every cell depends only on cells with a strictly greater i and/or j
    # (Intersect advances i, j, or both), so filling the table bottom-up -- i
    # descending, then j descending -- guarantees each dependency is already
    # computed. This resolves every sub-problem exactly once, giving the
    # O(len(A) * len(B)) bound with no recursion and no action-space enumeration.
    $dp = New-Object 'bool[,]' ($lenA + 1), ($lenB + 1)

    for ($i = $lenA; $i -ge 0; $i--) {
        for ($j = $lenB; $j -ge 0; $j--) {

            $aExhausted = ($i -ge $lenA)
            $bExhausted = ($j -ge $lenB)

            # Base case: both suffixes empty -- they trivially share the empty tail.
            if ($aExhausted -and $bExhausted) {
                $dp[$i, $j] = $true
                continue
            }

            # Base case: one suffix empty. The non-empty side can only collapse to
            # the empty string when all of its remaining characters are '*'
            # (zero-or-more), so scan the remainder for any non-'*' character.
            if ($aExhausted -or $bExhausted) {
                $remaining = if ($aExhausted) { $b } else { $a }
                $start = if ($aExhausted) { $j } else { $i }

                $allStars = $true
                for ($k = $start; $k -lt $remaining.Length; $k++) {
                    if ($remaining[$k] -ne '*') { $allStars = $false; break }
                }
                $dp[$i, $j] = $allStars
                continue
            }

            $charA = $a[$i]
            $charB = $b[$j]

            if ($charA -eq '*') {
                # '*' in A either matches the empty string (advance i) or absorbs
                # one character that B contributes (advance j, keeping the '*').
                $dp[$i, $j] = $dp[($i + 1), $j] -or $dp[$i, ($j + 1)]
                continue
            }

            if ($charB -eq '*') {
                # Symmetric rule for '*' in B.
                $dp[$i, $j] = $dp[$i, ($j + 1)] -or $dp[($i + 1), $j]
                continue
            }

            # Both current characters are literals or '?'. They are compatible when
            # equal or when either side is '?' (single-char wildcard). If they can
            # agree on one concrete character, advance both; otherwise no overlap.
            $compatible = ($charA -eq $charB) -or ($charA -eq '?') -or ($charB -eq '?')
            $dp[$i, $j] = $compatible -and $dp[($i + 1), ($j + 1)]
        }
    }

    return [bool]$dp[0, 0]
}

function Test-CHARIamActionOverlap {
    <#
    .SYNOPSIS
        Decides whether two IAM action patterns overlap in at least one concrete action.

    .DESCRIPTION
        Private helper implementing the bidirectional wildcard match for IAM action
        patterns (Req 3). Two IAM action patterns overlap when there exists at least
        one concrete action string matched by BOTH patterns, regardless of which side
        carries the wildcard.

        IAM action glob syntax uses '*' (zero-or-more characters) and '?' (exactly one
        character) as its only metacharacters. This helper:

            1. Lowercases both patterns, because the IAM service prefix and action name
               are compared case-insensitively (Req 3.6).
            2. Fast-paths a bare '*' on either side -- a lone star matches every action,
               so it overlaps anything.
            3. Delegates the general decision to Test-CHARGlobIntersect, which resolves
               overlap with the O(len(A) * len(B)) glob-intersection dynamic program.
               No concrete action space is enumerated and no regex is constructed.

        The relation is symmetric by construction: the underlying Intersect recurrence
        is symmetric, so Test-CHARIamActionOverlap A B == Test-CHARIamActionOverlap B A.

    .PARAMETER PatternA
        The first IAM action pattern (for example a Query_Action such as 'ec2:Describe*').
        May contain '*' and '?' wildcards.

    .PARAMETER PatternB
        The second IAM action pattern (for example a Policy_Action such as 'ec2:*').
        May contain '*' and '?' wildcards.

    .OUTPUTS
        System.Boolean. True when the two action patterns overlap in at least one
        concrete action; otherwise false.

    .EXAMPLE
        Test-CHARIamActionOverlap -PatternA 'ec2:GetInstance' -PatternB 'ec2:Get*'

        Returns $true -- 'ec2:GetInstance' is a concrete action matched by both.

    .EXAMPLE
        Test-CHARIamActionOverlap -PatternA 'ec2:GetInstance' -PatternB 's3:Get*'

        Returns $false -- the fixed 'ec2:' / 's3:' service prefixes cannot overlap.

    .NOTES
        Generated by Kiro using Claude Opus 4.8, reviewed by ccharland
        Created: August 2026

        This is a PRIVATE helper and is intentionally not exported.
    #>
    [CmdletBinding()]
    [OutputType([bool])]
    param(
        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$PatternA,

        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$PatternB
    )

    # IAM compares the service prefix and action name case-insensitively (Req 3.6), so
    # normalize both sides to lowercase before any comparison happens downstream.
    $a = $PatternA.ToLowerInvariant()
    $b = $PatternB.ToLowerInvariant()

    # Fast path: a bare '*' matches every action, so it overlaps anything (Req 3.4).
    # This also short-circuits the most common wildcard before the DP runs.
    if ($a -eq '*' -or $b -eq '*') {
        return $true
    }

    # Delegate the general case to the glob-intersection dynamic program. The helper is
    # symmetric, so the argument order does not affect the result (Req 3.1, 3.2).
    return [bool](Test-CHARGlobIntersect -PatternA $a -PatternB $b)
}

function Get-CHARPrincipalPolicyDocument {
    <#
    .SYNOPSIS
        Aggregates the managed and inline policy statements attached directly to an IAM principal.

    .DESCRIPTION
        Private helper that enumerates every managed policy attached directly to a
        single IAM principal (Role, User, or Group) and every inline policy embedded on
        that principal, then emits the normalized statements from each policy document.

        The helper performs exactly ONE hop of resolution on the named principal. It
        deliberately does NOT resolve group membership for users (Get-IAMGroupForUser is
        never called) and does NOT read permissions-boundary attributes (Req 2.3, 2.4),
        so every emitted statement traces back to a policy literally attached to or
        embedded on the named principal.

        The principal type selects the parallel Role/User/Group cmdlet family once, then
        that family drives both managed and inline enumeration:

            Managed: Get-IAM{Role|User|Group}AttachedPolicyList
                     -> Get-IAMPolicy      (read DefaultVersionId)
                     -> Get-IAMPolicyVersion (default-version document)
            Inline:  Get-IAM{Role|User|Group}PolicyList
                     -> Get-IAM{Role|User|Group}Policy (embedded document)

        Each retrieved document is URL-decoded with
        [System.Web.HttpUtility]::UrlDecode and parsed with ConvertFrom-Json, mirroring
        the existing Find-CHARDeletedPrincipalPolicy pattern (Req 2.5, 2.6). Every AWS
        call receives the caller's AWS common-parameter splat via @AwsParams.

        Per-policy resilience (Req 2.7): each document retrieval and parse is wrapped in
        try/catch with -ErrorAction Stop. When a single policy fails, the helper emits a
        Write-Warning naming the failing policy identifier and continues with the
        remaining policies, so one bad document never aborts the whole aggregation.

    .PARAMETER PrincipalType
        The principal classification: 'Role', 'User', or 'Group'. Selects the AWS cmdlet
        family used for both managed and inline enumeration.

    .PARAMETER PrincipalName
        The IAM principal name (path already stripped) whose policies are enumerated.

    .PARAMETER AwsParams
        The AWS common-parameter splat (hashtable) produced by New-AWSParamSplat in the
        caller. Forwarded verbatim to every AWS API call so connection context
        (Region, ProfileName, credentials, EndpointUrl) is honored.

    .OUTPUTS
        PSCustomObject, one per statement, with properties:
            PolicyName - The source policy's name
            PolicyType - 'Managed' or 'Inline'
            Effect     - The statement's Effect scalar ('Allow' | 'Deny')
            Action     - The statement's action pattern(s), normalized to an array
            Resource   - The statement's resource set, normalized to an array

    .EXAMPLE
        $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters
        Get-CHARPrincipalPolicyDocument -PrincipalType 'Role' -PrincipalName 'read-only' -AwsParams $awsParams

        Emits normalized statement records for every managed and inline policy on the
        'read-only' role.

    .NOTES
        Generated by Kiro using Claude Opus 4.8, reviewed by ccharland
        Created: August 2026

        This is a PRIVATE helper and is intentionally not exported.

    .LINK
        https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_managed-vs-inline.html
    #>
    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory)]
        [ValidateSet('Role', 'User', 'Group')]
        [string]$PrincipalType,

        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$PrincipalName,

        [Parameter(Mandatory)]
        [hashtable]$AwsParams
    )

    # Select the parallel Role/User/Group cmdlet family once from the principal type.
    # Each type exposes the same four operations under type-specific cmdlet names; the
    # managed-document pair (Get-IAMPolicy + Get-IAMPolicyVersion) is shared across all
    # three types. The -NameParam entry records the principal name parameter each family
    # uses (RoleName/UserName/GroupName) so calls can be splatted uniformly.
    $family = switch ($PrincipalType) {
        'Role' {
            @{
                NameParam        = 'RoleName'
                AttachedListCmd  = 'Get-IAMAttachedRolePolicyList'
                InlineListCmd    = 'Get-IAMRolePolicyList'
                InlinePolicyCmd  = 'Get-IAMRolePolicy'
            }
        }
        'User' {
            @{
                NameParam        = 'UserName'
                AttachedListCmd  = 'Get-IAMAttachedUserPolicyList'
                InlineListCmd    = 'Get-IAMUserPolicyList'
                InlinePolicyCmd  = 'Get-IAMUserPolicy'
            }
        }
        'Group' {
            @{
                NameParam        = 'GroupName'
                AttachedListCmd  = 'Get-IAMAttachedGroupPolicyList'
                InlineListCmd    = 'Get-IAMGroupPolicyList'
                InlinePolicyCmd  = 'Get-IAMGroupPolicy'
            }
        }
    }

    # The principal name parameter, splatted into every family cmdlet call so the same
    # invocation shape works for Role/User/Group without branching per call.
    $nameSplat = @{ $family.NameParam = $PrincipalName }

    # Normalizes one parsed policy document into per-statement records tagged with the
    # source policy name and type. Statement/Action/Resource are coerced to arrays
    # (AWS returns either a scalar or an array); Effect is read as a scalar (Req 6.3).
    $emitStatements = {
        param($ParsedDocument, $PolicyName, $PolicyType)

        foreach ($stmt in @($ParsedDocument.Statement)) {
            [PSCustomObject]@{
                PolicyName = $PolicyName
                PolicyType = $PolicyType
                Effect     = [string]$stmt.Effect
                Action     = @($stmt.Action)
                Resource   = @($stmt.Resource)
            }
        }
    }

    #
    # Managed policies attached directly to the principal (Req 2.1, 2.5).
    #
    Write-Verbose "Enumerating attached managed policies for $PrincipalType '$PrincipalName'"
    $attachedPolicies = & $family.AttachedListCmd @nameSplat @AwsParams

    foreach ($attached in $attachedPolicies) {
        # Per-policy resilience: any failure retrieving or parsing THIS managed policy
        # warns with the policy identifier and continues to the next policy (Req 2.7).
        try {
            # Resolve the managed policy to its default version, then fetch that
            # version's document. Both calls forward the AWS connection splat.
            $policy = Get-IAMPolicy -PolicyArn $attached.PolicyArn @AwsParams -ErrorAction Stop
            $policyVersion = Get-IAMPolicyVersion -PolicyArn $attached.PolicyArn -VersionId $policy.DefaultVersionId @AwsParams -ErrorAction Stop

            # AWS returns the managed document URL-encoded; decode then parse (Req 2.6).
            $decoded = [System.Web.HttpUtility]::UrlDecode($policyVersion.Document)
            $parsed = $decoded | ConvertFrom-Json -ErrorAction Stop
        }
        catch {
            Write-Warning "Failed to retrieve or parse managed policy '$($attached.PolicyName)' ($($attached.PolicyArn)): $_"
            continue
        }

        & $emitStatements $parsed $attached.PolicyName 'Managed'
    }

    #
    # Inline policies embedded directly on the principal (Req 2.2).
    #
    Write-Verbose "Enumerating inline policies for $PrincipalType '$PrincipalName'"
    $inlinePolicyNames = & $family.InlineListCmd @nameSplat @AwsParams

    foreach ($inlineName in $inlinePolicyNames) {
        # Per-policy resilience for inline documents, mirroring the managed path (Req 2.7).
        try {
            $inlinePolicy = & $family.InlinePolicyCmd @nameSplat -PolicyName $inlineName @AwsParams -ErrorAction Stop

            # Inline documents are also URL-encoded on the returned object (Req 2.6).
            $decoded = [System.Web.HttpUtility]::UrlDecode($inlinePolicy.PolicyDocument)
            $parsed = $decoded | ConvertFrom-Json -ErrorAction Stop
        }
        catch {
            Write-Warning "Failed to retrieve or parse inline policy '$inlineName' on $PrincipalType '$PrincipalName': $_"
            continue
        }

        & $emitStatements $parsed $inlineName 'Inline'
    }
}
