function Test-CHARIsWindows {
    <#
    .SYNOPSIS
        Returns whether the current platform is Windows.
    .DESCRIPTION
        Thin wrapper around the automatic $IsWindows variable to enable
        mocking in Pester tests (automatic variables are read-only).
    .NOTES
        Generated by Kiro using Auto, reviewed by ccharland
    #>
    return [bool]$IsWindows
}
