<#
.NOTES
    Generated by Copilot, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    Get-Module 'CloudWatch-Alarms' -All | Remove-Module -Force -ErrorAction SilentlyContinue
    Import-Module "$PSScriptRoot/../../../../src/CharlandCustomizations/Public/AWS/CloudWatch/CloudWatch-Alarms.psm1" -Force

    # Define stub cmdlets inside the module scope so Pester mocks and ParameterFilters work correctly
    InModuleScope 'CloudWatch-Alarms' {
        function script:Get-CWAlarm {
            param(
                [string]$StateValue,
                [string]$Region,
                [string]$ProfileName,
                [string]$AccessKey,
                [string]$SecretKey,
                [string]$SessionToken,
                $Credential,
                [string]$ProfileLocation,
                [string]$EndpointUrl
            )
            process { }
        }
    }
}

Describe 'Get-CHARCWAlarmInAlarmState' -Tag 'Unit' {

    It 'Returns alarms that are in the ALARM state' {
        Mock Get-CWAlarm {
            # Simulate what Get-CWAlarm -StateValue ALARM returns from AWS
            @([PSCustomObject]@{ AlarmName = 'firing-alarm'; StateValue = 'ALARM' })
        } -ModuleName 'CloudWatch-Alarms'

        $result = Get-CHARCWAlarmInAlarmState

        $result | Should -Not -BeNullOrEmpty
        $result.AlarmName | Should -Be 'firing-alarm'
    }

    It 'Returns an empty result when no alarms are in ALARM state' {
        Mock Get-CWAlarm { @() } -ModuleName 'CloudWatch-Alarms'

        $result = Get-CHARCWAlarmInAlarmState

        $result | Should -BeNullOrEmpty
    }

    It 'Returns multiple alarms when several are in ALARM state' {
        Mock Get-CWAlarm {
            @(
                [PSCustomObject]@{ AlarmName = 'alarm-one'; StateValue = 'ALARM' }
                [PSCustomObject]@{ AlarmName = 'alarm-two'; StateValue = 'ALARM' }
            )
        } -ModuleName 'CloudWatch-Alarms'

        $result = Get-CHARCWAlarmInAlarmState

        $result.Count | Should -Be 2
    }

    It 'Calls Get-CWAlarm with -StateValue ALARM' {
        Mock Get-CWAlarm { @() } -ModuleName 'CloudWatch-Alarms'

        Get-CHARCWAlarmInAlarmState

        Should -Invoke Get-CWAlarm -ModuleName 'CloudWatch-Alarms' -Times 1 -ParameterFilter {
            $StateValue -eq 'ALARM'
        }
    }

    It 'Passes AWS common parameters through to Get-CWAlarm' {
        Mock New-AWSParamSplat { @{ Region = $BoundParameters.Region } } -ModuleName 'CloudWatch-Alarms'
        Mock Get-CWAlarm { @() } -ModuleName 'CloudWatch-Alarms'

        Get-CHARCWAlarmInAlarmState -Region 'eu-west-1'

        Should -Invoke Get-CWAlarm -ModuleName 'CloudWatch-Alarms' -Times 1 -ParameterFilter {
            $Region -eq 'eu-west-1' -and $StateValue -eq 'ALARM'
        }
    }
}
