<#
.SYNOPSIS
    CloudWatch Alarm audit helper functions.

.DESCRIPTION
    This module provides functions for auditing CloudWatch alarms, including
    finding alarms with invalid actions, alarms in the ALARM state, and alarms
    with no actions defined.

.NOTES
    Generated by Copilot, reviewed by ccharland
#>
Write-Verbose "Loading CloudWatch-Alarms.psm1"

. "$PSScriptRoot/../../../Private/New-AWSParamSplat.ps1"

# ================================================================================================
# Find-CHARCWAlarmInvalidAction
# ================================================================================================

function Find-CHARCWAlarmInvalidAction {
    <#
    .SYNOPSIS
        Finds CloudWatch alarms that have invalid or non-existent action ARNs.

    .DESCRIPTION
        Retrieves all CloudWatch alarms and inspects their AlarmActions, OKActions, and
        InsufficientDataActions arrays. For each SNS action ARN the function verifies that
        the topic still exists in the account. Non-SNS ARNs are validated against the
        standard ARN format. Alarms that contain at least one unresolvable or malformed
        action ARN are returned together with the list of offending ARNs.

    .PARAMETER Region
        AWS region. If not specified, uses your default Region.

    .PARAMETER ProfileName
        AWS profile name. Optional.

    .PARAMETER AccessKey
        AWS access key. Optional.

    .PARAMETER SecretKey
        AWS secret key. Optional.

    .PARAMETER SessionToken
        AWS session token for temporary credentials. Optional.

    .PARAMETER Credential
        Pre-built AWS credential object. Optional.

    .PARAMETER ProfileLocation
        Custom credential file path. Optional.

    .PARAMETER EndpointUrl
        Custom AWS service endpoint URL. Optional.

    .INPUTS
        None. This function does not accept pipeline input.

    .OUTPUTS
        System.Management.Automation.PSCustomObject
        Returns objects with the following properties:
            AlarmName      - The name of the alarm.
            AlarmArn       - The ARN of the alarm.
            InvalidActions - Array of action ARNs that are invalid or unresolvable.

    .EXAMPLE
        Find-CHARCWAlarmInvalidAction -Region us-east-1

        Lists all CloudWatch alarms in us-east-1 that have at least one invalid action ARN.

    .EXAMPLE
        Find-CHARCWAlarmInvalidAction -ProfileName prod | Select-Object AlarmName, InvalidActions

        Returns alarm names and their invalid actions for the prod profile.

    .NOTES
        Generated by Copilot, reviewed by ccharland
    #>
    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSAvoidUsingPlainTextForPassword', 'Credential',
        Justification = 'Credential is an AWS SDK credential object, not a PSCredential.')]
    param(
        # AWS common parameters
        [Parameter()]
        [string]$Region,

        [Parameter()]
        [string]$ProfileName,

        [Parameter()]
        [string]$AccessKey,

        [Parameter()]
        [string]$SecretKey,

        [Parameter()]
        [string]$SessionToken,

        [Parameter()]
        [object]$Credential,

        [Parameter()]
        [string]$ProfileLocation,

        [Parameter()]
        [string]$EndpointUrl
    )

    process {
        $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters

        $alarms = @(Get-CWAlarm @awsParams)
        $snsTopics = @(Get-SNSTopic @awsParams | Select-Object -ExpandProperty TopicArn)

        # Regex for a minimally valid AWS ARN: arn:partition:service:region:account:resource
        $arnRegex = '^arn:[a-z][a-z0-9-]*:[a-z0-9-]+:[a-z0-9-]*:[0-9]*:.+'

        foreach ($alarm in $alarms) {
            $allActions = @(
                $alarm.AlarmActions
                $alarm.OKActions
                $alarm.InsufficientDataActions
            ) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) }

            $invalidActions = foreach ($action in $allActions) {
                if ($action -match '^arn:aws[a-z0-9-]*:sns:') {
                    # SNS ARN — verify the topic exists
                    if ($action -notin $snsTopics) {
                        $action
                    }
                }
                elseif ($action -notmatch $arnRegex) {
                    # Non-SNS ARN that fails basic format validation
                    $action
                }
            }

            if ($invalidActions) {
                [PSCustomObject]@{
                    AlarmName      = $alarm.AlarmName
                    AlarmArn       = $alarm.AlarmArn
                    InvalidActions = @($invalidActions)
                }
            }
        }
    }
}

# ================================================================================================
# Get-CHARCWAlarmInAlarmState
# ================================================================================================

function Get-CHARCWAlarmInAlarmState {
    <#
    .SYNOPSIS
        Returns all CloudWatch alarms currently in the ALARM state.

    .DESCRIPTION
        Calls Get-CWAlarm with -StateValue ALARM and returns the matching alarm objects.
        Use this to quickly identify alarms that are actively firing and may require
        investigation or remediation.

    .PARAMETER Region
        AWS region. If not specified, uses your default Region.

    .PARAMETER ProfileName
        AWS profile name. Optional.

    .PARAMETER AccessKey
        AWS access key. Optional.

    .PARAMETER SecretKey
        AWS secret key. Optional.

    .PARAMETER SessionToken
        AWS session token for temporary credentials. Optional.

    .PARAMETER Credential
        Pre-built AWS credential object. Optional.

    .PARAMETER ProfileLocation
        Custom credential file path. Optional.

    .PARAMETER EndpointUrl
        Custom AWS service endpoint URL. Optional.

    .INPUTS
        None. This function does not accept pipeline input.

    .OUTPUTS
        Amazon.CloudWatch.Model.MetricAlarm
        Returns the native CloudWatch alarm objects for alarms in the ALARM state.

    .EXAMPLE
        Get-CHARCWAlarmInAlarmState -Region us-east-1

        Lists all CloudWatch alarms currently in the ALARM state in us-east-1.

    .EXAMPLE
        Get-CHARCWAlarmInAlarmState -ProfileName prod | Select-Object AlarmName, StateReason

        Returns alarm names and reasons for the prod profile.

    .NOTES
        Generated by Copilot, reviewed by ccharland
    #>
    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSAvoidUsingPlainTextForPassword', 'Credential',
        Justification = 'Credential is an AWS SDK credential object, not a PSCredential.')]
    param(
        # AWS common parameters
        [Parameter()]
        [string]$Region,

        [Parameter()]
        [string]$ProfileName,

        [Parameter()]
        [string]$AccessKey,

        [Parameter()]
        [string]$SecretKey,

        [Parameter()]
        [string]$SessionToken,

        [Parameter()]
        [object]$Credential,

        [Parameter()]
        [string]$ProfileLocation,

        [Parameter()]
        [string]$EndpointUrl
    )

    process {
        $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters
        Get-CWAlarm -StateValue ALARM @awsParams
    }
}

# ================================================================================================
# Find-CHARCWAlarmNoAction
# ================================================================================================

function Find-CHARCWAlarmNoAction {
    <#
    .SYNOPSIS
        Finds CloudWatch alarms that have no actions defined.

    .DESCRIPTION
        Retrieves all CloudWatch alarms and returns those where AlarmActions, OKActions,
        and InsufficientDataActions are all empty. Alarms with no actions configured will
        never notify anyone or trigger automation when they fire, which is typically a
        misconfiguration.

    .PARAMETER Region
        AWS region. If not specified, uses your default Region.

    .PARAMETER ProfileName
        AWS profile name. Optional.

    .PARAMETER AccessKey
        AWS access key. Optional.

    .PARAMETER SecretKey
        AWS secret key. Optional.

    .PARAMETER SessionToken
        AWS session token for temporary credentials. Optional.

    .PARAMETER Credential
        Pre-built AWS credential object. Optional.

    .PARAMETER ProfileLocation
        Custom credential file path. Optional.

    .PARAMETER EndpointUrl
        Custom AWS service endpoint URL. Optional.

    .INPUTS
        None. This function does not accept pipeline input.

    .OUTPUTS
        Amazon.CloudWatch.Model.MetricAlarm
        Returns the native CloudWatch alarm objects for alarms with no actions.

    .EXAMPLE
        Find-CHARCWAlarmNoAction -Region us-east-1

        Lists all CloudWatch alarms in us-east-1 that have no actions configured in any state.

    .EXAMPLE
        Find-CHARCWAlarmNoAction -ProfileName prod | Select-Object AlarmName

        Returns alarm names with no actions for the prod profile.

    .NOTES
        Generated by Copilot, reviewed by ccharland
    #>
    [CmdletBinding()]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute(
        'PSAvoidUsingPlainTextForPassword', 'Credential',
        Justification = 'Credential is an AWS SDK credential object, not a PSCredential.')]
    param(
        # AWS common parameters
        [Parameter()]
        [string]$Region,

        [Parameter()]
        [string]$ProfileName,

        [Parameter()]
        [string]$AccessKey,

        [Parameter()]
        [string]$SecretKey,

        [Parameter()]
        [string]$SessionToken,

        [Parameter()]
        [object]$Credential,

        [Parameter()]
        [string]$ProfileLocation,

        [Parameter()]
        [string]$EndpointUrl
    )

    process {
        $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters

        Get-CWAlarm @awsParams | Where-Object {
            $_.AlarmActions.Count -eq 0 -and
            $_.OKActions.Count -eq 0 -and
            $_.InsufficientDataActions.Count -eq 0
        }
    }
}

Export-ModuleMember -Function 'Find-CHARCWAlarmInvalidAction', 'Find-CHARCWAlarmNoAction', 'Get-CHARCWAlarmInAlarmState'
