<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Public/Clear-CCAuthenticodeSignature.ps1"
}

Describe 'Clear-CCAuthenticodeSignature' -Tag 'Unit' {

    Context 'Happy path' {

        It 'Removes signature block and preserves content before marker' {
            # Arrange
            $scriptContent = @"
function Get-Something {
    Write-Output 'hello'
}