<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Private/New-AWSParamSplat.ps1"
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Public/Invoke-CHARScriptMultiRegionProfile.ps1"
}

Describe 'Invoke-CHARScriptMultiRegionProfile' -Tag 'Unit' {

    BeforeEach {
        # Default mocks for AWS cmdlets
        Mock Get-STSCallerIdentity {
            [PSCustomObject]@{ Account = '123456789012'; Arn = 'arn:aws:iam::123456789012:user/test' }
        }
        Mock Set-AWSCredential {}
        Mock Get-AWSCredential { @() } -ParameterFilter { $ListProfileDetail -eq $true }
        Mock Get-DefaultAWSRegion { @{ Region = 'us-east-1' } }
        Mock Write-Progress {}
    }

    Context 'N profiles × M regions execution count (Req 2.8)' {

        It 'Executes ScriptBlock N×M times for 2 profiles and 3 regions' {
            $script:callCount = 0
            $sb = { $script:callCount++ }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'profile1', 'profile2' `
                -Region 'us-east-1', 'us-west-2', 'eu-west-1' `
                -ScriptBlock $sb

            $script:callCount | Should -Be 6
        }

        It 'Executes ScriptBlock N×M times for 3 profiles and 2 regions' {
            $script:callCount = 0
            $sb = { $script:callCount++ }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'dev', 'staging', 'prod' `
                -Region 'us-east-1', 'eu-west-1' `
                -ScriptBlock $sb

            $script:callCount | Should -Be 6
        }

        It 'Executes ScriptBlock once for 1 profile and 1 region' {
            $script:callCount = 0
            $sb = { $script:callCount++ }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'single' `
                -Region 'us-east-1' `
                -ScriptBlock $sb

            $script:callCount | Should -Be 1
        }
    }

    Context 'IncludeAccountId enrichment (Req 2.9)' {

        It 'Adds AccountId property matching Get-STSCallerIdentity account' {
            Mock Get-STSCallerIdentity {
                [PSCustomObject]@{ Account = '987654321098'; Arn = 'arn:aws:iam::987654321098:user/test' }
            }

            $sb = { [PSCustomObject]@{ Name = 'TestResource' } }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb `
                -IncludeAccountId

            $results | Should -Not -BeNullOrEmpty
            $results.AccountId | Should -Be '987654321098'
        }

        It 'Each output object gets the correct AccountId for its profile' {
            # First profile returns one account, second returns another
            Mock Get-STSCallerIdentity {
                if ($ProfileName -eq 'dev') {
                    [PSCustomObject]@{ Account = '111111111111'; Arn = 'arn:aws:iam::111111111111:user/test' }
                }
                else {
                    [PSCustomObject]@{ Account = '222222222222'; Arn = 'arn:aws:iam::222222222222:user/test' }
                }
            }

            $sb = { [PSCustomObject]@{ Name = 'Resource' } }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'dev', 'prod' `
                -Region 'us-east-1' `
                -ScriptBlock $sb `
                -IncludeAccountId

            $results | Should -HaveCount 2
            $results[0].AccountId | Should -Be '111111111111'
            $results[1].AccountId | Should -Be '222222222222'
        }
    }

    Context 'AWS cmdlet exception writes warning (Req 8.1)' {

        It 'Writes warning containing profile, region, and exception message when ScriptBlock throws' {
            $sb = { throw 'Access Denied' }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'failprofile' `
                -Region 'us-west-2' `
                -ScriptBlock $sb `
                -WarningVariable capturedWarnings 3>&1 | Out-Null

            $capturedWarnings | Should -Not -BeNullOrEmpty
            $warningText = $capturedWarnings | Out-String
            $warningText | Should -BeLike '*failprofile*'
            $warningText | Should -BeLike '*us-west-2*'
            $warningText | Should -BeLike '*Access Denied*'
        }
    }

    Context 'No profile configured writes non-terminating error (Req 8.2)' {

        It 'Writes error when no ProfileName specified and no default profile found' {
            Mock Get-AWSCredential { @() } -ParameterFilter { $ListProfileDetail -eq $true }

            # Temporarily clear StoredAWSCredentials at all accessible scopes
            $originalStored = $null
            $hadVariable = Test-Path variable:StoredAWSCredentials
            if ($hadVariable) {
                $originalStored = $StoredAWSCredentials
            }
            # Clear from global scope where AWS.Tools sets it
            Set-Variable -Name StoredAWSCredentials -Value $null -Scope Global -Force -ErrorAction SilentlyContinue

            $sb = { [PSCustomObject]@{ Name = 'test' } }

            try {
                Invoke-CHARScriptMultiRegionProfile -Region 'us-east-1' `
                    -ScriptBlock $sb `
                    -ErrorVariable capturedErrors `
                    -ErrorAction SilentlyContinue 2>&1 | Out-Null

                $errorMessages = $capturedErrors | Out-String
                $errorMessages | Should -BeLike '*No ProfileName specified*'
            }
            finally {
                # Restore original value
                if ($hadVariable) {
                    Set-Variable -Name StoredAWSCredentials -Value $originalStored -Scope Global -Force -ErrorAction SilentlyContinue
                }
                else {
                    Remove-Variable StoredAWSCredentials -Scope Global -ErrorAction SilentlyContinue
                }
            }
        }
    }

    Context 'Auth failure for one profile still processes subsequent profiles (Req 8.3)' {

        It 'Continues processing after authentication failure for first profile' {
            # First profile fails auth, second succeeds
            Mock Get-STSCallerIdentity {
                if ($ProfileName -eq 'badprofile') {
                    throw 'Invalid credentials'
                }
                [PSCustomObject]@{ Account = '123456789012'; Arn = 'arn:aws:iam::123456789012:user/test' }
            }

            $script:callCount = 0
            $sb = { $script:callCount++; [PSCustomObject]@{ Name = 'Result' } }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'badprofile', 'goodprofile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb `
                -WarningVariable capturedWarnings 3>&1 | Out-Null

            # ScriptBlock should execute once (only for goodprofile)
            $script:callCount | Should -Be 1

            # Warning should mention the failing profile
            $warningText = $capturedWarnings | Out-String
            $warningText | Should -BeLike '*badprofile*'
            $warningText | Should -BeLike '*unable to authenticate*'
        }

        It 'Processes all remaining profiles after one fails authentication' {
            Mock Get-STSCallerIdentity {
                if ($ProfileName -eq 'middle') {
                    throw 'Token expired'
                }
                [PSCustomObject]@{ Account = '123456789012'; Arn = 'arn:aws:iam::123456789012:user/test' }
            }

            $script:callCount = 0
            $sb = { $script:callCount++ }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'first', 'middle', 'last' `
                -Region 'us-east-1' `
                -ScriptBlock $sb 3>&1 | Out-Null

            # first and last should execute, middle should be skipped
            $script:callCount | Should -Be 2
        }

        It 'Aborts execution when region configuration is missing' {
            Mock Get-STSCallerIdentity {
                throw 'No RegionEndpoint or ServiceURL configured'
            }

            $script:callCount = 0
            $sb = { $script:callCount++ }

            {
                Invoke-CHARScriptMultiRegionProfile -ProfileName 'first', 'second' `
                    -Region 'us-east-1' `
                    -ScriptBlock $sb
            } | Should -Throw

            $script:callCount | Should -Be 0
        }

        It 'Aborts execution when DefaultAWSRegion is not configured' {
            Mock Get-STSCallerIdentity {
                throw 'DefaultAWSRegion is not configured for this session'
            }

            $script:callCount = 0
            $sb = { $script:callCount++; [PSCustomObject]@{ Name = 'result' } }

            {
                Invoke-CHARScriptMultiRegionProfile -ProfileName 'first' `
                    -Region 'us-east-1' `
                    -ScriptBlock $sb
            } | Should -Throw

            $script:callCount | Should -Be 0
        }
    }

    Context 'Property: N×M execution count' {
        # Feature: pester-test-coverage, Property 2: N×M execution count
        # **Validates: Requirements 2.8**
        It 'Executes ScriptBlock exactly N×M times for random profile/region combinations' {
            $regionPool = @('us-east-1', 'us-west-2', 'eu-west-1', 'ap-southeast-1')

            foreach ($i in 1..100) {
                $N = Get-Random -Minimum 1 -Maximum 6  # 1-5 profiles
                $M = Get-Random -Minimum 1 -Maximum 5  # 1-4 regions

                $profiles = 1..$N | ForEach-Object { "profile$_" }
                $regions = $regionPool | Get-Random -Count $M

                $script:callCount = 0
                $sb = { $script:callCount++ }

                Invoke-CHARScriptMultiRegionProfile -ProfileName $profiles `
                    -Region $regions `
                    -ScriptBlock $sb

                $script:callCount | Should -Be ($N * $M) -Because "iteration $i with $N profiles × $M regions should equal $($N * $M)"
            }
        }
    }

    Context 'Property: output enrichment with AccountId' {
        # Feature: pester-test-coverage, Property 3: output enrichment
        # **Validates: Requirements 2.9**
        It 'Every output object has AccountId matching mocked STS identity for random combinations' {
            $regionPool = @('us-east-1', 'us-west-2', 'eu-west-1', 'ap-southeast-1')
            $expectedAccountId = '123456789012'

            foreach ($i in 1..100) {
                $N = Get-Random -Minimum 1 -Maximum 4  # 1-3 profiles
                $M = Get-Random -Minimum 1 -Maximum 4  # 1-3 regions

                $profiles = 1..$N | ForEach-Object { "profile$_" }
                $regions = $regionPool | Get-Random -Count $M

                $sb = { [PSCustomObject]@{ Name = "Resource-$([guid]::NewGuid().ToString().Substring(0,8))" } }

                $results = Invoke-CHARScriptMultiRegionProfile -ProfileName $profiles `
                    -Region $regions `
                    -ScriptBlock $sb `
                    -IncludeAccountId

                $results | Should -HaveCount ($N * $M) -Because "iteration $i should produce $($N * $M) results"
                foreach ($result in $results) {
                    $result.AccountId | Should -Be $expectedAccountId -Because "iteration ${i}: all objects should have AccountId from mocked STS"
                }
            }
        }
    }

    Context 'Sets StoredAWSRegion and StoredAWSCredentials during ScriptBlock execution' {

        It 'ScriptBlock sees StoredAWSRegion set to the current iteration region' {
            $sb = { [PSCustomObject]@{ SeenRegion = $global:StoredAWSRegion } }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'eu-west-1' `
                -ScriptBlock $sb

            $results.SeenRegion | Should -Be 'eu-west-1'
        }

        It 'ScriptBlock sees StoredAWSCredentials set to the current profile name' {
            $sb = { [PSCustomObject]@{ SeenCreds = $global:StoredAWSCredentials } }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'prod-account' `
                -Region 'us-east-1' `
                -ScriptBlock $sb

            $results.SeenCreds | Should -Be 'prod-account'
        }

        It 'Restores original StoredAWSRegion after execution completes' {
            $global:StoredAWSRegion = 'ap-southeast-1'

            $sb = { [PSCustomObject]@{ Done = $true } }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'testprofile' `
                -Region 'us-west-2' `
                -ScriptBlock $sb | Out-Null

            $global:StoredAWSRegion | Should -Be 'ap-southeast-1'
        }

        It 'Restores original StoredAWSCredentials after execution completes' {
            $global:StoredAWSCredentials = 'original-profile'

            $sb = { [PSCustomObject]@{ Done = $true } }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'different-profile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb | Out-Null

            $global:StoredAWSCredentials | Should -Be 'original-profile'
        }

        It 'Restores StoredAWSRegion even when ScriptBlock throws' {
            $global:StoredAWSRegion = 'original-region'

            $sb = { throw 'something broke' }

            Invoke-CHARScriptMultiRegionProfile -ProfileName 'failprofile' `
                -Region 'eu-central-1' `
                -ScriptBlock $sb `
                -WarningVariable w 3>&1 | Out-Null

            $global:StoredAWSRegion | Should -Be 'original-region'
        }

        It 'Updates StoredAWSRegion per region iteration' {
            $sb = { [PSCustomObject]@{ SeenRegion = $global:StoredAWSRegion } }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'us-east-1', 'eu-west-1' `
                -ScriptBlock $sb

            $results | Should -HaveCount 2
            $results[0].SeenRegion | Should -Be 'us-east-1'
            $results[1].SeenRegion | Should -Be 'eu-west-1'
        }
    }

    Context 'Wraps string and primitive results in Value property' {

        It 'Wraps string results with a Value property' {
            $sb = { 'https://sqs.us-east-1.amazonaws.com/123456789012/my-queue' }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb

            $results | Should -Not -BeNullOrEmpty
            $results.Value | Should -Be 'https://sqs.us-east-1.amazonaws.com/123456789012/my-queue'
        }

        It 'Does not produce a Length property for string results' {
            $sb = { 'some-string-value' }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb

            $results.PSObject.Properties.Name | Should -Contain 'Value'
            $results.PSObject.Properties.Name | Should -Not -Contain 'Length'
        }

        It 'Enriches string results with AccountId and Region when switches specified' {
            $sb = { 'queue-url-1'; 'queue-url-2' }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb `
                -IncludeAccountId -IncludeRegion

            $results | Should -HaveCount 2
            $results[0].Value | Should -Be 'queue-url-1'
            $results[0].AccountId | Should -Be '123456789012'
            $results[0].Region | Should -Be 'us-east-1'
            $results[1].Value | Should -Be 'queue-url-2'
        }

        It 'Wraps integer results with a Value property' {
            $sb = { 42 }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb

            $results.Value | Should -Be 42
        }

        It 'Does not wrap PSCustomObject results — preserves original properties' {
            $sb = { [PSCustomObject]@{ Name = 'MyFunc'; Runtime = 'dotnet6' } }

            $results = Invoke-CHARScriptMultiRegionProfile -ProfileName 'myprofile' `
                -Region 'us-east-1' `
                -ScriptBlock $sb

            $results.Name | Should -Be 'MyFunc'
            $results.Runtime | Should -Be 'dotnet6'
            $results.PSObject.Properties.Name | Should -Not -Contain 'Value'
        }
    }

    Context 'OutputSubTemplate parameter set' {

        It 'Returns a non-empty string without requiring ScriptBlock' {
            $output = Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate

            $output | Should -Not -BeNullOrEmpty
            $output | Should -BeOfType [string]
        }

        It 'Output contains a ScriptBlock opening brace' {
            $output = Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate

            $output | Should -BeLike '{*'
        }

        It 'Output contains CmdletBinding attribute' {
            $output = Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate

            $output | Should -BeLike '*[CmdletBinding()]*'
        }

        It 'Output contains param block' {
            $output = Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate

            $output | Should -BeLike '*param(*'
        }

        It 'Output contains begin, process, and end blocks' {
            $output = Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate

            $output | Should -BeLike '*begin {*'
            $output | Should -BeLike '*process {*'
            $output | Should -BeLike '*end {*'
        }

        It 'Output is a valid ScriptBlock that can be parsed' {
            $output = Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate

            $sb = [scriptblock]::Create($output)
            $sb | Should -Not -BeNullOrEmpty
            $sb | Should -BeOfType [scriptblock]
        }

        It 'Does not invoke any AWS cmdlets when OutputSubTemplate is used' {
            $script:stsCalled = $false
            Mock Get-STSCallerIdentity { $script:stsCalled = $true }

            Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate | Out-Null

            $script:stsCalled | Should -BeFalse
        }
    }

    Context 'Parameter set validation' {

        It 'Rejects -OutputSubTemplate combined with -ScriptBlock' {
            {
                Invoke-CHARScriptMultiRegionProfile -OutputSubTemplate `
                    -ScriptBlock { Get-STSCallerIdentity }
            } | Should -Throw -ErrorId 'AmbiguousParameterSet*'
        }

        It 'Execute parameter set requires ScriptBlock as mandatory' {
            $cmd = Get-Command Invoke-CHARScriptMultiRegionProfile
            $sbParam = $cmd.Parameters['ScriptBlock']

            $executeAttrs = $sbParam.Attributes |
                Where-Object { $_ -is [System.Management.Automation.ParameterAttribute] -and $_.ParameterSetName -eq 'Execute' }

            $executeAttrs | Should -Not -BeNullOrEmpty
            $executeAttrs.Mandatory | Should -BeTrue
        }

        It 'SubTemplate parameter set does not include ScriptBlock' {
            $cmd = Get-Command Invoke-CHARScriptMultiRegionProfile
            $sbParam = $cmd.Parameters['ScriptBlock']

            $subTemplateAttrs = $sbParam.Attributes |
                Where-Object { $_ -is [System.Management.Automation.ParameterAttribute] -and $_.ParameterSetName -eq 'SubTemplate' }

            $subTemplateAttrs | Should -BeNullOrEmpty
        }

        It 'Default parameter set is Execute' {
            $cmd = Get-Command Invoke-CHARScriptMultiRegionProfile
            $cmd.DefaultParameterSet | Should -Be 'Execute'
        }
    }
}
