<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    # Override Set-AuthenticodeSignature with a loose-typed function so that
    # PSCustomObject mocks for Certificate don't trigger X509Certificate2 casting.
    # This must be defined before the SUT is loaded and before mocks are set up.
    function global:Set-AuthenticodeSignature {
        param($FilePath, $TimestampServer, $Certificate)
    }

    . "$PSScriptRoot/../../../src/CharlandCustomizations/Public/Set-CHARAuthenticodeSignature.ps1"
    # Force the script-scoped variable used by the SUT to $true for testing on non-Windows
    $script:CHARIsWindows = $true
}

AfterAll {
    Remove-Item "function:global:Set-AuthenticodeSignature" -ErrorAction SilentlyContinue
}

Describe 'Set-CHARAuthenticodeSignature' -Tag 'Unit' {

    BeforeAll {
        # Mock Set-AuthenticodeSignature to prevent actual signing
        Mock Set-AuthenticodeSignature {
            [PSCustomObject]@{ Status = 'Valid'; Path = $FilePath }
        }
    }

    Context 'No valid certificate' {

        It 'Throws terminating error when no valid code-signing certificate is found' {
            # Arrange - mock cert store to return nothing so auto-detection fails
            Mock Get-ChildItem { @() } -ParameterFilter { $Path -like 'cert:\*' }

            # Act & Assert
            { Set-CHARAuthenticodeSignature -MyCert $null -Path 'TestDrive:\test.ps1' } |
                Should -Throw '*No valid codesign certificate found*'
        }
    }

    Context 'Digicert issuer timestamp server selection' {

        It 'Sets timestamp server to http://timestamp.digicert.com for Digicert issuer' {
            # Arrange
            $mockCert = [PSCustomObject]@{
                Issuer        = 'CN=Digicert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US'
                NotAfter      = (Get-Date).AddYears(1)
                HasPrivateKey = $true
                Thumbprint    = 'AABBCCDD1234567890'
            }
            Set-Content -Path 'TestDrive:\script.ps1' -Value 'Write-Output "hello"'

            # Act
            Set-CHARAuthenticodeSignature -MyCert $mockCert -Path 'TestDrive:\script.ps1'

            # Assert
            Should -Invoke Set-AuthenticodeSignature -Times 1 -ParameterFilter {
                $TimestampServer -eq 'http://timestamp.digicert.com'
            }
        }
    }

    Context 'Sectigo issuer timestamp server selection' {

        It 'Sets timestamp server to http://timestamp.sectigo.com for Sectigo issuer' {
            # Arrange
            $mockCert = [PSCustomObject]@{
                Issuer        = 'CN=Sectigo RSA Code Signing CA, O=Sectigo Limited, L=Salford'
                NotAfter      = (Get-Date).AddYears(1)
                HasPrivateKey = $true
                Thumbprint    = 'EEFF112233445566'
            }
            Set-Content -Path 'TestDrive:\script.ps1' -Value 'Write-Output "hello"'

            # Act
            Set-CHARAuthenticodeSignature -MyCert $mockCert -Path 'TestDrive:\script.ps1'

            # Assert
            Should -Invoke Set-AuthenticodeSignature -Times 1 -ParameterFilter {
                $TimestampServer -eq 'http://timestamp.sectigo.com'
            }
        }
    }

    Context 'Alias compatibility' {

        It 'Alias Set-CHARFileSignature resolves to Set-CHARAuthenticodeSignature' {
            (Get-Alias Set-CHARFileSignature).Definition | Should -Be 'Set-CHARAuthenticodeSignature'
        }
    }

    Context 'Windows requirement' {

        It 'Throws when not running on Windows' {
            $script:CHARIsWindows = $false
            { Set-CHARAuthenticodeSignature -MyCert ([PSCustomObject]@{ Issuer='CN=Digicert'; NotAfter=(Get-Date).AddYears(1); HasPrivateKey=$true }) -Path 'TestDrive:\script.ps1' } |
                Should -Throw '*only supported on Windows systems*'
            $script:CHARIsWindows = $true
        }
    }

    Context 'Unknown issuer without TimeStampServer' {

        It 'Throws terminating error when issuer is unknown and no TimeStampServer provided' {
            # Arrange
            $mockCert = [PSCustomObject]@{
                Issuer        = 'CN=Unknown CA, O=Unknown Org, C=US'
                NotAfter      = (Get-Date).AddYears(1)
                HasPrivateKey = $true
                Thumbprint    = '9988776655443322'
            }

            # Act & Assert
            { Set-CHARAuthenticodeSignature -MyCert $mockCert -Path 'TestDrive:\script.ps1' } |
                Should -Throw '*No Timestamp server could be set, aborting.*'
        }
    }
}
