<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Public/Update-Powershell7.ps1"

    # Create a wrapper function for the winget executable so Pester can mock it
    function winget { }
}

Describe 'Update-Powershell7' -Tag 'Unit' {

    Context 'Windows with winget available' {

        BeforeAll {
            # Store original OS value
            $script:OriginalOS = $PSVersionTable.OS
        }

        AfterAll {
            # Restore original OS value
            $PSVersionTable.OS = $script:OriginalOS
        }

        It 'Invokes winget upgrade Microsoft.PowerShell with --accept-source-agreements' {
            # Arrange - simulate Windows platform
            $PSVersionTable.OS = 'Microsoft Windows 10.0.22631'

            Mock Get-Command {
                [PSCustomObject]@{
                    Name   = 'winget'
                    Source = 'C:\Users\test\AppData\Local\Microsoft\WindowsApps\winget.exe'
                }
            } -ParameterFilter { $Name -eq 'winget' }

            Mock winget { }

            # Act
            Update-Powershell7

            # Assert - verify winget was called with the correct arguments
            Should -Invoke winget -Times 1 -Exactly -ParameterFilter {
                "$args" -match 'upgrade' -and
                "$args" -match 'Microsoft.PowerShell' -and
                "$args" -match '--accept-source-agreements'
            }
        }
    }
}
