<#
.SYNOPSIS
    Validates branch/path separation for repository changes.
.DESCRIPTION
    Enforces domain-based ownership of test files alongside source and infrastructure.

    Infrastructure branches (workflow, infra, ci) own:
      - .github/, .kiro/, .vscode/, Scripts/, tests/scripts/

    Normal code branches (feature, bugfix, hotfix, etc.) own:
      - src/, tests/src/

    Each branch type is blocked from modifying the other's test directory,
    keeping infrastructure and source changes in separate PRs.
.PARAMETER BranchName
    Branch name to classify.
.PARAMETER ChangedPath
    Changed repository-relative paths to validate.
.EXAMPLE
    ./Scripts/Test-BranchPathPolicy.ps1 -BranchName 'feature/add-audit' -ChangedPath @('src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.psm1', 'tests/src/CharlandCustomizations/Public/AWS/Audit/Audit-AWSAccount.Tests.ps1')
    # Passes: source and its matching tests are allowed on a normal code branch
.EXAMPLE
    ./Scripts/Test-BranchPathPolicy.ps1 -BranchName 'feature/add-audit' -ChangedPath @('.github/workflows/publish.yml')
    # Fails: workflow changes are not allowed on a normal code branch
.EXAMPLE
    ./Scripts/Test-BranchPathPolicy.ps1 -BranchName 'feature/add-audit' -ChangedPath @('tests/scripts/Build-Module.Tests.ps1')
    # Fails: infrastructure test changes are not allowed on a normal code branch
.EXAMPLE
    ./Scripts/Test-BranchPathPolicy.ps1 -BranchName 'ci/update-workflows' -ChangedPath @('.github/workflows/publish.yml', 'tests/scripts/Build-Module.Tests.ps1')
    # Passes: workflow and infrastructure tests are allowed on a CI branch
.EXAMPLE
    ./Scripts/Test-BranchPathPolicy.ps1 -BranchName 'infra/pipeline-fixes' -ChangedPath @('src/CharlandCustomizations/Public/Get-Something.ps1')
    # Fails: source changes are not allowed on an infrastructure branch
.EXAMPLE
    ./Scripts/Test-BranchPathPolicy.ps1 -BranchName 'infra/pipeline-fixes' -ChangedPath @('tests/src/CharlandCustomizations/Public/Get-Something.Tests.ps1')
    # Fails: source test changes are not allowed on an infrastructure branch
.EXAMPLE
    ./Scripts/Test-BranchPathPolicy.ps1 -BranchName 'my-branch-no-slash' -ChangedPath @('src/CharlandCustomizations/Public/Get-Something.ps1')
    # Fails: branch name must contain a forward slash
.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$BranchName,

    [Parameter(Mandatory)]
    [AllowEmptyCollection()]
    [string[]]$ChangedPath
)

$ErrorActionPreference = 'Stop'

# Branch names must contain a forward slash (e.g., feature/thing, ci/updates)
if ($BranchName -notmatch '/') {
    Write-Error @"
Branch path policy failed.

Branch '$BranchName' does not contain a forward slash.
Branch names must follow the format 'type/description' (e.g., feature/add-audit, ci/update-workflows).

All changes are blocked until the branch is renamed.
"@
    return
}

function Test-WorkflowInfrastructureBranch {
    param(
        [Parameter(Mandatory)]
        [string]$Name
    )

    return $Name -match '(workflow|workflows|infra|infrastructure)' -or
        $Name -match '(^|[\/_-])ci($|[\/_-])'
}

function Test-PathPrefix {
    param(
        [Parameter(Mandatory)]
        [string]$Path,

        [Parameter(Mandatory)]
        [string[]]$Prefix
    )

    $normalizedPath = $Path -replace '\\', '/'

    foreach ($item in $Prefix) {
        $normalizedPrefix = $item.TrimEnd('/')
        if ($normalizedPath -eq $normalizedPrefix -or $normalizedPath.StartsWith("$normalizedPrefix/")) {
            return $true
        }
    }

    return $false
}

$isWorkflowInfrastructureBranch = Test-WorkflowInfrastructureBranch -Name $BranchName

if ($isWorkflowInfrastructureBranch) {
    # Infrastructure branches own: .github, .kiro, .vscode, Scripts, tests/scripts
    # Blocked from: src, tests/src
    $blockedPrefixes = @('src', 'tests/src')
    $branchType = 'workflow/infrastructure branch'
}
else {
    # Normal code branches own: src, tests/src
    # Blocked from: .github, .kiro, .vscode, Scripts, tests/scripts
    $blockedPrefixes = @('.github', '.kiro', '.vscode', 'Scripts', 'tests/scripts')
    $branchType = 'normal code branch'
}

$blockedPaths = @(
    foreach ($path in $ChangedPath) {
        if (Test-PathPrefix -Path $path -Prefix $blockedPrefixes) {
            $path
        }
    }
)

if ($blockedPaths.Count -gt 0) {
    $blockedPrefixText = ($blockedPrefixes | ForEach-Object { "$_/" }) -join ', '
    Write-Error @"
Branch path policy failed.

Branch '$BranchName' is treated as a $branchType.
Do not include changes under $blockedPrefixText on this branch type.

Blocked changed paths:
$($blockedPaths -join [Environment]::NewLine)

Split this work into a branch whose name matches the kind of change being made.
"@
}

Write-Output "Branch path policy passed for '$BranchName'."
