function Invoke-CCScriptMultiRegionProfile {
  <#
.SYNOPSIS
    Invokes AWS commands across multiple AWS Profiles and regions to gather data.

.DESCRIPTION
    Executes a ScriptBlock against multiple AWS accounts (via profiles) and regions,
    collecting the output from each invocation. Each output object is optionally
    enriched with the AccountId and Region it came from, making it easy to aggregate
    and compare data across your AWS estate.

    Designed for read-only data gathering (e.g., Get-EC2SecurityGroup, Get-S3Bucket,
    Get-IAMUser). The ScriptBlock runs with AWS environment variables
    (AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_SESSION_TOKEN or AWS_PROFILE, plus
    AWS_DEFAULT_REGION) set for each account/region iteration.

    Use -OutputSubTemplate to emit a starter script template that calls this function,
    which you can customize for your specific data-gathering scenario.

.PARAMETER ProfileName
    One or more AWS profile names to iterate over. Accepts pipeline input.
    If not specified, uses the current default AWS profile.

.PARAMETER Region
    One or more AWS regions to query per profile. Defaults to the current default region.

.PARAMETER ScriptBlock
    The ScriptBlock to execute for each account/region combination.

.PARAMETER IncludeAccountId
    When specified, adds an AccountId property to each output object.

.PARAMETER IncludeRegion
    When specified, adds a Region property to each output object.

.PARAMETER IncludeProfileName
    When specified, adds a ProfileName property to each output object.

.PARAMETER NoProgress
    Suppress progress bar output.

.PARAMETER OutputSubTemplate
    When specified, outputs a string containing a ScriptBlock function stub with CmdletBinding,
    param block, and begin/process/end structure. Assign the output to a variable and
    convert it to a ScriptBlock (e.g. `[scriptblock]::Create($output)`) before passing to -ScriptBlock.

.PARAMETER AccessKey
    AWS access key for explicit credentials. Optional.

.PARAMETER SecretKey
    AWS secret key for explicit credentials. Optional.

.PARAMETER SessionToken
    AWS session token for temporary credentials. Optional.

.PARAMETER Credential
    Pre-built AWS credential object. Optional.

.PARAMETER ProfileLocation
    Custom credential file path. Optional.

.PARAMETER EndpointUrl
    Custom AWS service endpoint URL. Optional.

.EXAMPLE
    Invoke-CCScriptMultiRegionProfile -ProfileName 'dev','prod' -Region 'us-east-1' `
        -ScriptBlock { Get-STSCallerIdentity } -IncludeRegion -IncludeProfileName

.EXAMPLE
    Get-AWSCredential -ListProfileDetail | Select-Object -ExpandProperty ProfileName |
        Invoke-CCScriptMultiRegionProfile -Region 'us-east-1' `
            -ScriptBlock { Get-S3Bucket } -IncludeAccountId -IncludeProfileName

.EXAMPLE
    Invoke-CCScriptMultiRegionProfile -OutputSubTemplate

    Outputs a ScriptBlock function stub with param/begin/process/end blocks
    that you can assign to a variable and pass to -ScriptBlock.

.NOTES
    Generated by Kiro using Auto, reviewed by ccharland
#>
  [CmdletBinding(DefaultParameterSetName = 'Execute')]
  # Suppress: StoredAWSCredentials is a well-known AWS.Tools global variable used to detect the current session profile
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidGlobalVars', '',
    Justification = 'AWS.Tools uses global:StoredAWSCredentials and global:StoredAWSRegion for session state; must read/write them to set context for ScriptBlock execution')]
  [Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUsePSCredentialType', '',
    Justification = 'Credential parameter accepts an AWSCredentials object from AWS.Tools, not a PSCredential')]
  param(
    [Parameter(ValueFromPipeline, ValueFromPipelineByPropertyName, ParameterSetName = 'Execute')]
    [string[]]$ProfileName,

    [Parameter(ValueFromPipeline, ValueFromPipelineByPropertyName, ParameterSetName = 'Execute')]
    [string[]]$Region,

    [Parameter(Mandatory, ParameterSetName = 'Execute')]
    [scriptblock]$ScriptBlock,

    [Parameter(ParameterSetName = 'Execute')]
    [switch]$IncludeAccountId,

    [Parameter(ParameterSetName = 'Execute')]
    [switch]$IncludeRegion,

    [Parameter(ParameterSetName = 'Execute')]
    [switch]$IncludeProfileName,

    [Parameter(ParameterSetName = 'Execute')]
    [switch]$NoProgress,

    [Parameter(Mandatory, ParameterSetName = 'SubTemplate')]
    [switch]$OutputSubTemplate,

    # AWS common parameters (credential passthrough for Get-STSCallerIdentity validation)
    [Parameter(ParameterSetName = 'Execute')]
    [string]$AccessKey,

    [Parameter(ParameterSetName = 'Execute')]
    [string]$SecretKey,

    [Parameter(ParameterSetName = 'Execute')]
    [string]$SessionToken,

    [Parameter(ParameterSetName = 'Execute')]
    $Credential,

    [Parameter(ParameterSetName = 'Execute')]
    [string]$ProfileLocation,

    [Parameter(ParameterSetName = 'Execute')]
    [string]$EndpointUrl
  )

  begin {
    # When -OutputSubTemplate is specified, emit a function stub for use as a ScriptBlock
    if ($OutputSubTemplate) {
      $subTemplate = @'
{
    <#
    .SYNOPSIS
        ScriptBlock stub for Invoke-CCScriptMultiRegionProfile.

    .DESCRIPTION
        This function runs once per profile/region iteration. AWS context
        (credentials and region) is already set by the caller. Add your
        data-gathering logic in the process block.

    .NOTES
        Generated by Invoke-CCScriptMultiRegionProfile -OutputSubTemplate
    #>
    [CmdletBinding()]
    param(
        # Add parameters your ScriptBlock needs here, e.g.:
        # [string]$ResourceTag = 'Environment'
    )

    begin {
        # One-time setup per iteration (initialize collections, set filters, etc.)
        $results = [System.Collections.Generic.List[object]]::new()
    }

    process {
        # Data-gathering logic — AWS credentials and region are already in scope.
        # Replace the example below with your cmdlet(s):
        # $instances = Get-EC2Instance
        # $buckets = Get-S3Bucket
        $identity = Get-STSCallerIdentity
        $results.Add($identity)
    }

    end {
        # Return collected results to the pipeline
        $results
    }
}
'@
      Write-Output $subTemplate
      return
    }

    # Build base AWS splat from credential parameters then remove ProfileName/Region
    # since those are arrays used for iteration in this function, not single-value
    # credential params to pass to AWS cmdlets directly.
    $awsParams = New-AWSParamSplat -BoundParameters $PSBoundParameters
    $awsParams.Remove('ProfileName') | Out-Null
    $awsParams.Remove('Region') | Out-Null
    if (-not $ProfileName) {
      # Try the shell's current stored credential profile name
      $currentProfile = $null
      if ($StoredAWSCredentials) {
        $currentProfile = $StoredAWSCredentials
      }
      if (-not $currentProfile) {
        # Fall back: check if there's a default profile in the credential store
        $defaultProfile = (Get-AWSCredential -ListProfileDetail |
          Where-Object { $_.ProfileName -eq 'default' } |
          Select-Object -First 1 -ExpandProperty ProfileName)
        if ($defaultProfile) {
          $currentProfile = $defaultProfile
        }
      }
      if ($currentProfile) {
        $ProfileName = @($currentProfile)
      }
      else {
        Write-Error "No ProfileName specified and no current AWS profile found. Use -ProfileName or Set-AWSCredential."
        return
      }
    }

    if (-not $Region) {
      $defaultRegion = (Get-DefaultAWSRegion).Region
      if ($defaultRegion) {
        $Region = @($defaultRegion)
      }
      else {
        Write-Error "No region specified and no default AWS region set. Use -Region or Set-DefaultAWSRegion."
        return
      }
    }
    $profileCount = 0
    $regionTotal = $Region.Count

    # Match common AWS.Tools missing-region failures:
    # - "No region..." text
    # - "RegionEndpoint" / "ServiceURL" configuration errors
    # - Explicit "DefaultAWSRegion is not configured"/"no default region" failures.
    $missingRegionPatternAlternatives = @(
      'no\s+region(?:\s*endpoint)?\b'
      '\bregionendpoint\b'
      'serviceurl\s+configured'
      'defaultawsregion.*(not\s+configured|not\s+set)'
      'no\s+default\s+aws\s+region'
      'region.*not.*(configured|specified|set)'
    )
    $missingRegionPattern = '(?i)(' + ($missingRegionPatternAlternatives -join '|') + ')'
  }

  process {
    foreach ($prof in $ProfileName) {
      $profileCount++
      if (-not $NoProgress) {
        Write-Progress -Id 1 -Activity "Processing AWS Profiles" `
          -Status "Profile: $prof (#$profileCount)" `
          -CurrentOperation "Authenticating..."
      }

      # Validate credentials before doing any work for this profile
      # Override ProfileName per iteration; base awsParams carries other credential params
      $iterParams = $awsParams.Clone()
      $iterParams['ProfileName'] = $prof
      try {
        $identity = Get-STSCallerIdentity @iterParams -ErrorAction Stop
        $accountId = $identity.Account
        Write-Verbose "Profile '$prof' resolved to AccountId: $accountId"
      }
      catch {
        if ($_.Exception.Message -match $missingRegionPattern) {
          $missingRegionError = [System.Management.Automation.ErrorRecord]::new(
            $_.Exception,
            'InvokeCCScriptMultiRegionProfile.MissingRegion',
            [System.Management.Automation.ErrorCategory]::InvalidOperation,
            $prof
          )
          $PSCmdlet.ThrowTerminatingError($missingRegionError)
        }
        Write-Warning "Skipping profile '${prof}': unable to authenticate - $_"
        continue
      }

      # Resolve the profile into concrete AccessKey/SecretKey/SessionToken.
      # For profiles stored in the credentials file (e.g., from Update-CCSSOCredentialList),
      # read the keys directly. This avoids SSO token re-resolution and SDK caching issues.
      $resolvedCreds = $null
      try {
        # Get-AWSCredential -ProfileName with the profile's location resolves correctly
        # because it reads directly from the ini file, not from the SSO token cache.
        $profileDetail = Get-AWSCredential -ListProfileDetail |
        Where-Object { $_.ProfileName -eq $prof } | Select-Object -First 1

        if ($profileDetail -and $profileDetail.ProfileLocation) {
          $credObj = Get-AWSCredential -ProfileName $prof -ProfileLocation $profileDetail.ProfileLocation
          if ($credObj -and $credObj.GetCredentials) {
            $resolvedCreds = $credObj.GetCredentials()
          }
        }

        if (-not $resolvedCreds) {
          # Fall back: try without explicit ProfileLocation
          $credObj = Get-AWSCredential -ProfileName $prof
          if ($credObj -and $credObj.GetCredentials) {
            $resolvedCreds = $credObj.GetCredentials()
          }
        }
      }
      catch {
        Write-Verbose "Could not resolve credentials for profile '$prof': $_"
      }

      $regionIndex = 0
      foreach ($r in $Region) {
        $regionIndex++
        $regionPercent = [int](($regionIndex / $regionTotal) * 100)
        if (-not $NoProgress) {
          Write-Progress -Id 2 -ParentId 1 -Activity "Processing Regions for '$prof'" `
            -Status "Region: $r ($regionIndex of $regionTotal)" `
            -PercentComplete $regionPercent
        }

        Write-Verbose "Executing against Profile='$prof', Region='$r'"

        try {
          # Save current environment variables and AWS session state
          $origAK = $env:AWS_ACCESS_KEY_ID
          $origSK = $env:AWS_SECRET_ACCESS_KEY
          $origST = $env:AWS_SESSION_TOKEN
          $origRegion = $env:AWS_DEFAULT_REGION
          $origProfile = $env:AWS_PROFILE
          $origStoredRegion = $global:StoredAWSRegion
          $origStoredCreds = $global:StoredAWSCredentials

          if ($resolvedCreds -and $resolvedCreds.AccessKey) {
            # Set environment variables that the AWS SDK always respects
            $env:AWS_ACCESS_KEY_ID = $resolvedCreds.AccessKey
            $env:AWS_SECRET_ACCESS_KEY = $resolvedCreds.SecretKey
            $env:AWS_SESSION_TOKEN = $resolvedCreds.Token
            $env:AWS_DEFAULT_REGION = $r
            $env:AWS_PROFILE = $null
            # Set AWS Tools for PowerShell session variables so cmdlets resolve without -Region/-ProfileName
            $global:StoredAWSRegion = $r
            $global:StoredAWSCredentials = $prof
          }
          else {
            $env:AWS_ACCESS_KEY_ID = $null
            $env:AWS_SECRET_ACCESS_KEY = $null
            $env:AWS_SESSION_TOKEN = $null
            $env:AWS_DEFAULT_REGION = $r
            $env:AWS_PROFILE = $prof
            $global:StoredAWSRegion = $r
            $global:StoredAWSCredentials = $prof
          }

          Write-Verbose "Invoking scriptblock for Profile='$prof', Region='$r'"
          $results = & $ScriptBlock

          if ($results) {
            foreach ($item in $results) {
              $props = [ordered]@{}

              # If the item is a simple type (string, number, etc.), wrap it so enrichment works
              if ($item -is [string]) {
                $props['Value'] = $item
              }
              elseif ($item.GetType().IsPrimitive -or $item -is [decimal]) {
                $props['Value'] = $item
              }
              else {
                foreach ($p in $item.PSObject.Properties) {
                  $props[$p.Name] = $p.Value
                }
              }

              if ($IncludeAccountId) { $props['AccountId'] = $accountId }
              if ($IncludeRegion) { $props['Region'] = $r }
              if ($IncludeProfileName) { $props['ProfileName'] = $prof }

              $enriched = [PSCustomObject]$props

              $propNames = [string[]]$props.Keys
              $propSet = [System.Management.Automation.PSPropertySet]::new(
                'DefaultDisplayPropertySet', $propNames
              )
              $enriched | Add-Member -MemberType MemberSet -Name PSStandardMembers -Value $propSet -Force

              $enriched
            }
          }
          else {
            Write-Verbose "No results returned for Profile='$prof', Region='$r'"
          }
        }
        catch {
          Write-Warning "Error executing ScriptBlock for Profile='${prof}', Region='${r}': $_"
        }
        finally {
          # Restore original environment variables and AWS session state
          $env:AWS_ACCESS_KEY_ID = $origAK
          $env:AWS_SECRET_ACCESS_KEY = $origSK
          $env:AWS_SESSION_TOKEN = $origST
          $env:AWS_DEFAULT_REGION = $origRegion
          $env:AWS_PROFILE = $origProfile
          $global:StoredAWSRegion = $origStoredRegion
          $global:StoredAWSCredentials = $origStoredCreds
        }

      }
      if (-not $NoProgress) {
        Write-Progress -Id 2 -ParentId 1 -Activity "Processing Regions for '$prof'" -Completed
      }
    }
  }

  end {
    if (-not $NoProgress) {
      Write-Progress -Id 1 -Activity "Processing AWS Profiles" -Completed
    }
  }
}