<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Public/Git/Install-CCGitHooks.ps1"
}

Describe 'Install-CCGitHooks' -Tag 'Unit' {

    BeforeEach {
        # Set up temporary git directory structure in TestDrive
        New-Item -Path "TestDrive:\repo\.git\hooks" -ItemType Directory -Force | Out-Null
        New-Item -Path "TestDrive:\repo\.githooks" -ItemType Directory -Force | Out-Null

        # Mock git rev-parse to return TestDrive paths
        Mock git {
            param()
            # Determine which git subcommand was called based on args
            if ($args -contains '--git-dir') {
                return "TestDrive:\repo\.git"
            }
            if ($args -contains '--show-toplevel') {
                return "TestDrive:\repo"
            }
            # For git config calls, return empty
            return $null
        }

        # Suppress LASTEXITCODE from git mocks
        $global:LASTEXITCODE = 0

        # Mock Write-Host to suppress output
        Mock Write-Host {}

        # Mock chmod for cross-platform compatibility
        Mock chmod {}
    }

    Context 'Source hook copied to destination' {

        It 'Copies source hook file to .git/hooks/pre-commit with matching content' {
            # Arrange - create source hook
            $sourceContent = '#!/bin/sh' + "`n" + 'echo "running pre-commit hook"'
            Set-Content -Path "TestDrive:\repo\.githooks\pre-commit" -Value $sourceContent -NoNewline

            # Mock git to return proper paths
            Mock git {
                if ($args -contains '--git-dir') {
                    return (Join-Path $TestDrive 'repo\.git')
                }
                if ($args -contains '--show-toplevel') {
                    return (Join-Path $TestDrive 'repo')
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            # Act
            Install-CCGitHooks

            # Assert - destination file exists with matching content
            $destPath = Join-Path $TestDrive 'repo\.git\hooks\pre-commit'
            $destPath | Should -Exist
            $destContent = Get-Content -Path $destPath -Raw
            $srcContent = Get-Content -Path (Join-Path $TestDrive 'repo\.githooks\pre-commit') -Raw
            $destContent | Should -Be $srcContent
        }
    }

    Context 'Existing hook without -Force prompts user' {

        It 'Calls Read-Host to prompt user when hook already exists and -Force not specified' {
            # Arrange - create source and existing destination hook
            $sourceContent = '#!/bin/sh' + "`n" + 'echo "new hook"'
            Set-Content -Path "TestDrive:\repo\.githooks\pre-commit" -Value $sourceContent -NoNewline

            $existingContent = '#!/bin/sh' + "`n" + 'echo "old hook"'
            Set-Content -Path "TestDrive:\repo\.git\hooks\pre-commit" -Value $existingContent -NoNewline

            Mock git {
                if ($args -contains '--git-dir') {
                    return (Join-Path $TestDrive 'repo\.git')
                }
                if ($args -contains '--show-toplevel') {
                    return (Join-Path $TestDrive 'repo')
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            # Mock Read-Host to return 'y' (accept overwrite)
            Mock Read-Host { return 'y' }

            # Act
            Install-CCGitHooks

            # Assert - Read-Host was called
            Should -Invoke Read-Host -Times 1 -Exactly
        }
    }

    Context 'Force overwrites without prompt' {

        It 'Overwrites existing hook without prompting when -Force is specified' {
            # Arrange - create source and existing destination hook
            $sourceContent = '#!/bin/sh' + "`n" + 'echo "new hook"'
            Set-Content -Path "TestDrive:\repo\.githooks\pre-commit" -Value $sourceContent -NoNewline

            $existingContent = '#!/bin/sh' + "`n" + 'echo "old hook"'
            Set-Content -Path "TestDrive:\repo\.git\hooks\pre-commit" -Value $existingContent -NoNewline

            Mock git {
                if ($args -contains '--git-dir') {
                    return (Join-Path $TestDrive 'repo\.git')
                }
                if ($args -contains '--show-toplevel') {
                    return (Join-Path $TestDrive 'repo')
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            Mock Read-Host { return 'n' }

            # Act
            Install-CCGitHooks -Force

            # Assert - Read-Host was NOT called and file was overwritten
            Should -Invoke Read-Host -Times 0 -Exactly
            $destPath = Join-Path $TestDrive 'repo\.git\hooks\pre-commit'
            $destContent = Get-Content -Path $destPath -Raw
            $srcContent = Get-Content -Path (Join-Path $TestDrive 'repo\.githooks\pre-commit') -Raw
            $destContent | Should -Be $srcContent
        }
    }

    Context 'User declines overwrite' {

        It 'Preserves existing hook when user responds with value other than y' {
            # Arrange - create source and existing destination hook
            $sourceContent = '#!/bin/sh' + "`n" + 'echo "new hook"'
            Set-Content -Path "TestDrive:\repo\.githooks\pre-commit" -Value $sourceContent -NoNewline

            $existingContent = '#!/bin/sh' + "`n" + 'echo "old hook"'
            Set-Content -Path "TestDrive:\repo\.git\hooks\pre-commit" -Value $existingContent -NoNewline

            Mock git {
                if ($args -contains '--git-dir') {
                    return (Join-Path $TestDrive 'repo\.git')
                }
                if ($args -contains '--show-toplevel') {
                    return (Join-Path $TestDrive 'repo')
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            # Mock Read-Host to decline
            Mock Read-Host { return 'N' }

            # Act
            Install-CCGitHooks

            # Assert - existing hook content is preserved unchanged
            $destPath = Join-Path $TestDrive 'repo\.git\hooks\pre-commit'
            $destContent = Get-Content -Path $destPath -Raw
            $destContent | Should -Be $existingContent
        }
    }

    Context 'Missing source hook file' {

        It 'Writes error and does not create destination when source hook is missing' {
            # Arrange - no source hook file exists, but git dir structure is present
            Mock git {
                if ($args -contains '--git-dir') {
                    return (Join-Path $TestDrive 'repo\.git')
                }
                if ($args -contains '--show-toplevel') {
                    return (Join-Path $TestDrive 'repo')
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            # Act & Assert - function writes error (terminating due to ErrorActionPreference = Stop)
            { Install-CCGitHooks } | Should -Throw '*Source hook not found*'

            # Assert - destination was not created
            $destPath = Join-Path $TestDrive 'repo\.git\hooks\pre-commit'
            $destPath | Should -Not -Exist
        }
    }
}
