<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    . "$PSScriptRoot/../../../src/CharlandCustomizations/Public/Git/Test-CCCommitSignatures.ps1"
}

Describe 'Test-CCCommitSignatures' -Tag 'Unit' {

    BeforeEach {
        # Mock Write-Host to suppress output during tests
        Mock Write-Host {}
        Mock Write-Warning {}
    }

    Context 'Valid signature returns true' {

        It 'Returns $true when most recent commit has valid signature (status G)' {
            # Arrange - mock git to simulate a valid git repo with signed commit
            Mock git {
                if ($args -contains 'rev-parse') {
                    $global:LASTEXITCODE = 0
                    return '.git'
                }
                if ($args -contains 'log') {
                    $global:LASTEXITCODE = 0
                    return 'abc1234deadbeef1234567890abcdef12345678|G|User Name|commit message'
                }
                if ($args -contains 'config') {
                    $global:LASTEXITCODE = 0
                    return 'true'
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            # Act
            $result = Test-CCCommitSignatures -Count 1

            # Assert
            $result | Should -Be $true
        }
    }

    Context 'No signature returns false' {

        It 'Returns $false when most recent commit has no signature (status N)' {
            # Arrange - mock git to simulate a valid git repo with unsigned commit
            Mock git {
                if ($args -contains 'rev-parse') {
                    $global:LASTEXITCODE = 0
                    return '.git'
                }
                if ($args -contains 'log') {
                    $global:LASTEXITCODE = 0
                    return 'abc1234deadbeef1234567890abcdef12345678|N||commit message'
                }
                if ($args -contains 'config') {
                    $global:LASTEXITCODE = 0
                    return 'true'
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            # Act
            $result = Test-CCCommitSignatures -Count 1

            # Assert
            $result | Should -Be $false
        }
    }

    Context 'Not a git repository' {

        It 'Writes error and returns $false when not in a git repository' {
            # Arrange - mock git rev-parse to fail (not a git repo)
            Mock git {
                if ($args -contains 'rev-parse') {
                    $global:LASTEXITCODE = 128
                    return 'fatal: not a git repository'
                }
                return $null
            }
            $global:LASTEXITCODE = 0

            # Act - function has ErrorActionPreference = Stop, so Write-Error becomes terminating
            # We need to catch the terminating error
            $result = $null
            $errorCaught = $null
            try {
                $result = Test-CCCommitSignatures -Count 1
            }
            catch {
                $errorCaught = $_
            }

            # Assert - either returns $false or throws with the expected message
            if ($null -ne $errorCaught) {
                $errorCaught.Exception.Message | Should -BeLike '*Not in a git repository*'
            }
            else {
                $result | Should -Be $false
            }
        }
    }
}
