<#
.NOTES
    Generated by Kiro using Claude Sonnet 4, reviewed by ccharland
#>
BeforeAll {
    $script:SUTPath = "$PSScriptRoot/../../Scripts/Test-SrcTestCoverage.ps1"

    # Helper: run the script with custom SrcPath / TestsPath, capturing errors
    function Invoke-SrcTestCoverage {
        [CmdletBinding()]
        param(
            [string]$SrcPath,
            [string]$TestsPath
        )
        $scriptContent = Get-Content $script:SUTPath -Raw
        $scriptDir = Split-Path $script:SUTPath -Parent
        $scriptContent = $scriptContent -replace '\$PSScriptRoot', "'$scriptDir'"

        $sb = [scriptblock]::Create($scriptContent)
        $invokeParams = @{}
        if ($SrcPath) { $invokeParams['SrcPath'] = $SrcPath }
        if ($TestsPath) { $invokeParams['TestsPath'] = $TestsPath }

        & $sb @invokeParams
    }
}

Describe 'Test-SrcTestCoverage' -Tag 'Unit' {

    Context 'When SrcPath does not exist' {

        It 'Throws an error when SrcPath is missing' {
            { Invoke-SrcTestCoverage -SrcPath 'C:\NonExistent\src' -TestsPath 'C:\NonExistent\tests\src' } |
                Should -Throw
        }
    }

    Context 'With a temporary source and test tree' {

        BeforeAll {
            $script:tempRoot = Join-Path ([System.IO.Path]::GetTempPath()) "SrcCovTest_$([System.Guid]::NewGuid().ToString('N').Substring(0,8))"
            $script:tempSrc   = Join-Path $script:tempRoot 'src'
            $script:tempTests = Join-Path $script:tempRoot 'tests' 'src'

            New-Item -ItemType Directory -Path $script:tempSrc   -Force | Out-Null
            New-Item -ItemType Directory -Path $script:tempTests -Force | Out-Null
        }

        AfterAll {
            Remove-Item -Path $script:tempRoot -Recurse -Force -ErrorAction SilentlyContinue
        }

        AfterEach {
            # Clean up any ps1/psm1 test fixtures created by each test
            Get-ChildItem -Path $script:tempSrc   -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue
            Get-ChildItem -Path $script:tempTests -Recurse | Remove-Item -Force -ErrorAction SilentlyContinue
        }

        It 'Passes when all source files have matching test files with It blocks' {
            # Arrange: create a source file and a matching test file
            $srcFile  = Join-Path $script:tempSrc 'Get-Thing.ps1'
            $testFile = Join-Path $script:tempTests 'Get-Thing.Tests.ps1'
            Set-Content -Path $srcFile  -Value "function Get-Thing { }"
            Set-Content -Path $testFile -Value "Describe 'Get-Thing' { It 'works' { \$true | Should -Be \$true } }"

            { Invoke-SrcTestCoverage -SrcPath $script:tempSrc -TestsPath $script:tempTests } |
                Should -Not -Throw
        }

        It 'Throws when a source file has no matching test file' {
            # Arrange: source file but NO test file
            $srcFile = Join-Path $script:tempSrc 'Get-Orphan.ps1'
            Set-Content -Path $srcFile -Value "function Get-Orphan { }"

            { Invoke-SrcTestCoverage -SrcPath $script:tempSrc -TestsPath $script:tempTests } |
                Should -Throw
        }

        It 'Throws when a matching test file exists but contains no It block' {
            # Arrange: test file present but empty of It blocks
            $srcFile  = Join-Path $script:tempSrc 'Get-Empty.ps1'
            $testFile = Join-Path $script:tempTests 'Get-Empty.Tests.ps1'
            Set-Content -Path $srcFile  -Value "function Get-Empty { }"
            Set-Content -Path $testFile -Value "Describe 'Get-Empty' { # no It blocks here }"

            { Invoke-SrcTestCoverage -SrcPath $script:tempSrc -TestsPath $script:tempTests } |
                Should -Throw
        }

        It 'Passes for a multi-function psm1 with a test subdirectory' {
            # Arrange: psm1 with 2+ functions, test subdir with at least one .Tests.ps1
            $moduleDir = Join-Path $script:tempSrc 'MyModule'
            New-Item -ItemType Directory -Path $moduleDir -Force | Out-Null
            $srcFile = Join-Path $moduleDir 'MyModule.psm1'
            Set-Content -Path $srcFile -Value "function Get-A { } `nfunction Get-B { }"

            $testSubDir = Join-Path $script:tempTests 'MyModule' 'MyModule'
            New-Item -ItemType Directory -Path $testSubDir -Force | Out-Null
            Set-Content -Path (Join-Path $testSubDir 'Get-A.Tests.ps1') `
                -Value "Describe 'Get-A' { It 'works' { \$true | Should -Be \$true } }"

            { Invoke-SrcTestCoverage -SrcPath $script:tempSrc -TestsPath $script:tempTests } |
                Should -Not -Throw
        }

        It 'Throws for a multi-function psm1 with an empty test subdirectory' {
            # Arrange: psm1 with 2+ functions, but test subdir has no .Tests.ps1 files
            $moduleDir = Join-Path $script:tempSrc 'EmptyModule'
            New-Item -ItemType Directory -Path $moduleDir -Force | Out-Null
            $srcFile = Join-Path $moduleDir 'EmptyModule.psm1'
            Set-Content -Path $srcFile -Value "function Get-X { } `nfunction Get-Y { }"

            { Invoke-SrcTestCoverage -SrcPath $script:tempSrc -TestsPath $script:tempTests } |
                Should -Throw
        }
    }
}
